skeletonlabs/skeleton

.github/FUNDING.yml
This implemented the funding file and adds a Github Sponsors button for Brain & Bones
=> Create FUNDING.yml and add Github Sponsor

package.json, tsconfig.json
Test of new settings as mentioned in #134
=> Settings to match new library from svelte-create

src/routes/guides/astro/+page.svelte
Did a pure npm run through and added a few missing imports and some wording around the examples.
=> Improvements to the guide and wordsmithing

src/lib/Alert/Alert.svelte, src/routes/+page.svelte, src/routes/components/alerts/+page.svelte
See the attached issue for details.
=> Alert design refresh

src/routes/+layout.svelte, src/routes/docs/comparisons/+page.svelte
See the attached ticket for details.
=> Implement the new Comparison section in the Skeleton docs.

src/lib/Table/DataTable.svelte, src/routes/(inner)/components/data-tables/+page.svelte
See the attached ticket for details.
=> Add color text prop to table, allow inherit text color

src/lib/Tooltip/Tooltip.svelte, src/routes/(inner)/components/tooltips/+page.svelte
See the attached ticket for details. Note this component is probably due for a bit of a refactor soon. The code is a bit messy, probably too many elements and props.
=> Provide additional slot style pros to tooltip

src/lib/Avatar/Avatar.svelte
Altered the implementation for setSize()
This seems to fix #184 for me, but I want to ensure it doesn't negatively affect other uses
If testing agrees this resolves the issue, then I will remove the commented out code
=> Fixed Avatar Size Flashing

scripts/skel
Utilise new all.css
Remove using published SkeletonUI package to make it quicker to use a local package
=> Updates to new install

src/lib/tailwind/theme.cjs, src/lib/tailwind/typography.cjs, tailwind.config.cjs, tsconfig.json, vite.config.js
Just some of the config files.
Good to see that VScode is handling the main files on save
=> Format run

src/lib/components/Table/DataTable.svelte, src/lib/components/Table/DataTable.test.ts, src/lib/components/Table/DataTableService.ts
This refactors some of the code behind the data tables, to allow for better typings underneath a unified function that handles both strings and numbers. I also added in some tests, but I haven't been able to get the test runner to work on my machine, so I'm unable to verify that they actually work.
=> DataTable-typing

src/lib/utilities/LightSwitch/LightSwitch.svelte, src/lib/utilities/LightSwitch/stores.ts
Created a separate stores file to be exposed and altered the lightswitch functionality to use the LocalStorageStore to its fullest
Partially Addresses #291
I feel we have this as fast as reasonable at the moment.
=> Exposed LightSwitch store, Used LocalStorageWritable

src/docs/DocsThemer/DocsThemer.svelte
=> Bugfix: Theme gen randomize labels now set

src/docs/DocsNavigation/DocsSidebar.svelte, src/docs/DocsNavigation/links.ts, src/routes/(inner)/components/tabs/+page.svelte, src/routes/(inner)/docs/contributions/+page.svelte, src/routes/(inner)/docs/contributions/code/+page.svelte, src/routes/(inner)/docs/contributions/requirements/+page.svelte
This handles the process of subdividing the contribution section and making it easier to digest and reference. With several updates and corrections.
=> Contribution guide subdivided

src/routes/(inner)/actions/filters/+page.svelte, src/routes/(inner)/elements/forms/+page.svelte
Adds a link to the Filter generator tool linked in the ticket.
=> Filter generator added to docs

src/lib/styles/typography.css
Simple bugfix to use theme colors.
=> KBD style uses theme colors

src/docs/DocsShell/DocsShell.svelte
=> Fix import statements for doc shell

src/docs/DocsThemer/DocsThemer.svelte, src/docs/DocsThemer/helpers.ts, src/lib/components/ConicGradient/ConicGradient.svelte, src/lib/tailwind/colors.ts
Updated Themer and Conic Gradient to use a local set of default colors found in the `/lib/tailwind` directory.
=> Update Themer and Conic to use local TW default colors

src/lib/utilities/Menu/menu.ts, src/lib/utilities/Tooltip/tooltip.ts, src/routes/(inner)/utilities/menus/+page.svelte, src/routes/(inner)/utilities/tooltips/+page.svelte
Submitting this as a draft for early review.
=> Menu/Tooltip State Handler

src/routes/(inner)/guides/tailwind/+page.svelte
A typo in docs, compatability -> compatibility
=> Just a typo in docs

src/app.html, src/routes/(inner)/components/app-shell/+page.svelte, src/routes/(inner)/guides/frameworks/sveltekit/+page.svelte
Resolves the issue described in the ticket.
=> Updated app html, app shell docs, and SvelteKit guide

src/docs/DocsShell/DocsShell.svelte, src/routes/(inner)/elements/core/+page.svelte
=> Hardcoding github path

src/routes/(inner)/docs/contributions/code/+page.svelte
=> Bugfix for contributor style guide code indents

src/routes/(inner)/components/breadcrumbs/+page.svelte
Quick fix on import statement typo
=> Breadcrumb import fix

src/routes/(inner)/components/paginators/+page.svelte
Quick doc fix to make example work
=> Added comma to make example work

src/docs/DocsThemer/DocsThemer.svelte, src/docs/DocsThemer/Swatches.svelte
Does not reference an issue directly, but is related to #301's discussion.
Didn't touch anything needing tests
Yes 
Yes
Fixes the typing issues introduced when we shifted to statically typing the Tailwind values.
=> Fixes the typing issue in the palette

src/app.html, src/app.postcss, src/docs/DocsThemer/DocsThemer.svelte, src/docs/stores.ts, src/lib/styles/typography.css, src/lib/themes/theme-skeleton.css, src/routes/+layout.svelte
See ticket for details. This PR modifies how the mesh gradient is applied for the default Skeleton theme and ensures it never applies for other presets or when a generate theme is showing.
=> Bugfix for body mesh gradient and themes

src/docs/DocsShell/DocsShell.svelte
Plz Merge my Single Character PR 😛
=> Corrected Style Sheet copy import string

src/routes/(inner)/components/app-shell/+page.svelte
Noticed this in the release notes screen grab if you want to update that as well
=> Typo fix on AppShell

src/docs/DocsNavigation/links.ts, src/routes/(inner)/docs/recommendations/+page.svelte
This includes the new Docs > Recommendations page, including a small curated list of recommended packages.
=> Recommendations page added

src/routes/(inner)/components/conic-gradients/+page.svelte
=> Fixes to conic gradient docs page

src/routes/(inner)/guides/frameworks/sveltekit/+page.svelte, src/routes/(inner)/guides/frameworks/vite/+page.svelte
Move GradientHeading import statement from +layout to +page
=> Fix svelte guide component import error

package-lock.json, package.json, src/docs/DocsAppBar/DocsAppBar.svelte, src/docs/DocsNavigation/DocsSidebar.svelte, src/lib/components/FileButton/FileButton.test.ts, src/lib/components/FileDropzone/FileDropzone.test.ts, src/lib/styles/typography.css, src/routes/(inner)/elements/badges/+page.svelte, src/routes/(inner)/elements/buttons/+page.svelte, src/routes/(inner)/elements/cards/+page.svelte, src/routes/(inner)/elements/lists/+page.svelte, src/routes/(inner)/elements/logo-clouds/+page.svelte, src/routes/(inner)/elements/placeholders/+page.svelte
Dependency Updates - includes Svelte/Kit and Tailwind
=> Dependency Updates - includes Svelte/Kit and Tailwind

src/lib/components/Paginator/Paginator.svelte
Fixed limit of pagination exceeding size with suggestion from @leranjun !
=> Fix for #426

src/lib/themes/theme-skeleton.css
=> fix #425 font family defined twice

.github/pull_request_template.md
=> updated website url

src/lib/components/FileDropzone/FileDropzone.svelte, src/routes/(inner)/docs/contributions/+page.svelte, src/routes/(inner)/docs/contributions/documentation/+page.svelte, src/routes/(inner)/docs/contributions/requirements/+page.svelte
Fix little type on FileDropzone
Added new Documentation Page and menu item
Removed some references from Requirements that now belong in Documentation
=> Documentation Guide Additions

src/lib/utilities/Drawer/Drawer.svelte
=> Fixed drawer animation speed, improved open event handler

src/lib/utilities/Dialog/Dialog.svelte, src/routes/(inner)/utilities/dialogs/+page.svelte
=> Restored Dialog component embed type

src/docs/DocsAppBar/DocsAppBar.svelte
Temporary search option added. Uses Control+K keyboard. Will be replaced with a Dialog + Autocomplete in the next release.
=> Search added

src/lib/components/Accordion/AccordionGroup.svelte
Spelling fix for AccordionGroup class
=> Class id changed to AccordionGroup

src/lib/styles/typography.css
=> Typgraphy pre rounded style fix

src/docs/DocsThemer/DocsThemer.svelte, src/routes/+layout.svelte
=> Hotfix for doc localstorage ternary value

README.md, src/docs/DocsNavigation/DocsSidebar.svelte, src/lib/themes/theme-gold-nouveau.css, src/lib/themes/theme-skeleton.css
Quick merge into master to address doc bug found here:
- https://github.com/Brain-Bones/skeleton/issues/489
This provides a simple temporary fix to get us by for now.
=> Hotpatch: LocalStorage Ternary Bug in Docs

src/lib/components/FileDropzone/FileDropzone.svelte
=> Bugfix for dropzone plurals

src/routes/+error.svelte
=> Added SvelteKit error page

src/lib/utilities/Drawer/Drawer.svelte, src/routes/(inner)/utilities/drawers/+page.svelte
=> Bugfix for drawer focus trapping

src/docs/DocsShell/DocsShell.svelte, src/lib/index.ts, src/lib/utilities/Toast/Toast.svelte, src/lib/utilities/Toast/Toats.test.ts, src/lib/utilities/Toast/stores.ts, src/lib/utilities/Toast/types.ts, src/routes/(inner)/guides/themes/+page.svelte, src/routes/(inner)/utilities/toasts/+page.svelte
=> Toast refactor

src/routes/+layout.svelte
Fixes the error message for `The navigation shape changed - from.routeId should now be from.route.id`
=> Fix console error of route.to.id

src/lib/utilities/Tooltip/tooltip.ts
Fixes #519
Fixes tooltips closing when the cursor hovers over a child element of the element with the tooltip action
=> Fixes #519, Tooltip should stay open now as long as the cursor is inside the tooltip element.

src/lib/utilities/Toast/stores.ts, src/routes/(inner)/utilities/toasts/+page.svelte
=> Resolved toast bugs

src/routes/(inner)/utilities/data-tables/+page.svelte
=> docs: Proofed the DataTables page

src/routes/(inner)/utilities/toasts/+page.svelte
Checked through toast doc page - minor update to toast content example.
=> docs: tweak to toast cotent

src/routes/(inner)/utilities/modals/+page.svelte
Small grammar fix by removing "your these" from the sentence
=> Removed unneccessary 'your these' from docs

src/routes/(inner)/components/app-shell/+page.svelte, src/routes/(inner)/guides/frameworks/sveltekit/+page.svelte
=> Updated app html guides for new display style

svelte.config.js, vite.config.js
=> Updated Svelte config to store Alias info

src/docs/DocsAppBar/DocsAppBar.svelte, src/lib/utilities/Modal/Modal.svelte
=> Fixed modal backdrop click bug, multiple search init bug

src/routes/(inner)/guides/tailwind/+page.svelte
=> Dropped TW aspect plugin reference

src/routes/(inner)/guides/themes/+page.svelte
=> Resolved preset theme import path bug

src/docs/DocsAppBar/DocsAppBar.svelte, src/docs/DocsNavigation/DocsDrawer.svelte, src/docs/DocsNavigation/DocsSidebar.svelte, src/docs/stores.ts, src/lib/index.ts, src/lib/utilities/Drawer/Drawer.svelte, src/lib/utilities/Drawer/stores.ts, src/lib/utilities/Drawer/types.ts, src/routes/(inner)/utilities/drawers/+page.svelte, src/routes/(inner)/utilities/modals/+page.svelte, src/routes/(inner)/utilities/toasts/+page.svelte
=> Drawer Updates

src/docs/DocsNavigation/links.ts, src/routes/(inner)/utilities/drawers/+page.svelte, src/routes/(inner)/utilities/modals/+page.svelte, src/routes/(inner)/utilities/toasts/+page.svelte
=> SK SSR warning for Toasts, Dialogs, and Drawers

src/docs/DocsAppBar/DocsAppBar.svelte, src/docs/DocsNavigation/DocsSidebar.svelte, src/routes/(inner)/elements/buttons/+page.svelte, src/routes/blog/+page.svelte
=> Updated link prefetch syntax

package.json, scripts/post-build.js, scripts/pre-build.js
Adds needed exports on dev version of package.json and adds some scripts to remove/re-add them when SK goes to do it's packaging
=> Build scripts and updated package.json

src/lib/utilities/Modal/examples/ModalExampleForm.svelte, src/lib/utilities/Modal/examples/ModalExampleList.svelte
=> Updated modal example paths to use alias package path

src/lib/utilities/Drawer/stores.ts, src/lib/utilities/Modal/Modal.svelte, src/lib/utilities/Modal/examples/ModalExampleForm.svelte, src/lib/utilities/Modal/examples/ModalExampleList.svelte, src/lib/utilities/Modal/stores.ts
=> Improve TS handling for Modals

src/docs/DocsAppBar/DocsAppBar.svelte
=> bugfix: keep theme menu open when changing theme

src/routes/(inner)/elements/forms/+page.svelte
Fixes the 'instlal' typo to 'install'.
Basic typo fix in the Tailwind Elements Forms docs.
=> Fix install typo

src/lib/components/FileDropzone/FileDropzone.svelte, src/routes/(inner)/components/file-dropzone/+page.svelte
- [ X ] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/skeletonlabs/skeleton/discussions) before submission.
- [ X ] Did you update and run tests before submission using `npm run test`?
Note: Drawer.test.ts is failing from before this commit
- [ X ] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [ X ] Did you update documentation related to your new feature or changes?
Ticket [Fixes #657](https://github.com/skeletonlabs/skeleton/issues/657)
Adds the requested functionality
=> Feat: #657 * New Feature: Change File Drop Zone's text title

src/routes/(inner)/docs/faqs/+page.svelte, src/routes/(inner)/guides/frameworks/sveltekit/+page.svelte, src/routes/(inner)/guides/install/+page.svelte, src/routes/(inner)/guides/styling/+page.svelte, src/routes/(inner)/guides/tailwind/+page.svelte, src/routes/(inner)/guides/themes/+page.svelte, src/routes/(inner)/guides/themes/generator/+page.svelte
=> Update SvelteKit onboarding to use CLI

src/lib/components/Radio/RadioGroup.svelte, src/lib/components/Radio/RadioItem.svelte, src/routes/(inner)/components/radio-groups/+page.svelte
=> RadioItem restProp bugfix, and new padding prop added

src/lib/tailwind/theme.cjs
=> chore: added <alpha-value> placeholder

src/routes/(inner)/components/app-shell/+page.svelte
Fixes #670
Fix typo from `display: content` to `display: contents`
=> Fix typo: content => contents

src/lib/components/Stepper/Step.svelte
=> Replace stepper lock emojii with SVG icon

src/lib/utilities/Drawer/Drawer.test.ts, src/lib/utilities/LocalStorageStore/LocalStorageStore.test.ts, src/lib/utilities/LocalStorageStore/LocalStorageStore.ts
Fixes #677
Additionally this resolves a test case issue with the Drawer tests
=> Updated local storage store, fixed Drawer test case

src/routes/(inner)/utilities/toasts/+page.svelte
There is a missing comma in the Toasts example.
=> docs(toasts): fix missing comma

src/lib/utilities/Toast/stores.ts, src/lib/utilities/Toast/types.ts, src/routes/(inner)/utilities/toasts/+page.svelte
Fixes #682
I'm submitting this for review and feedback. The ticket details the options available. Let me know if we should add/tweak/adjust.
=> Expand toasts with preset feature

src/docs/DocsNavigation/links.ts, src/docs/DocsThemer/DocsThemer.svelte, src/lib/styles/elements/cards.css, src/routes/(inner)/docs/comparisons/+page.svelte, src/routes/(inner)/docs/features/+page.svelte, src/routes/(inner)/docs/why/+page.svelte, src/routes/(inner)/elements/cards/+page.svelte, src/routes/(inner)/elements/core/+page.svelte, src/routes/(inner)/elements/tokens/+page.svelte, src/routes/(inner)/guides/frameworks/+page.svelte, src/routes/(inner)/guides/styling/+page.svelte, src/routes/(inner)/guides/tailwind/+page.svelte, src/routes/(inner)/guides/themes/+page.svelte, src/routes/+page.svelte, src/routes/blog/[slug]/+page.svelte
=> Updates to Why Skeleton, homepage, and card improvements

src/lib/utilities/Modal/Modal.svelte
=> Make modal prompt input required to submit

src/docs/DocsAppBar/DocsAppBar.svelte
=> Doc AppBar small mobile size fix

src/lib/components/Paginator/Paginator.svelte, src/lib/components/Stepper/Step.svelte, src/lib/components/Stepper/Stepper.svelte
=> I18n and style improvements for Stepper and Pagination

src/lib/components/ListBox/ListBoxItem.svelte
=> Fixed listbox item focus offset

src/routes/(inner)/components/file-buttons/+page.svelte, src/routes/(inner)/components/radio-groups/+page.svelte
Fix a few typos here and there. No big changes.
=> docs: fix typos

src/lib/components/Accordion/AccordionGroup.svelte, src/lib/components/AppRail/AppRailTile.svelte, src/lib/components/Breadcrumb/Crumb.svelte, src/lib/components/ConicGradient/ConicGradient.svelte, src/lib/components/FileButton/FileButton.svelte, src/lib/components/FileDropzone/FileDropzone.svelte, src/lib/components/ListBox/ListBoxItem.svelte, src/lib/components/Paginator/Paginator.svelte, src/lib/components/Radio/RadioItem.svelte, src/lib/components/SlideToggle/SlideToggle.svelte, src/lib/components/Stepper/Step.svelte, src/lib/components/Tab/Tab.svelte, src/lib/components/Table/Table.svelte, src/lib/utilities/CodeBlock/CodeBlock.svelte, src/lib/utilities/Drawer/Drawer.svelte, src/lib/utilities/LightSwitch/LightSwitch.svelte, src/lib/utilities/Modal/Modal.svelte, src/routes/(inner)/components/app-rail/+page.svelte
=> Improved component events and event docs

package.json, src/lib/components/AppRail/AppRailTile.svelte, src/lib/components/Breadcrumb/Crumb.svelte
=> Version bumpt to 0.80.9, AppRail and Crumb event forward bug fix

src/docs/DocsNavigation/links.ts, src/routes/blog/+page.svelte, src/routes/blog/rss/+server.ts
=> Add RSS Support to Blog

src/docs/DocsNavigation/DocsSidebar.svelte
=> Add blog to mobile navigation

src/docs/DocsNavigation/links.ts, src/docs/DocsShell/DocsShell.svelte, src/lib/components/InputChip/InputChip.svelte, src/lib/index.ts, src/lib/styles/elements/chips.css, src/lib/styles/forms.css, src/lib/styles/tokens/backgrounds.css, src/lib/themes/theme-skeleton.css, src/routes/(inner)/components/input-chips/+page.svelte, src/routes/(inner)/elements/chips/+page.svelte, src/routes/(inner)/guides/styling/+page.svelte, src/routes/(inner)/template/+page.svelte
=> Chips elements and InputChip component

src/docs/DocsThemer/DocsThemer.svelte, src/lib/components/SlideToggle/SlideToggle.svelte, src/lib/styles/forms.css, src/routes/(inner)/elements/forms/preview/+page.svelte
=> Color input styles added to forms.css

src/docs/DocsAppBar/DocsAppBar.svelte, src/docs/DocsNavigation/links.ts, src/docs/DocsSearch/DocsSearch.svelte, src/lib/utilities/Modal/Modal.svelte, src/lib/utilities/Modal/types.ts, src/routes/(inner)/utilities/modals/+page.svelte
Fixes #567
Fixes #568
Plus various style and feature improvements, such as keyword search.
=> Search improvements

src/lib/components/ListBox/ListBoxItem.svelte
=> Allow undefined listbox selected value

.github/FUNDING.yml
=> Enabled GitHub Sponsors

src/docs/DocsShell/DocsShell.svelte, src/lib/components/TableOfContents/TableOfContents.svelte, src/routes/(inner)/components/table-of-contents/+page.svelte
=> Highlight active Table of Contents heading

src/lib/components/AppRail/AppRailTile.svelte
Just some TS typing for the event and the dispatcher
=> TS: Adding types instead of any on eventhandler and dispatcher

CODE_OF_CONDUCT.md
=> CoC markdown file added

src/routes/(inner)/guides/themes/colors/+page.svelte
Fixed the kinda broken theme color reference sentence.
Fixes #808
=> Fixed the garbled theme color reference sentence.

src/app.html, src/lib/tailwind/settings.cjs, src/lib/tailwind/skeleton.cjs, src/lib/tailwind/theme/colors.cjs, src/lib/tailwind/tokens/backgrounds.cjs, src/lib/tailwind/tokens/border-radius.cjs, src/lib/tailwind/tokens/borders.cjs, src/lib/tailwind/tokens/fills.cjs, src/lib/tailwind/tokens/rings.cjs, src/lib/tailwind/tokens/text.cjs, src/lib/utilities/DataTable/DataTable.ts
=> Performed a format on the code base

src/routes/(inner)/utilities/toasts/+page.svelte
Example code was missing a comma (`,`)
Added missing comma to the example code
=> Fix example code

src/lib/components/ProgressRadial/ProgressRadial.svelte
Value of 0 now still displays inner text
=> Fixed text display for 0%

src/routes/+layout.server.ts, src/routes/+page.server.ts
=> Fix: Set cookie path for theme switcher to root

src/lib/components/ListBox/ListBoxItem.svelte, src/routes/(inner)/components/listboxes/+page.svelte
=> Bugfix for listbox array detection and zero index in docs

package.json, src/routes/(inner)/elements/forms/+page.svelte, src/routes/(inner)/guides/styling/+page.svelte, src/routes/(inner)/guides/tailwind/+page.svelte, tailwind.config.cjs
=> QA Fixes for Onboarding and Forms page

src/routes/(inner)/docs/contributions/documentation/+page.svelte, src/routes/(inner)/utilities/codeblocks/+page.svelte, src/routes/(inner)/utilities/drawers/+page.svelte, src/routes/(inner)/utilities/lightswitches/+page.svelte, src/routes/(inner)/utilities/modals/+page.svelte, src/routes/(inner)/utilities/toasts/+page.svelte
Added some missing commas
Remove extraneous ts-ignores
Fixes #873
=> docs: Modal CodeBlock fixes

package.json
Fixed issue #881 by adding the discussed details to package.json
=> As discussed in issue #881 added more details to package json.

src/routes/(inner)/docs/faqs/+page.svelte
Fix a small typo in the Total Typescript course recommendation link.
=> docs: Fix Typo

src/lib/styles/elements/breadcrumbs.css
Thanks to https://github.com/skeletonlabs/skeleton/issues/889#issuecomment-1407292563.
Fixes #889
=> Fix breadcrumb-nonresponsive regression

src/routes/(inner)/guides/themes/+page.svelte
=> Theme docs updated for better data attribute guidance

src/lib/components/Accordion/Accordion.svelte, src/lib/components/Accordion/AccordionItem.svelte, src/lib/components/AppBar/AppBar.svelte, src/lib/components/AppRail/AppRail.svelte, src/lib/components/AppRail/AppRailTile.svelte, src/lib/components/AppShell/AppShell.svelte, src/lib/components/Avatar/Avatar.svelte, src/lib/components/ConicGradient/ConicGradient.svelte, src/lib/components/FileButton/FileButton.svelte, src/lib/components/FileDropzone/FileDropzone.svelte, src/lib/components/InputChip/InputChip.svelte, src/lib/components/ListBox/ListBox.svelte, src/lib/components/ListBox/ListBoxItem.svelte, src/lib/components/Paginator/Paginator.svelte, src/lib/components/ProgressBar/ProgressBar.svelte, src/lib/components/ProgressRadial/ProgressRadial.svelte, src/lib/components/Radio/RadioGroup.svelte, src/lib/components/Radio/RadioItem.svelte, src/lib/components/RangeSlider/RangeSlider.svelte, src/lib/components/SlideToggle/SlideToggle.svelte, src/lib/components/Stepper/Step.svelte, src/lib/components/Stepper/Stepper.svelte, src/lib/components/Tab/Tab.svelte, src/lib/components/Tab/TabGroup.svelte, src/lib/components/Table/Table.svelte, src/lib/components/TableOfContents/TableOfContents.svelte, src/lib/index.ts
Fixes #910
@niktek this is ready for review. Note this updates ONLY the `/components` portion of the library - it does not yet affect `/utilities` (which contains a few components. Let's plan to circle back during/after the Utilities polish pass is complete.
=> Type alias added for CSS class props

scripts/post-build.js, scripts/tw-settings.json, src/lib/components/Paginator/Paginator.svelte
Remove AmountText from Paginator
Put class at the beginning for quicker resolution
=> Remove amountText and put class first

src/docs/DocsShell/DocsShell.svelte, src/lib/components/AppBar/AppBar.svelte, src/lib/components/FileDropzone/FileDropzone.svelte, src/lib/components/Radio/RadioGroup.svelte, src/lib/components/SlideToggle/SlideToggle.svelte, src/lib/components/Tab/TabGroup.svelte, src/routes/(inner)/components/slide-toggles/+page.svelte, src/routes/(inner)/components/tabs/+page.svelte, src/routes/(inner)/docs/contributions/documentation/+page.svelte
=> Component prop naming consistency

src/lib/styles/variants.css
=> Fix #894 - Explicitly set text-on-X-token in dark mode.

src/docs/DocsNavigation/links.ts, src/routes/(inner)/components/tables/+page.svelte, src/routes/(inner)/elements/tables/+page.svelte, src/routes/(inner)/utilities/data-tables/+page.svelte
=> Delist data table

src/lib/components/Paginator/Paginator.svelte
=> fix: Paginator button classes

src/lib/styles/elements/forms.css
=> fix #941 - set border on input-group on focus-within

src/lib/styles/elements/forms.css
=> Fix for native select unfocused active rows

src/lib/components/Accordion/AccordionItem.svelte
=> Implemented toggle event on Accordion

src/docs/DocsThemer/DocsThemer.svelte
Fixes #960 with SlideToggle doesn't working in Theme Generator page
=> docs: fix outdated SlideToggle prop

src/routes/(inner)/components/tabs/+page.svelte
Fixes #964
- Link to local-storage-stores led to 404 page
- renamed route from `/utlities/local-storage-store` to `/utilities/local-storage-stores` 
=> docs/Fix typo in route to local-storage-stores page

src/lib/components/ListBox/ListBoxItem.svelte, src/lib/components/Radio/RadioItem.svelte, src/lib/components/Tab/Tab.svelte
=> Bugfix for Listbox, RadioItem, Tab double reporting event

src/lib/components/RangeSlider/RangeSlider.svelte
=> Correct RangeSlider prop docs

src/lib/components/Accordion/Accordion.svelte, src/lib/components/Accordion/AccordionItem.svelte
=> Added props to set accordion item caret rotation states

src/lib/components/InputChip/InputChip.svelte
=> Improved tabindex and keyboard interaction for input chips

src/docs/modals/examples/ModalExampleEmbed.svelte, src/docs/stores/stores.ts, src/lib/components/FileDropzone/FileDropzone.svelte, src/lib/utilities/Modal/Modal.svelte, src/routes/(inner)/docs/generator/+page.svelte, src/routes/(inner)/docs/get-started/SectionInstall.svelte, src/routes/(inner)/docs/get-started/SectionStylesheets.svelte, src/routes/(inner)/docs/get-started/SectionTailwind.svelte, src/routes/(inner)/docs/get-started/SectionThemes.svelte, src/routes/(inner)/docs/introduction/+page.svelte, src/routes/(inner)/docs/quickstart/+page.svelte, src/routes/(inner)/docs/styling/+page.svelte, src/routes/(inner)/utilities/modals/+page.svelte, src/routes/(inner)/utilities/popups/+page.svelte
Various fixes and improvements to prep for tomorrow's release.
=> QA cleanup continued

src/lib/utilities/LightSwitch/LightSwitch.svelte
=> fix: LightSwitch height

.github/pull_request_template.md, src/routes/(inner)/utilities/popups/+page.svelte
Fixes #1015 
Fixes Popups documentation typo; fixes broken link to contribution guide in PR template
=> Docs: fix Popups documentation typo; fix pull request template broken link

src/routes/(inner)/components/tables/+page.svelte
Just a tiny typo in documentation
Tiny typo in example code
=> Documentation: Fixes tiny typo in example code

src/routes/(inner)/docs/quickstart/+page.svelte
I have removed the closing tag and now it reads `<section>` insted of `</section>` in **line 77**
- [] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributing)? If not, please amend the branch name using `branch -m new-branch-name`
removed the '/' in section tag
=> Fixes: #1037

src/lib/styles/typography.css
Allow unstyling `<del>`/`<ins>` with `unstyle` or `prose` classes, see #1060
=> allow unstyling del/ins html components

src/lib/components/Stepper/Step.svelte, src/lib/components/Stepper/Stepper.svelte
=> Stepper button type props added

src/lib/components/InputChip/InputChip.svelte
=> Input chip button type fix

src/lib/styles/elements/forms.css
=> Bugfix for input group select option bg color

src/lib/components/FileDropzone/FileDropzone.svelte, src/routes/(inner)/components/file-dropzone/+page.svelte
=> File dropzone binding fix

src/routes/(inner)/elements/breadcrumbs/+page.svelte, src/routes/(inner)/elements/buttons/+page.svelte, src/routes/(inner)/elements/chips/+page.svelte, src/routes/(inner)/elements/gradient-headings/+page.svelte, src/routes/(inner)/elements/lists/+page.svelte, src/routes/(inner)/elements/logo-clouds/+page.svelte, src/routes/(inner)/elements/placeholders/+page.svelte, src/routes/(inner)/elements/tables/+page.svelte
Contributing to : 
- https://github.com/skeletonlabs/skeleton/issues/1049
=> Docs Audit  - Tailwind Group 2 

README.md, src/docs/components/DocsFooter/DocsFooter.svelte, src/docs/layouts/DocsShell/DocsShell.svelte, src/docs/layouts/DocsShell/partials/Header.svelte, src/lib/styles/variants.css, src/routes/(inner)/actions/filters/+page.svelte, src/routes/(inner)/actions/focus-trap/+page.svelte, src/routes/(inner)/components/app-rail/+page.svelte, src/routes/(inner)/components/progress-radials/+page.svelte, src/routes/(inner)/components/range-sliders/+page.svelte, src/routes/(inner)/docs/colors/+page.svelte, src/routes/(inner)/docs/contributing/+page.svelte, src/routes/(inner)/docs/contributing/documentation/+page.svelte, src/routes/(inner)/docs/contributing/requirements/+page.svelte, src/routes/(inner)/docs/contributing/style-guide/+page.svelte, src/routes/(inner)/docs/get-started/+page.svelte, src/routes/(inner)/docs/get-started/SectionInstall.svelte, src/routes/(inner)/docs/get-started/SectionStylesheets.svelte, src/routes/(inner)/docs/get-started/SectionTailwind.svelte, src/routes/(inner)/docs/get-started/SectionThemes.svelte, src/routes/(inner)/docs/introduction/+page.svelte, src/routes/(inner)/docs/quickstart/+page.svelte, src/routes/(inner)/docs/styling/+page.svelte, src/routes/(inner)/docs/tokens/+page.svelte, src/routes/(inner)/docs/variants/+page.svelte, src/routes/(inner)/elements/breadcrumbs/+page.svelte, src/routes/(inner)/elements/forms/+page.svelte, src/routes/(inner)/template/+page.svelte, src/routes/(inner)/utilities/drawers/+page.svelte, src/routes/(inner)/utilities/modals/+page.svelte
Contributing to:
- https://github.com/skeletonlabs/skeleton/issues/1049
Sections:
=> Docs Audit - Critical Sections

src/lib/utilities/Modal/types.ts
- [X ] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/skeletonlabs/skeleton/discussions) before submission.
- [ X] Did you update and run tests before submission using `npm run test`2 were skipped. Is that bad?
- [ X?] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributing)? If not, please amend the branch name using `branch -m new-branch-name`
- [N/A ] Did you update documentation related to your new feature or changes?
Found some doc comment typos and inconsistencies while using Modals
Uhm should it close?
Teach me anything I missed!
=> docs/Modal/types.ts Fixes #1049

src/lib/components/ListBox/ListBox.svelte, src/lib/components/Radio/RadioGroup.svelte, src/lib/styles/elements/tables.css, src/routes/(inner)/components/listboxes/+page.svelte, src/routes/(inner)/components/paginators/+page.svelte, src/routes/(inner)/components/progress-bars/+page.svelte, src/routes/(inner)/components/progress-radials/+page.svelte, src/routes/(inner)/components/radio-groups/+page.svelte, src/routes/(inner)/components/range-sliders/+page.svelte, src/routes/(inner)/components/slide-toggles/+page.svelte, src/routes/(inner)/components/steppers/+page.svelte, src/routes/(inner)/components/table-of-contents/+page.svelte, src/routes/(inner)/components/tables/+page.svelte, src/routes/(inner)/components/tabs/+page.svelte
Contributing to:
- #1049 
--- 
From Chris:
Fixes #1039
=> Docs Audit - Svelte Group 2

src/lib/utilities/Drawer/Drawer.svelte, src/lib/utilities/Drawer/types.ts, src/lib/utilities/Modal/Modal.svelte, src/lib/utilities/Modal/types.ts, src/routes/(inner)/utilities/drawers/+page.svelte, src/routes/(inner)/utilities/lightswitches/+page.svelte, src/routes/(inner)/utilities/modals/+page.svelte, src/routes/(inner)/utilities/popups/+page.svelte, src/routes/(inner)/utilities/toasts/+page.svelte
=> Docs Audit - Utilities

README.md, src/routes/(inner)/docs/contributing/documentation/+page.svelte, src/routes/(inner)/docs/contributing/requirements/+page.svelte, src/routes/(inner)/docs/contributing/style-guide/+page.svelte
Resolves part of https://github.com/skeletonlabs/skeleton/issues/1049
Docs Sections - Group 2 (unassigned)
PR: (not yet available)
=> Docs Update: Docs Section 2

src/lib/components/Stepper/Step.svelte, src/lib/components/Stepper/Stepper.svelte, src/routes/(inner)/components/steppers/+page.svelte
Exports the current Step from the Stepper component so that conditional classes and other dynamic behaviour can be easily implemented without the user having to set up event listeners and make assumptions about the initial default state of the Stepper.
=> Exported current step from Stepper for easier dynamic styling and behaviour.

src/lib/utilities/Popup/popup.ts, src/routes/(inner)/utilities/popups/+page.svelte
=> Fixed issue with popup autoUpdate

src/docs/layouts/DocsShell/DocsShell.svelte, src/docs/layouts/LayoutPage/LayoutPage.svelte, src/lib/components/TableOfContents/TableOfContents.svelte
=> ToC updates per current page tab

src/lib/components/FileDropzone/FileDropzone.svelte, src/lib/components/InputChip/InputChip.svelte, src/lib/components/ListBox/ListBox.svelte, src/lib/components/Radio/RadioItem.svelte, src/lib/components/Tab/Tab.svelte
=> Adjust Sveld autodocs for missing props

src/lib/components/FileDropzone/FileDropzone.svelte
=> Bugfix for dropzone in Firefox

src/lib/components/AppRail/AppRailTile.svelte, src/routes/(inner)/components/app-rail/+page.svelte
=> Improve click event handler for App Rail Tile

src/lib/styles/elements/buttons.css, src/routes/(inner)/elements/buttons/+page.svelte
=> Resolve Safari overflow bug for button group

src/routes/+page.svelte, src/routes/+page.ts
=> Fix: Only fetch the contributor list on the browser to avoid github ratelimit

src/routes/home-partials/HomeSponsors.svelte
=> Fixed the giant space found only on safari

src/lib/utilities/LightSwitch/lightswitch.ts
Rename stroage to storage in the code to have a better DX.
=> refactor: rename stroage to storage

src/routes/(inner)/components/conic-gradients/+page.svelte
=> Fix typo in Animated Spinner sample code

src/routes/(inner)/elements/tables/+page.svelte
=> Table classname fix

src/routes/(inner)/docs/get-started/SectionTailwind.svelte
=> Onboarding dark mode instruction

src/lib/components/TableOfContents/TableOfContents.svelte
=> Avoid ignoring items for having a permalink

src/docs/components/DocsFooter/DocsFooter.svelte
=> Add YouTube social link

src/routes/(inner)/utilities/toasts/+page.svelte
=> Toast codeblock doc fixes

src/lib/utilities/Drawer/Drawer.svelte, src/lib/utilities/Modal/Modal.svelte, src/lib/utilities/Toast/Toast.svelte, src/routes/(inner)/utilities/popups/+page.svelte
Adds Z-Index Documentation and an interactive menu example to the docs.
=> Added Z-Index Documentation & added an Interactive example to Popups

src/routes/home-partials/HomeFeatures.svelte
A simple typo on the homepage.
=> Fix typo in HomeFeatures.svelte

src/routes/(inner)/elements/forms/+page.svelte
Fix a broken link in the Forms documentation
=> Fix broken link in Forms documentation

src/lib/utilities/Popup/popup.ts
=> Bugfix for Popup update args and render

src/lib/utilities/Modal/Modal.svelte
=> Bugfix for modal prompt form submit

src/routes/(inner)/components/steppers/+page.svelte
=> Doc update for Stepper to explain stepTerm

src/routes/(inner)/utilities/modals/+page.svelte
=> Docs update for modal width usage

src/routes/(inner)/elements/core/+page.svelte
Fixes #1207 and uses a relative link instead of actual navigation
=> Fixes broken Link found in #1207

src/routes/(inner)/components/autocomplete/+page.svelte
Implementing an Autocomplete example with Popup utilizing the new focus event that was added.
Implementing an Autocomplete example with Popup utilizing the new focus event that was added.
=> Provide documentation of Autocomplete W/Popup

src/app.postcss, src/routes/(inner)/docs/themes/+page.svelte
=> Resolved font import path

src/routes/(inner)/docs/themes/+page.svelte
=> Resolve themes doc zindex fighting issue

src/lib/styles/elements/buttons.css, src/routes/(inner)/elements/buttons/+page.svelte
=> Bugfix for button icon default padding

src/lib/styles/elements/lists.css
=> List li wrap by default

src/routes/(inner)/docs/themes/+page.svelte
=> Extend Theme docs to cover CSS Properties

src/routes/(inner)/components/app-rail/+page.svelte
=> Added AppRailTile to import

src/routes/(inner)/docs/themes/+page.svelte
https://github.com/skeletonlabs/skeleton/issues/1247
Incorrect link to Design Tokens in docs/themes
=> [Fixes #1247] Design Tokens link updated and removed target _blank

src/lib/components/RangeSlider/RangeSlider.svelte
=> fixed ticks absent for negative values

src/lib/components/AppRail/AppRailTile.svelte, src/routes/(inner)/components/app-rail/+page.svelte
=> Bugfix for AppRailTile not supporting integer 0 value

src/lib/utilities/Modal/Modal.svelte
Fixes #1251 where undefined slot is passed to Modal's
=> Prevent rendering of undefined slot

src/lib/components/ListBox/ListBoxItem.svelte
=> Remove ListBoxItem base padding to favor padding prop

src/lib/utilities/Popup/popup.ts
Fixed #1264 (SyntaxError in popup close query) with early return
=> Fixed #1264 (SyntaxError in popup close query) with early return

src/lib/styles/elements/forms.css
=> Datetime input calendar icon fix

src/lib/components/FileButton/FileButton.test.ts, src/lib/components/FileDropzone/FileDropzone.test.ts, src/lib/components/ListBox/ListBoxItem.test.ts, src/lib/components/RangeSlider/RangeSlider.svelte, src/lib/components/RangeSlider/RangeSlider.test.ts, src/lib/components/SlideToggle/SlideToggle.test.ts
=> Updated range slider ticked functionality, fixed test cases

src/lib/styles/elements/tables.css
=> Bugfix for reversed table sort arrows

src/lib/components/Autocomplete/Autocomplete.svelte, src/routes/(inner)/components/autocomplete/+page.svelte
=> Use inclusive terms for autocomplete props

src/docs/links.ts
Added Divider to the core keywords.
=> Added Divider to the core keywords.

.github/ISSUE_TEMPLATE/bug_report.yml
Included asking for a reproduction and a hint that reproductions will improve the bug answer process
=> Updated Bug_report.yaml

src/lib/utilities/Toast/Toast.svelte
I originally wanted to fix the way Toasts would just "popout" when destroyed:
but ended up changing the animation entirely to this:
I added a crossfade animation and increased the default duration of Toasts to 250ms (from 150) to make them appear a bit smoother. This is kind of a preference thing in regards to the animation.
I definitely don't have much experience when it comes to animations so if anyone wants to tweak it so it's more refined, be my guest! I took inspiration from [Svelte French Toast](https://svelte-french-toast.com/) (yes that library name is amazing).
They use straight CSS via:
```CSS
transition: all 230ms cubic-bezier(0.21, 1.02, 0.73, 1);
```
and
```CSS
transform: translateY(calc(var(--offset, 16px) * var(--factor) * 1px));
```
=> Switch to crossfade instead of fly, increase duration

src/routes/(inner)/docs/contributing/requirements/+page.svelte
Adds instructions for `cspell` into contribution requirements
=> Add instructions for `cspell` to contribution requirements 

src/docs/modals/examples/ModalExampleEmbed.svelte, src/docs/modals/examples/ModalExampleForm.svelte, src/docs/modals/examples/ModalExampleImage.svelte, src/docs/modals/examples/ModalExampleList.svelte
=> Modal component transition content issue

src/lib/utilities/Popup/popup.ts, src/routes/(inner)/utilities/popups/+page.svelte
=> Resolve closeQuery popup logic issue

src/routes/(inner)/components/app-rail/+page.svelte
=> Adjusted Example to only highlight one tile per selection

src/lib/components/Stepper/Step.svelte
Fixes #1328
The problem is due to the removal of the `Step` component from the DOM before the form is able to submit. Making the click handler, `onNext`, asynchronous fixes the issue.
=> Fix: Stepper form submissions

src/lib/components/Accordion/Accordion.svelte, src/lib/components/Accordion/AccordionItem.svelte, src/routes/(inner)/components/accordions/+page.svelte
=> Set disabled state for Accordion or Item

src/routes/(inner)/docs/introduction/+page.svelte
Showing HuntaByte's video in the introduction section
=> Updated to show Huntabyte's video

src/lib/components/InputChip/InputChip.svelte
=> Input chip events for focus blur added

src/routes/(inner)/utilities/popups/+page.svelte
On the popup page of the docs in the examples there are usages of the let keyword when const can be used which is more conventional when working with unchanged objects. So this PR changes those let's to const's.
=> Changed unnecessary let's to const's both in examples and code

src/docs/components/DocsPreview/options.ts, src/lib/styles/variants.css, src/routes/(inner)/docs/variants/+page.svelte
=> Implemented gradient variants and docs

src/lib/utilities/Drawer/Drawer.svelte
=> Fixed mislabeled drawer prop doc

src/lib/components/Autocomplete/Autocomplete.svelte
=> Implement autocomplete limit prop

src/routes/(inner)/utilities/modals/+page.svelte
This fixes a minor typo in the modals docs.
=> fix typo in modals docs

package-lock.json, package.json, src/routes/(inner)/actions/filters/+page.svelte, src/routes/(inner)/components/accordions/+page.svelte, src/routes/(inner)/components/app-shell/+page.svelte, src/routes/(inner)/components/autocomplete/+page.svelte, src/routes/(inner)/components/avatars/+page.svelte, src/routes/(inner)/components/paginators/+page.svelte, src/routes/(inner)/components/progress-bars/+page.svelte, src/routes/(inner)/components/slide-toggles/+page.svelte, src/routes/(inner)/components/tables/+page.svelte, src/routes/(inner)/elements/alerts/+page.svelte, src/routes/(inner)/elements/breadcrumbs/+page.svelte, src/routes/(inner)/elements/cards/+page.svelte, src/routes/(inner)/elements/core/+page.svelte, src/routes/(inner)/elements/forms/+page.svelte, src/routes/(inner)/elements/gradient-headings/+page.svelte, src/routes/(inner)/elements/lists/+page.svelte, src/routes/(inner)/elements/logo-clouds/+page.svelte, src/routes/(inner)/elements/tables/+page.svelte, src/routes/(inner)/utilities/popups/+page.svelte
=> Documentation - consistent images and example text

src/routes/(inner)/elements/forms/settings.ts
Docs change, changes the input for tel and url to match the type (I'm using au phone format), adds type to the settings
=> docs/placeholder-tel-fix 

src/docs/components/DocsSidebar/DocsSidebar.svelte, src/docs/links.ts, src/lib/components/ListBox/ListBoxItem.svelte, src/lib/styles/elements/lists.css, src/routes/(inner)/components/listboxes/+page.svelte, src/routes/(inner)/elements/chat/+page.svelte
=> Implement new Chat UI block

src/lib/components/Accordion/Accordion.svelte, src/routes/(inner)/components/accordions/+page.svelte, src/routes/home-partials/HomeSvelteKit.svelte
=> Added accordion width prop

src/lib/utilities/LightSwitch/LightSwitch.svelte
=> Implement nonce attribute to lightswitch script tag

src/routes/(inner)/actions/filters/+page.svelte
=> SVG filter browser support docs expanded

src/lib/styles/elements/forms.css
=> Styled webkit search cancel button

src/routes/(inner)/docs/introduction/+page.svelte
=> Update introduction videos

scripts/compile-css-to-js.cjs, src/lib/styles/partials/elements.css
- changed paths in elements.css to be relative
- added typograhy plugin to the build scripts to handle the new prose classes
=> Pathing in elements and fixes to build scripts

src/routes/(inner)/components/autocomplete/+page.svelte
- Updated example code for Autocomplete to address popup changes
=> Change 'focus' to 'focus-click' in Autocomplete documentation

src/lib/utilities/Toast/Toast.svelte
`undefined` class in toast when `classes` is not used in the toast settings. (Fixes #1480)
=> bugfix/ undefined class in toast

src/lib/utilities/Popup/popup.ts
=> Fixes `callback` is not a function on hover Popups

src/lib/styles/elements/buttons.css
=> bugfixes/add active styles to btn-icon

src/routes/(inner)/docs/themes/+page.svelte
=> docs/remove extra `the`

package.json
=> Drop V from version in package.json

src/routes/(inner)/docs/variants/+page.svelte
I verified that this website does have a valid SSL: https://www.markferrari.com
=> Update +page.svelte - use https instead of http

src/routes/(inner)/utilities/popups/+page.svelte
=> Popup hover pointer events tip

sites/skeleton.dev/src/lib/layouts/DocsShell/partials/Header.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/documentation/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/style-guide/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/sveld/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte
=> Updates to contributor documentation

packages/skeleton/src/lib/styles/elements/forms.css
=> Bugfix for input group ring styles

packages/skeleton/src/lib/themes/theme-gold-nouveau.css, packages/skeleton/src/lib/themes/theme-modern.css, packages/skeleton/src/lib/themes/theme-rocket.css, packages/skeleton/src/lib/themes/theme-sahara.css, packages/skeleton/src/lib/themes/theme-seafoam.css, packages/skeleton/src/lib/themes/theme-skeleton.css, packages/skeleton/src/lib/themes/theme-vintage.css, sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte
=> Update theme attachment and theme docs

packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte
Fixes #1541 dynamically updated autocomplete options.
=> Fixes #1541 dynamically updated autocomplete options.

packages/skeleton/package.json, packages/skeleton/src/lib/components/Table/Table.svelte, packages/skeleton/src/lib/utilities/CodeBlock/CodeBlock.svelte, packages/skeleton/src/lib/utilities/Drawer/Drawer.svelte, packages/skeleton/src/lib/utilities/Modal/Modal.svelte
Merge dev to master for v1.6.1
=> Merge dev to master for v1.6.1

packages/skeleton/src/lib/components/Paginator/Paginator.svelte
fixes #1550 
`onLast()` sometimes produces floating point numbers as the offset (size/limit)
applied `ceil` to get an Integer always.
=> bugfix: paginator-offset-number

packages/skeleton/package.json, sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte
=> Merge dev to master for 1.6.2

sites/skeleton.dev/src/routes/(inner)/utilities/toasts/+page.svelte
- [ X] Did you update and run tests before submission using `npm run test`?
- [ X] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributing)? If not, please amend the branch name using `branch -m new-branch-name`
- [X ] Did you update documentation related to your new feature or changes?
Documentation update.
Change `Modal Store` to `Toast Store`
=> docs: toast store typo

.changeset/purple-mice-fly.md, packages/skeleton/src/lib/tailwind/tokens/backgrounds.cjs
fixes #1574
`.dark .bg-variant-hover-token` was missing.
=> Bugfix: dark bg-variant-hover-token

sites/skeleton.dev/src/routes/home-partials/HomeStats.svelte
Closes #1467
Updates the homepage stats to reflect the latest statistics.
=> Updated homepage stats

.changeset/empty-apricots-judge.md, packages/skeleton/src/lib/components/Paginator/Paginator.svelte, sites/skeleton.dev/src/routes/(inner)/components/paginators/+page.svelte
Closes #1536 
- added Numeric Row with a prop to show it and a prop to define the max active page siblings.
feat: added pagination-control Numeric row
=> feat: pagination-controls

package.json, packages/create-skeleton-app/pnpm-lock.yaml, packages/skeleton/pnpm-lock.yaml, pnpm-lock.yaml, sites/skeleton.dev/pnpm-lock.yaml
Closes #1624 
Instructions: Changesets automate our changelog. If you modify files in `/package/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.
=> chore: update pnpm-lockfile version to `6.1`

.changeset/good-dingos-attend.md, packages/skeleton/src/lib/styles/partials/typography-prose.css, sites/skeleton.dev/src/lib/styles/blog.css, sites/skeleton.dev/src/routes/+layout.svelte
Resolves bug with prose stylesheet import.
=> Hotpatch for release

.changeset/itchy-hounds-unite.md, packages/skeleton/src/lib/components/Tab/Tab.svelte, packages/skeleton/src/lib/components/Tab/TabAnchor.svelte, packages/skeleton/src/lib/index.ts, sites/skeleton.dev/src/routes/(inner)/components/tabs/+page.svelte
Closes #1583
Added Anchor tab to TabGroup
feat: Added anchor tab to TabGroup.
=> feat: added anchor tab

.changeset/cuddly-adults-hide.md, .changeset/itchy-hounds-unite.md, .changeset/lazy-pants-yawn.md, .changeset/ninety-points-turn.md, .changeset/spotty-parrots-rush.md, .changeset/thick-cougars-notice.md
Closes #1675
Did a quick audit and review of the current state of changeset markdown files.
=> Audit and update to changeset copy

.changeset/wet-bugs-guess.md, packages/skeleton/src/lib/components/InputChip/InputChip.svelte
Added nullsafe access and nullish coalescense to InputChips to handle value being undefined.
- [x ] This PR targets the `dev` branch (NEVER `master`)
=> Added nullsafe access and nullish coalescense to InputChips to handle value being undefined.

sites/skeleton.dev/src/lib/components/DocsAppBar/DocsAppBar.svelte, sites/skeleton.dev/src/lib/components/DocsSidebar/DocsSidebar.svelte, sites/skeleton.dev/src/routes/+page.svelte
Closes #1747
Introduces a link to the Skeleton Store in the core navigation, as well as a small promo banner at the top of the homepage.
=> Store link and promo added

.changeset/big-ligers-rest.md, .changeset/mighty-wombats-report.md, .changeset/silent-bikes-count.md, .changeset/tall-days-shop.md, .changeset/two-spoons-cheer.md, packages/skeleton/postcss.config.cjs, packages/skeleton/src/lib/components/AppRail/AppRail.svelte, packages/skeleton/src/lib/components/AppRail/AppRailAnchor.svelte, packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte, packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte, packages/skeleton/src/lib/components/Paginator/Paginator.svelte, packages/skeleton/src/lib/components/Ratings/Ratings.svelte, packages/skeleton/src/lib/components/TreeView/TreeView.svelte, packages/skeleton/src/lib/components/TreeView/TreeView.test.ts, packages/skeleton/src/lib/components/TreeView/TreeViewItem.svelte, packages/skeleton/src/lib/components/TreeView/TreeViewItem.test.ts, packages/skeleton/src/lib/index.ts, packages/skeleton/src/lib/utilities/Popup/popup.ts, packages/skeleton/svelte.config.js, sites/skeleton.dev/postcss.config.cjs, sites/skeleton.dev/src/lib/components/DocsAppBar/DocsAppBar.svelte, sites/skeleton.dev/src/lib/components/DocsSidebar/DocsSidebar.svelte, sites/skeleton.dev/src/lib/layouts/DocsThemer/DocsThemer.svelte, sites/skeleton.dev/src/lib/layouts/DocsThemer/colors.ts, sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/components/app-rail/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/tree-views/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte, sites/skeleton.dev/src/routes/+page.svelte, sites/skeleton.dev/svelte.config.js
=> Merge for release 1.10.0

.changeset/two-experts-kick.md, packages/skeleton/src/lib/styles/elements/logo-clouds.css
Closes #1767
😄 
bugfix: fixed typo in logo-clouds styles
=> fixed logo-clouds.css typo

sites/skeleton.dev/src/routes/(inner)/components/accordions/+page.svelte, sites/skeleton.dev/src/routes/+page.ts, sites/skeleton.dev/src/routes/blog/blog-service.ts, sites/skeleton.dev/src/routes/home-partials/HomeContributors.svelte, sites/skeleton.dev/src/routes/home-partials/HomeTheming.svelte
none
just fixed a few linting error
Changes are not in `/packages/skeleton`
=> fixes a few lint errors

.changeset/giant-cows-joke.md, packages/skeleton/src/lib/components/Paginator/Paginator.svelte
Closes #1776 
Added separatorText prop to Paginator to allow localization
=> feat/add separatorTest prop to paginator

sites/skeleton.dev/src/routes/(inner)/components/steppers/+page.svelte
French translation for "Step" in this context is "Étape"
=> minor:corrected translation

.changeset/giant-cows-joke.md, .changeset/lucky-roses-sip.md, .changeset/two-experts-kick.md, .changeset/wicked-ravens-itch.md, .changeset/witty-pigs-wave.md, packages/skeleton/src/lib/components/ListBox/ListBox.svelte, packages/skeleton/src/lib/components/ListBox/ListBoxItem.svelte, packages/skeleton/src/lib/components/Paginator/Paginator.svelte, packages/skeleton/src/lib/styles/elements/forms.css, packages/skeleton/src/lib/styles/elements/logo-clouds.css, packages/skeleton/src/lib/utilities/Modal/Modal.svelte, sites/skeleton.dev/src/routes/(inner)/components/accordions/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/steppers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/image-layouts/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/drawers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/toasts/+page.svelte, sites/skeleton.dev/src/routes/+page.ts, sites/skeleton.dev/src/routes/blog/blog-service.ts, sites/skeleton.dev/src/routes/home-partials/HomeContributors.svelte, sites/skeleton.dev/src/routes/home-partials/HomeTheming.svelte
=> Merge for release 1.11.0

sites/skeleton.dev/src/lib/components/DocsAppBar/DocsAppBar.svelte, sites/skeleton.dev/src/routes/+page.svelte
Closes #1819
Removed the promo banner, adjusted the Explore navigation store link.
=> Remove store promo banner, update Explore nav

.github/workflows/release-v2.yml, .github/workflows/release.yml
In preparation of creating a v2 prerelease, I've added the `v2` branch to our GH action workflow.
=> chore: Add `v2` branch to GH action workflow

sites/skeleton.dev/src/routes/+page.svelte
Closes #1864
Appends a new v2 RC promo banner to the top of the doc homepage.
=> v2 RC promo banner for homepage

sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionInstall.svelte
Closes #1874
Correct v2 RC docs for CLI install tag
=> Correct v2 RC docs for CLI install tag

sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionSkeleton.svelte
Closes #1877
v2 install tags fix
=> Resolve package and plugin NPM install tags for v2 RC

sites/skeleton.dev/src/routes/(inner)/docs/tokens/+page.svelte
This looks to me like a copy/paste error.
Created against v2 as requested by @endigo9740  in #1894.
=> Fix border radius description

packages/create-skeleton-app/CHANGELOG.md, packages/create-skeleton-app/package.json, packages/create-skeleton-app/pnpm-lock.yaml, packages/create-skeleton-app/src/creator.js, packages/create-skeleton-app/src/index.js
Added JSON5 to handle serialisation of JS Objects for configuration portions
Added wintry theme
usual formatting BS
=> JSON5 and wintry added

sites/skeleton.dev/src/lib/layouts/DocsThemer/DocsThemer.svelte, sites/skeleton.dev/src/lib/layouts/DocsThemer/types.ts
Reverts skeletonlabs/skeleton#1927
=> Revert "feat: ability to lock colors in theme generator"

.changeset/clean-roses-vanish.md, .changeset/clean-tables-boil.md, .changeset/cool-glasses-grow.md, .changeset/fast-queens-travel.md, .changeset/five-deers-listen.md, .changeset/flat-insects-film.md, .changeset/fluffy-garlics-carry.md, .changeset/forty-seahorses-tan.md, .changeset/fresh-carrots-lick.md, .changeset/fresh-crews-drum.md, .changeset/loud-fans-serve.md, .changeset/many-falcons-carry.md, .changeset/metal-dots-melt.md, .changeset/real-plums-collect.md, .changeset/shy-suits-provide.md, .changeset/silent-games-drop.md, .changeset/slimy-ads-talk.md, .changeset/slimy-garlics-sit.md, .changeset/soft-tables-wave.md, .changeset/spicy-horses-wonder.md, .changeset/spotty-cows-travel.md, .changeset/twenty-spoons-hope.md, .changeset/wild-fans-build.md
Closes #1933
Review and ensure all changesets meet our expectations before the v2 release goes out next week.
=> v2 changeset audit

sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionInstall.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionSkeleton.svelte, sites/skeleton.dev/src/routes/+page.svelte
Closes #1873
Update docs banner and onboarding for v2 stable launch.
=> Update docs banner and onboarding for v2 stable launch

.changeset/nervous-foxes-peel.md, packages/create-skeleton-app/src/creator.js, packages/create-skeleton-app/src/index.js
Empty path seems to skip the validate handler
Error in checking of custom theme
=> Fixed checks of path and custom theme

packages/create-skeleton-app/src/index.js
=> Semi Semi Semi Semi

sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/+page.svelte
Closes #2013
Removed homepage banner and NEW badges
=> Removed homepage banner and NEW badges

sites/skeleton.dev/src/lib/components/DocsAppBar/DocsAppBar.svelte, sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/docs/sponsorship/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/sponsorship/licensing/+page.svelte
Closes #2041
Adds a new Sponsorship promotion page, detailing the upcoming incentives.
=> Sponsor promo page added

.changeset/quick-rats-doubt.md, packages/skeleton/src/lib/utilities/LightSwitch/LightSwitch.svelte
Closes #2088
Added a Title prop to Lightswitch component
=> Added a Title prop to Lightswitch component

.changeset/funny-cows-cry.md, packages/plugin/src/tailwind/tokens/rings.ts
=> fix: Removed semicolon from ring design tokens

sites/skeleton.dev/src/routes/(inner)/docs/colors/+page.svelte
Added a Color Palette to /Colors. 
Responsiveness should be a go, but might be coming back to fix sub 400px width issues once or twice.
=> Color Palette

.changeset/angry-fishes-study.md, packages/plugin/src/styles/components/forms.css
Closes #2119
Applied the Suggestion mentioned in the issue 😄 
=> Separated light/dark classes for input validation variants

.changeset/red-oranges-sneeze.md, packages/skeleton/src/lib/utilities/Drawer/Drawer.svelte, packages/skeleton/src/lib/utilities/Drawer/types.ts, sites/skeleton.dev/src/routes/(inner)/utilities/drawers/+page.svelte
Closes #2138 
Implemented change, and minor cleanup of associated documentation.
Having some weird issues on my local install that have my drawer not working, but @niktek provided video proof.
https://github.com/skeletonlabs/skeleton/assets/91865823/f5b8ca3b-f35e-4060-bcf9-17383df7298b
=> feat:Drawer Transition Duration

packages/skeleton/src/lib/utilities/Modal/stores.ts
=> Fix typo in the Modal utilities comment

sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte
Closes #2221
Added a missing comma in modal documentations example
=> added missing comma

sites/skeleton.dev/src/routes/(inner)/components/accordions/+page.svelte
Closes #2240
Made Día de Muertos example non autocollapse and added a new auto collapse example
=> Update examples for accordion autocollapse

sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte, sites/skeleton.dev/src/routes/+layout.svelte
=> docs: fix https://github.com/skeletonlabs/skeleton/issues/2245

.changeset/eight-toes-itch.md, packages/skeleton/src/lib/utilities/Popup/popup.ts, sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/components/accordions/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/paginators/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/tables/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/tauri/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/chips/+page.svelte, sites/skeleton.dev/src/routes/+layout.svelte
=> Merge for release 11-20-2023

sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/docs/figma/+page.svelte
Adds Figma page to Docs as discussed with @endigo9740 
=> Add Figma page to Docs

.changeset/dry-numbers-jump.md, .changeset/giant-kings-suffer.md, .changeset/mighty-starfishes-leave.md, .changeset/red-drinks-obey.md, packages/plugin/src/tailwind/tokens/borders.ts, packages/plugin/src/tailwind/tokens/text.ts, packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte, packages/skeleton/src/lib/components/Paginator/Paginator.svelte, packages/skeleton/src/lib/components/ProgressBar/ProgressBar.svelte, packages/skeleton/src/lib/utilities/Drawer/Drawer.svelte, sites/skeleton.dev/package.json, sites/skeleton.dev/pnpm-lock.yaml, sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/docs/figma/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionThemes.svelte, sites/skeleton.dev/src/routes/(inner)/docs/tokens/+page.svelte
=> Merge for release 12-6-2023

sites/skeleton.dev/src/routes/(inner)/components/tree-views/+page.svelte
Closes #{[2299](https://github.com/skeletonlabs/skeleton/issues/2299)}
The code example is missing a comma
Add the missing comma
=> Update tree-views docs:  Add the missing comma

sites/skeleton.dev/src/routes/+layout.svelte
=> Remove Console.log() of current path

sites/skeleton.dev/src/routes/(inner)/utilities/drawers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/table-of-contents/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/toasts/+page.svelte
This PR covers a couple of corrections of writing mistakes and a few minor enhancements in order to enhance the documentation quality. Please note that the scope of this PR is the components under `utilities` only.
=> Enhance Utilities Documentation Writing

.changeset/mighty-cycles-drive.md, .changeset/modern-ways-greet.md, .changeset/smart-ligers-rest.md, .changeset/thick-trains-chew.md, README.md, packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte, packages/skeleton/src/lib/components/Avatar/Avatar.svelte, packages/skeleton/src/lib/components/Avatar/Avatar.test.ts, packages/skeleton/src/lib/components/ProgressBar/ProgressBar.svelte, packages/skeleton/src/lib/components/Radio/RadioGroup.svelte, packages/skeleton/src/lib/components/Radio/RadioGroup.test.ts, sites/skeleton.dev/src/app.postcss, sites/skeleton.dev/src/lib/layouts/DocsShell/DocsShell.svelte, sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/components/accordions/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/progress-bars/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/radio-groups/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/tree-views/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/drawers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/table-of-contents/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/toasts/+page.svelte, sites/skeleton.dev/src/routes/+layout.svelte
=> Merge for release 12-19-2023

.changeset/olive-snakes-return.md, packages/skeleton/src/lib/components/Avatar/Avatar.svelte
Closes #2055
Best described in the original issue: https://github.com/skeletonlabs/skeleton/issues/2055
=> Avatar in AppBar rendering incorrectly in Safari

sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte
Hey, 
I think CSpell have missed this spelling mistake
=> Fixed spelling mistake in Contributing guide 

.changeset/dry-socks-suffer.md, .changeset/eight-bugs-report.md, .changeset/gentle-melons-decide.md, .changeset/olive-snakes-return.md, .changeset/smooth-sloths-work.md, .changeset/spotty-ads-care.md, .changeset/stupid-maps-peel.md, .changeset/tough-ghosts-lie.md, .changeset/weak-mugs-judge.md, package.json, packages/plugin/src/styles/components/forms.css, packages/plugin/src/styles/components/tables.css, packages/skeleton/src/lib/actions/FocusTrap/focusTrap.ts, packages/skeleton/src/lib/components/Avatar/Avatar.svelte, packages/skeleton/src/lib/components/Stepper/Step.svelte, packages/skeleton/src/lib/components/Stepper/Stepper.svelte, packages/skeleton/src/lib/utilities/Modal/Modal.svelte, sites/skeleton.dev/src/lib/modals/examples/ModalExampleForm.svelte, sites/skeleton.dev/src/lib/modals/examples/ModalExampleFullscreen.svelte, sites/skeleton.dev/src/routes/(inner)/actions/focus-trap/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/tables/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/forms/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/lightswitches/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/table-of-contents/+page.svelte, sites/skeleton.dev/src/routes/+layout.svelte, sites/skeleton.dev/vite-plugin-skeleton-plugin-watcher/index.ts, sites/skeleton.dev/vite.config.ts
Merge for release January 2, 2024
=> Merge for release January 2, 2024

sites/skeleton.dev/src/routes/(inner)/utilities/lightswitches/+page.svelte
Closes #2420 
Fixed copmonents typo
=> Fixed copmonents typo

sites/skeleton.dev/src/routes/(inner)/components/steppers/+page.svelte
Closes #2418
Clarified Stepper documentation
=> Clarified stepTerm documentation

sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte
Closes #2415
added overflow-hidden to the popup-combobox example
=> docs-popup-combobox-overflow

.changeset/famous-pots-trade.md, .changeset/flat-icons-do.md, .changeset/nasty-terms-allow.md, .changeset/real-cougars-invent.md, .changeset/swift-insects-rush.md, packages/plugin/src/styles/components/modals.css, packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte, packages/skeleton/src/lib/components/InputChip/InputChip.svelte, packages/skeleton/src/lib/components/TreeView/RecursiveTreeView.svelte, packages/skeleton/src/lib/utilities/CodeBlock/CodeBlock.svelte, sites/skeleton.dev/src/routes/(inner)/components/input-chips/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/progress-radials/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte
Merge for release - Jan 30, 2024
=> Merge for release - Jan 30, 2024

sites/skeleton.dev/src/routes/(inner)/docs/ssd/+page.svelte
A user DM'd me on discord pointing out this spelling error.
=> Datatables Guide Typo

sites/skeleton.dev/src/lib/components/DocsSidebar/DocsSidebar.svelte
Closes #2499 
removes the link to the store from the sidebar navigation for small screens
=> remove store link from sidebar navigation

packages/skeleton-react/tailwind.config.js, packages/skeleton-svelte/tailwind.config.js, sites/next.skeleton.dev/tailwind.config.js
Closes #2505
Add special comment to Tailwind config to enable HRM reloading on plugin changes
=> Implement Tailwind config watcher comment

.changeset/fuzzy-apricots-hope.md, .changeset/giant-tomatoes-kick.md, packages/skeleton/src/lib/components/ListBox/ListBox.svelte, packages/skeleton/src/lib/components/ListBox/ListBoxItem.svelte, sites/skeleton.dev/README.md, sites/skeleton.dev/src/lib/components/DocsSidebar/DocsSidebar.svelte, sites/skeleton.dev/src/routes/(inner)/components/listboxes/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/ssd/ClientSSD.svelte, sites/skeleton.dev/src/routes/(inner)/docs/ssd/ServerSSD.svelte
Merge for release - Feb 27, 2024
=> Merge for release - Feb 27, 2024

packages/skeleton-react/src/App.tsx, packages/skeleton-react/src/components/Avatar/Avatar.tsx, packages/skeleton-react/src/components/Avatar/types.ts, packages/skeleton-react/src/lib/index.ts, packages/skeleton-react/src/main.tsx, packages/skeleton-react/src/routes/components/avatars.tsx, packages/skeleton-svelte/.eslintrc.cjs, packages/skeleton-svelte/.prettierrc, packages/skeleton-svelte/README.md, packages/skeleton-svelte/src/app.html, packages/skeleton-svelte/src/lib/components/Avatar/Avatar.svelte, packages/skeleton-svelte/src/lib/components/Avatar/types.ts, packages/skeleton-svelte/src/lib/index.ts, packages/skeleton-svelte/src/routes/+layout.svelte, packages/skeleton-svelte/src/routes/+page.svelte, packages/skeleton-svelte/src/routes/components/avatars/+page.svelte, packages/skeleton-svelte/vite.config.ts, sites/next.skeleton.dev/src/content/components/common/avatars.mdx, sites/next.skeleton.dev/src/content/components/react/avatars.mdx, sites/next.skeleton.dev/src/content/components/svelte/avatars.mdx, sites/next.skeleton.dev/src/examples/components/avatars/Example.svelte, sites/next.skeleton.dev/src/examples/components/avatars/Example.tsx
=> feat: Next-avatar

sites/next.skeleton.dev/src/components/docs/Navigation.astro, sites/next.skeleton.dev/src/content/design/iconography.mdx, sites/next.skeleton.dev/src/content/design/typography.mdx
Closes #2522
NEXT Iconography Docs
=> Iconography doc added

sites/next.skeleton.dev/src/content/components/common/app-bars.mdx
=> fixed appBar docs links

sites/next.skeleton.dev/README.md, sites/next.skeleton.dev/src/components/docs/NavGrid.astro, sites/next.skeleton.dev/src/content/resources/contribute/components.mdx, sites/next.skeleton.dev/src/content/resources/contribute/documentation.mdx, sites/next.skeleton.dev/src/content/resources/contribute/get-started.mdx
Closes #2361
Implements the first full draft of contributor guidelines.
=> NEXT Contributor Guidelines

sites/next.skeleton.dev/package.json, sites/next.skeleton.dev/pnpm-lock.yaml, sites/next.skeleton.dev/src/examples/components/accordions/Example.svelte, sites/next.skeleton.dev/src/examples/components/app-bars/Example.svelte, sites/next.skeleton.dev/src/examples/components/app-bars/ExampleResponsive.svelte, sites/next.skeleton.dev/src/examples/components/app-bars/ExampleToolbar.svelte, sites/next.skeleton.dev/src/examples/components/avatars/Example.svelte
Closes #2572
NEXT Astro docs dependency bump, fix Svelte comps
=> NEXT Astro docs dependency bump, fix Svelte comps

packages/skeleton-react/package.json, packages/skeleton-react/pnpm-lock.yaml, packages/skeleton-react/src/App.test.tsx, packages/skeleton-react/src/App.tsx, packages/skeleton-react/src/components/Accordion/Accordion.test.tsx, packages/skeleton-react/src/components/Accordion/Accordion.tsx, packages/skeleton-react/tests/setup.js, packages/skeleton-react/tsconfig.json, packages/skeleton-react/vite.config.ts
#2363
React Package Vitest and Testing Library Setup
=> NEXT React Package Vitest and Testing Library Setup

sites/next.skeleton.dev/src/components/docs/FrameworkPicker.astro
Closes #2580
BUG: framework picker is not working post doc updates
=> Fix FrameworkPicker bug

packages/skeleton-react/src/components/Progress/Progress.tsx, packages/skeleton-react/src/components/Progress/types.ts, packages/skeleton-react/src/lib/index.ts, packages/skeleton-svelte/src/lib/components/Progress/Progress.svelte, packages/skeleton-svelte/src/lib/components/Progress/types.ts, packages/skeleton-svelte/src/lib/index.ts, packages/skeleton/src/plugin/components/forms.css, sites/next.skeleton.dev/src/content/docs/components/progress/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/progress/react.mdx, sites/next.skeleton.dev/src/content/docs/components/progress/svelte.mdx, sites/next.skeleton.dev/src/examples/components/progress/Example.svelte, sites/next.skeleton.dev/src/examples/components/progress/Example.tsx, sites/next.skeleton.dev/src/examples/components/progress/ExampleColors.svelte, sites/next.skeleton.dev/src/examples/components/progress/ExampleColors.tsx, sites/next.skeleton.dev/src/examples/components/progress/ExampleCustomAnimation.svelte, sites/next.skeleton.dev/src/examples/components/progress/ExampleCustomAnimation.tsx, sites/next.skeleton.dev/src/examples/components/progress/ExampleHeight.svelte, sites/next.skeleton.dev/src/examples/components/progress/ExampleHeight.tsx, sites/next.skeleton.dev/src/examples/components/progress/ExampleIndeterminate.svelte, sites/next.skeleton.dev/src/examples/components/progress/ExampleIndeterminate.tsx, sites/next.skeleton.dev/src/examples/components/progress/ExampleNative.astro
This PR documents the Progress component for both Svelte and React.
=> Feat: Progress docs

.changeset/cuddly-bats-return.md, .changeset/stale-bears-tickle.md, .changeset/thirty-cows-laugh.md, packages/plugin/src/styles/base/core.css, packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte, packages/skeleton/src/lib/components/AppRail/AppRail.svelte, sites/skeleton.dev/src/routes/(inner)/docs/tokens/+page.svelte
=> Merge for release 4/9/2024

sites/skeleton.dev/src/routes/+page.ts
I only have one GitHub account now and its this one :)
=> Removing login filter

sites/skeleton.dev/src/routes/(inner)/elements/chat/+page.svelte
Closes #2638
Fix onMount import on the Chat block docs 
=> Fix onMount import bug

.github/workflows/release-next.yml
=> chore: Add skeleton-next workflow for `next` branch publishes 

.github/workflows/release-next.yaml
=> chore: add next release workflow to `next`

.changeset/lovely-dingos-join.md, packages/skeleton-svelte/package.json, sites/next.skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx
Closes #2678
- Flushes out NextJS/SvelteKit install instructions
- Resolves the Svelte peer dependency for `skeleton-svelte`
=> v3 Docs and Svelte package dep fixes

sites/next.skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx
=> docs: fix typo in installation page

packages/skeleton-react/src/lib/components/Switch/Switch.tsx, packages/skeleton-svelte/src/lib/components/Switch/Switch.svelte, sites/next.skeleton.dev/src/content/docs/components/switch/meta.mdx, sites/next.skeleton.dev/src/examples/components/switch/Example.svelte
Closes #2704
Resolved a few minor issues for the Switch component and documentation.
=> Next: Switch component QA feedback patch

.github/workflows/release-next.yml, LICENSE, sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte
Merge for Release June 4, 2024
=> Merge for Release June 4, 2024

packages/skeleton-react/src/lib/components/AppBar/AppBar.tsx, packages/skeleton-react/src/lib/components/AppBar/schema.json, packages/skeleton-react/src/lib/components/AppBar/types.ts, packages/skeleton-react/src/lib/index.ts, packages/skeleton-react/src/routes/components/app-bars.tsx, sites/next.skeleton.dev/src/content/docs/components/app-bar/react.mdx, sites/next.skeleton.dev/src/examples/components/app-bars/Example.tsx, sites/next.skeleton.dev/src/examples/components/app-bars/ExampleResponsive.tsx, sites/next.skeleton.dev/src/examples/components/app-bars/ExampleToolbar.tsx
Closes #2712
Note: I noticed we have "use client" on top of the component definition, I am not sure if this is what caused the issue in next.js but removing it still works so I removed it.
=> next appbar v3 conventions

.changeset/nasty-chefs-build.md, packages/skeleton-react/src/App.tsx, packages/skeleton-react/src/lib/components/ProgressRing/ProgressRing.test.tsx, packages/skeleton-react/src/lib/components/ProgressRing/ProgressRing.tsx, packages/skeleton-react/src/lib/components/ProgressRing/schema.json, packages/skeleton-react/src/lib/components/ProgressRing/types.ts, packages/skeleton-react/src/lib/index.ts, packages/skeleton-react/src/lib/schemas.ts, packages/skeleton-react/src/routes/components/progress-rings.tsx, packages/skeleton-svelte/src/lib/components/Progress/Progress.svelte, packages/skeleton-svelte/src/lib/components/Progress/types.ts, packages/skeleton-svelte/src/lib/components/ProgressRing/ProgressRing.svelte, packages/skeleton-svelte/src/lib/components/ProgressRing/types.ts, packages/skeleton-svelte/src/lib/index.ts, packages/skeleton-svelte/src/routes/+layout.svelte, packages/skeleton-svelte/src/routes/components/progress-rings/+page.svelte, sites/next.skeleton.dev/src/content/docs/components/accordion/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/app-bar/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/avatar/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/progress-ring/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/progress-ring/react.mdx, sites/next.skeleton.dev/src/content/docs/components/progress-ring/svelte.mdx, sites/next.skeleton.dev/src/content/docs/components/progress/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/tabs/meta.mdx, sites/next.skeleton.dev/src/examples/components/progress-rings/Example.svelte, sites/next.skeleton.dev/src/examples/components/progress-rings/Example.tsx, sites/next.skeleton.dev/src/examples/components/progress-rings/ExampleIcons.svelte, sites/next.skeleton.dev/src/examples/components/progress-rings/ExampleIcons.tsx, sites/next.skeleton.dev/src/examples/components/progress-rings/ExampleIndeterminate.svelte, sites/next.skeleton.dev/src/examples/components/progress-rings/ExampleIndeterminate.tsx
Closes #2391
Implements the `<ProgressRing>` component for Svelte and React, as well as all required documentation.
=> Next: Add the ProgressRing component

.npmrc, package.json, sites/skeleton.dev/.npmrc
=> chore: fix vercel CI

.npmrc, package.json, sites/skeleton.dev/.npmrc
=> chore: fix vercel CI (#2726)

.changeset/chatty-ties-sell.md, .changeset/clean-ducks-mix.md, packages/skeleton/src/lib/components/AppRail/AppRailAnchor.svelte, packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte, packages/skeleton/src/lib/components/InputChip/InputChip.svelte, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
Merge for release July 16, 2024
=> Merge for release July 16, 2024

packages/skeleton-react/src/lib/components/Progress/Progress.tsx, packages/skeleton-react/src/lib/components/Progress/types.ts, packages/skeleton-react/src/lib/components/ProgressRing/ProgressRing.tsx, packages/skeleton-react/src/lib/components/ProgressRing/types.ts, packages/skeleton-react/src/lib/components/Switch/Switch.tsx, packages/skeleton-react/src/lib/components/Switch/types.ts, packages/skeleton-react/src/routes/components/progress.tsx, packages/skeleton-svelte/src/lib/components/Progress/Progress.svelte, packages/skeleton-svelte/src/lib/components/Progress/types.ts, packages/skeleton-svelte/src/lib/components/ProgressRing/ProgressRing.svelte, packages/skeleton-svelte/src/lib/components/ProgressRing/types.ts, packages/skeleton-svelte/src/lib/components/Switch/Switch.svelte, packages/skeleton-svelte/src/lib/components/Switch/types.ts, packages/skeleton-svelte/src/routes/components/progress/+page.svelte
I've synced the API between svelte and react.
Also the examples had a non-working example for changing the background (it used meterClasses instead of meterBg, the default of meterBg takes precedent).
=> refactor: consistent progress API

packages/skeleton-svelte/package.json, pnpm-lock.yaml, sites/next.skeleton.dev/package.json
Closes #2782
Resolve Astro doc site project dependency error.
=> Astro dependency updates

sites/skeleton.dev/src/lib/components/DocsFooter/DocsFooter.svelte, sites/skeleton.dev/src/lib/modals/examples/ModalExampleForm.svelte, sites/skeleton.dev/src/routes/(inner)/elements/scroll-containers/+page.svelte, sites/skeleton.dev/src/routes/home-partials/HomeHeroComponents.svelte
Merge for release August 13, 2024
=> Merge for release August 13, 2024

pnpm-workspace.yaml
Moves duplicate versions into single variable, makes upgrading dependencies much easier without needing find and replace or anything like that.
=> Abstracted duplicate dep versions into variable

sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte
Merge for release August 27, 2024
=> Merge for release August 27, 2024

sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
Closes #2855
updated layouts link to point to the correct page
{description}
=> Updated layouts link to correct link

sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
Merge for release Sept 24, 2024
=> Merge for release Sept 24, 2024

sites/next.skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx
Closes #2894
Updates the following onboarding guides:
=> NEXT Onboarding Revised

.changeset/plenty-tables-grow.md, packages/skeleton/package.json
Closes #2901
Update peer dependencies to support Svelte 5.
=> Update v2 peer dependency for Svelte 5

.changeset/plenty-tables-grow.md, packages/skeleton/package.json
Merge for release October 24, 2024
=> Merge for release October 24, 2024

sites/skeleton.dev/src/routes/(inner)/docs/ssd/ClientSSD.svelte
Closes #2847
Fix minors issues in the datatable docs
=> Fix path and broken url

sites/next.skeleton.dev/src/components/docs/ThemeList.astro, sites/next.skeleton.dev/src/content/docs/design/themes.mdx
Add missing themes aswell as make them copy the theme on click
=> Added theme preview cards that copy paste

.changeset/clean-fans-pretend.md, packages/skeleton-react/src/lib/components/AppBar/AppBar.tsx, packages/skeleton-react/src/lib/components/Pagination/Pagination.tsx, packages/skeleton-react/src/lib/components/Progress/Progress.tsx, packages/skeleton-react/src/lib/components/ProgressRing/ProgressRing.tsx, packages/skeleton-react/src/lib/components/Rating/Rating.tsx, packages/skeleton-react/src/lib/components/Slider/Slider.tsx
Closes #2926
Ensure consistent usage of Use Client directive in each React component.
=> NEXT Ensure consistent usage of Use Client directive in React components

.changeset/fuzzy-birds-rush.md, packages/skeleton-svelte/src/lib/components/Toast/ToastProvider.svelte, packages/skeleton-svelte/src/lib/components/Toast/types.ts, packages/skeleton-svelte/src/lib/index.ts, packages/skeleton-svelte/src/routes/+layout.svelte, packages/skeleton-svelte/src/routes/components/toast/+page.svelte, pnpm-lock.yaml, sites/next.skeleton.dev/package.json, sites/next.skeleton.dev/src/content/docs/integrations/toasts/meta.mdx, sites/next.skeleton.dev/src/content/docs/integrations/toasts/react.mdx, sites/next.skeleton.dev/src/content/docs/integrations/toasts/svelte.mdx, sites/next.skeleton.dev/src/examples/integrations/toasts/Example.svelte, sites/next.skeleton.dev/src/examples/integrations/toasts/Example.tsx, sites/next.skeleton.dev/src/examples/integrations/toasts/ExamplePageContent.svelte, sites/next.skeleton.dev/src/examples/integrations/toasts/ExampleProvider.svelte
Closes #2884
Implements the following:
> NOTE: the Svelte solution will be temporary until either Zag or a third party library update to provide a better solution.
=> NEXT Toast Integration Guide and Svelte Component

pnpm-lock.yaml, sites/next.skeleton.dev/package.json, sites/next.skeleton.dev/tailwind.config.js
=> Fix: Build error on Vercel

.changeset/chilled-avocados-pull.md, .changeset/olive-coats-brake.md, packages/skeleton-react/src/lib/components/Pagination/Pagination.tsx, packages/skeleton-react/src/routes/components/pagination.tsx, packages/skeleton-svelte/src/lib/components/Pagination/Pagination.svelte, packages/skeleton-svelte/src/lib/components/Pagination/types.ts, packages/skeleton-svelte/src/routes/components/pagination/+page.svelte, sites/next.skeleton.dev/src/content/blog/test.md, sites/next.skeleton.dev/src/examples/components/pagination/Example.svelte, sites/next.skeleton.dev/src/examples/components/pagination/Example.tsx, sites/next.skeleton.dev/src/layouts/LayoutRoot.astro
Closes #2933
Closes #2939
Addresses the following issues and updates doc examples accordingly:
=> NEXT: Pagination component improvements

.changeset/silver-balloons-impress.md, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte
=> Fixed `bind:open` not working after using `onOpenChange`

sites/next.skeleton.dev/src/components/docs/TableCookbook.astro, sites/next.skeleton.dev/src/content/config.ts, sites/next.skeleton.dev/src/content/docs/resources/cookbook.mdx, sites/next.skeleton.dev/src/content/docs/resources/cookbook/alerts.mdx, sites/next.skeleton.dev/src/content/docs/resources/cookbook/breadcrumbs.mdx, sites/next.skeleton.dev/src/content/docs/resources/cookbook/image-layouts.mdx, sites/next.skeleton.dev/src/content/docs/resources/cookbook/logo-clouds.mdx, sites/next.skeleton.dev/src/examples/resources/cookbook/alerts/Example.astro, sites/next.skeleton.dev/src/examples/resources/cookbook/alerts/ExampleColors.astro, sites/next.skeleton.dev/src/examples/resources/cookbook/breadcrumbs/Example.astro, sites/next.skeleton.dev/src/examples/resources/cookbook/breadcrumbs/ExampleIcons.astro
Closes #2979
- Improves the display and navigation of the Cookbook section.
- Cosmetic improvements to some recipes
- More examples provided for existing recipes
=> NEXT Improve Cookbook docs interface

.changeset/nasty-snails-hug.md, packages/skeleton-react/src/lib/components/Navigation/Navigation.test.tsx, packages/skeleton-react/src/lib/components/Navigation/Navigation.tsx, packages/skeleton-react/src/lib/index.ts, packages/skeleton-react/src/routes/components/navigation.tsx, sites/next.skeleton.dev/src/examples/components/navigation/Example.tsx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleBar.tsx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleExpanded.tsx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleTiles.tsx
Closes #2958
Renamed React's Nav to Navigation and adjust its usages.
=> Renamed Nav to Navigation

sites/skeleton.dev/src/routes/(inner)/components/tree-views/+page.svelte
Closes #2862
Nothing major here. Fixing variable names to be in sync 
=> Fix variable name

.changeset/shaggy-pants-repair.md, sites/skeleton.dev/src/routes/(inner)/components/conic-gradients/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/tree-views/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/style-guide/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/+page.svelte
Merge for release December 3, 2024
=> Merge for release December 3, 2024

.changeset/cuddly-dingos-sell.md, .changeset/honest-bears-learn.md, .changeset/nasty-snails-hug.md, .changeset/tame-crews-poke.md
Closes #3013
Changeset improvements
=> NEXT Changeset improvements

.changeset/clever-terms-train.md, packages/skeleton-react/package.json
Closes #3036
Update peer dependencies to support React 19
=> Chore: Update peer dependencies to support React 19

.changeset/tricky-snakes-begin.md, packages/skeleton-react/src/lib/components/Rating/Rating.tsx, packages/skeleton-react/src/lib/components/Slider/Slider.tsx, packages/skeleton-react/src/lib/components/Slider/types.ts, packages/skeleton-react/src/lib/components/Switch/Switch.tsx, packages/skeleton-svelte/src/lib/components/Rating/Rating.svelte, packages/skeleton-svelte/src/lib/components/Slider/Slider.svelte, packages/skeleton-svelte/src/lib/components/Slider/types.ts, packages/skeleton-svelte/src/lib/components/Switch/Switch.svelte, packages/skeleton-svelte/src/routes/+layout.svelte
Closes #3030
- Improves focus state for the Switch component
- Improves focus state for the Slider component in iOS
- Minor style improvement to the Ratings text label
=> NEXT Improve component focus states

README.md, packages/create-skeleton-app/README.md, packages/create-skeleton-app/templates/skeleton-template-appshell/src/routes/+layout.svelte
Closes #2671 
Update README assets and fix minor issues
=> Update README assets

pnpm-lock.yaml, pnpm-workspace.yaml
Closes #3047
Update Zag deps to 0.78.3 to resolve upstream FileUpload component bug.
=> NEXT Update Zag deps to 0.78.3

packages/skeleton-react/src/lib/components/Pagination/types.ts, packages/skeleton-svelte/src/lib/components/Modal/types.ts, packages/skeleton-svelte/src/lib/components/Pagination/types.ts, packages/skeleton-svelte/src/lib/components/Popover/types.ts, packages/skeleton-svelte/src/lib/components/Tooltip/types.ts
Closes #3058
Fix props missing descriptions
=> Fix for Popover, Modal, Tooltip and Combobox.

.changeset/seven-avocados-clean.md, packages/skeleton/src/lib/utilities/Popup/popup.ts, packages/skeleton/src/lib/utilities/Toast/Toast.test.ts
v2 Merge for Release - December 18, 2024
=> v2 Merge for Release - December 18, 2024

sites/next.skeleton.dev/src/content/docs/components/file-upload/react.mdx, sites/next.skeleton.dev/src/content/docs/components/file-upload/svelte.mdx
Closes #3081
Not much to describe here
=> Update docs typo

.changeset/clever-shirts-brake.md, .changeset/violet-buckets-switch.md, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-module.test.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-module.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-svelte.test.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-svelte.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-tailwind-config.test.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-tailwind-config.ts, pnpm-lock.yaml
=> Feature: CLI Improvements 2

.changeset/nice-panthers-exercise.md, .changeset/sweet-ants-march.md, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/index.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-svelte.ts
=> Skeleton CLI Improvements

.changeset/red-tables-approve.md, .changeset/sour-parrots-try.md, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-module.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-svelte.ts
Bugfix/prevent checking inherited properties.
=> Bugfix/prevent checking inherited properties.

.changeset/pretty-pears-complain.md, packages/skeleton-cli/src/commands/migrate/index.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/index.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-module.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-svelte.ts
=> Chore (migrate/skeleton-3): Simpler method of preserving quotes in Svelte template.

packages/skeleton-cli/package.json, packages/skeleton-svelte/package.json, pnpm-lock.yaml, pnpm-workspace.yaml, sites/next.skeleton.dev/package.json, sites/themes.skeleton.dev/package.json
Closes #3112
Updating the following packages to a newer Svelte version:
- `skeleton-svelte`
- `skeleton-cli`
- `next.skeleton.dev`
- `themes.skeleton.dev`
=> Chore: Update Svelte deps

.changeset/calm-moles-move.md, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-module.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-svelte.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/utility/export-mappings.ts, packages/skeleton-cli/test/migrate/skeleton-3/fixtures/module/keep-non-skeleton-identifiers, packages/skeleton-cli/test/migrate/skeleton-3/fixtures/module/keep-non-skeleton-imports, packages/skeleton-cli/test/migrate/skeleton-3/fixtures/svelte/keep-non-skeleton-components, packages/skeleton-cli/test/migrate/skeleton-3/fixtures/svelte/rename-components, packages/skeleton-cli/test/migrate/skeleton-3/results/module/keep-non-skeleton-identifiers, packages/skeleton-cli/test/migrate/skeleton-3/results/module/keep-non-skeleton-imports, packages/skeleton-cli/test/migrate/skeleton-3/results/svelte/keep-non-skeleton-components, packages/skeleton-cli/test/migrate/skeleton-3/results/svelte/rename-components
=> Bugfix (migrate/skeleton-3): Perserve non-skeleton imports and identifiers.

sites/next.skeleton.dev/src/components/docs/FigmaBuyNow.astro, sites/next.skeleton.dev/src/content/docs/guides/figma.mdx, sites/next.skeleton.dev/src/content/docs/guides/figma/chapter-1.mdx, sites/next.skeleton.dev/src/content/docs/guides/figma/chapter-2.mdx, sites/next.skeleton.dev/src/content/docs/guides/figma/chapter-3.mdx, sites/next.skeleton.dev/src/pages/figma/index.astro
Closes #3152
Addressing a few issues related to the recent design refresh and ensuring consistency.
=> Figma Docs Cleanup

sites/next.skeleton.dev/src/layouts/LayoutDoc.astro, sites/next.skeleton.dev/src/styles/app.css
Closes nothing
Porting of Carbon ads over from v2 docs
=> Port carbon ads over from v2

.changeset/khaki-ears-rhyme.md, packages/create-skeleton-app/src/creator.js
=> Bugfix: Pin tailwind versions to prevent newer (major) versions of tailwind.

.changeset/khaki-ears-rhyme.md, .changeset/polite-lions-camp.md, .changeset/slow-dancers-stare.md, packages/create-skeleton-app/src/creator.js, packages/plugin/src/styles/components/forms.css, packages/skeleton/src/lib/utilities/Popup/popup.ts, sites/skeleton.dev/src/routes/(inner)/actions/filters/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/transitions/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/alerts/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/table-of-contents/+page.svelte
Merge for release January 25, 2025
=> Merge for release January 25, 2025

.github/ISSUE_TEMPLATE/bug_report.yml
Closes #2691 
Add `Environment Information` option to bug report template
=> Add environment info to issue template

.changeset/brave-numbers-glow.md, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/types.ts, sites/next.skeleton.dev/src/examples/components/popover/ExampleTooltip.svelte
Closes #3178 
Implement `arrow` for Tooltip
=> Tooltip arrow

sites/next.skeleton.dev/src/pages/docs/[...slug]/index.astro
Closes #3190 
Just trying to set metadata properly for component pages
=> Pass meta from file if available

sites/next.skeleton.dev/src/components/docs/FigmaBuyNow.astro
=> Fix typo figma page

.changeset/eight-pants-appear.md, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte
Closes nothing
Follow up [Hugo's comment](https://github.com/skeletonlabs/skeleton/pull/3223#issuecomment-2662622165)
=> Clean up trigger render 

.changeset/calm-crabs-lay.md, packages/skeleton-react/src/lib/components/Navigation/Navigation.tsx, packages/skeleton-svelte/src/lib/components/Navigation/NavTile.svelte
Closes #3227 
See #3227 
I verified this change manually using this patch:
https://gist.github.com/SIMULATAN/4f7afeb33a2874e5dd3de4b58b4cffe5
=> NEXT: Navigation - manual selection handling

package.json, pnpm-lock.yaml
See: https://github.com/changesets/changesets/commit/b9df59627623bcf211ddbdab4df7cc07028d4998
=> bugfix: Update changeset to fix `prettier` in config validation failing

.changeset/chilly-pillows-smash.md, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte, packages/skeleton-svelte/src/lib/components/Modal/types.ts, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Popover/types.ts, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/types.ts
Closes #3234
Aria-label for triggers
=> Add aria-label for triggers

sites/next.skeleton.dev/src/content/docs/design/colors.mdx, sites/next.skeleton.dev/src/content/docs/design/presets.mdx, sites/next.skeleton.dev/src/content/docs/design/spacing.mdx, sites/next.skeleton.dev/src/content/docs/design/themes.mdx, sites/next.skeleton.dev/src/content/docs/design/typography.mdx, sites/next.skeleton.dev/src/content/docs/get-started/core-api.mdx, sites/next.skeleton.dev/src/content/docs/integrations/popover/meta.mdx, sites/next.skeleton.dev/src/content/docs/tailwind/badges.mdx, sites/next.skeleton.dev/src/content/docs/tailwind/buttons.mdx, sites/next.skeleton.dev/src/content/docs/tailwind/cards.mdx, sites/next.skeleton.dev/src/content/docs/tailwind/chips.mdx, sites/next.skeleton.dev/src/content/docs/tailwind/dividers.mdx, sites/next.skeleton.dev/src/content/docs/tailwind/forms.mdx, sites/next.skeleton.dev/src/content/docs/tailwind/placeholders.mdx, sites/next.skeleton.dev/src/content/docs/tailwind/tables.mdx
Closes #3246
Resolve broken source code links for Tailwind features
=> Docs: Resolve broken source code links for Tailwind features

packages/skeleton/CHANGELOG.md
We had some release issues, I believe changeset accidentially nuked some of our changesets, this PR adds those back.
=> chore: fix broken changelog

packages/skeleton-cli/CHANGELOG.md, sites/next.skeleton.dev/src/content/docs/get-started/installation/astro.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/vite-react.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/vite-svelte.mdx
Closes #3252
Improves the onboarding documentation to resolve issues and provide more specific guidance.
=> Onboardind instruction improvement

sites/next.skeleton.dev/src/content/docs/get-started/installation/vite-react.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/vite-svelte.mdx
Closes #3266
Resolves a couple small issues with the Vite onboarding guides
=> Vite TW4 doc fixes

sites/next.skeleton.dev/src/components/docs/Drawer.astro, sites/next.skeleton.dev/src/components/docs/Lightswitch.astro, sites/next.skeleton.dev/src/components/docs/ThemeSwitch.astro
Fixed that all event handlers are reattacheed after a client side navigation event
=> Docs: Fix stale event handlers

sites/next.skeleton.dev/src/content/docs/design/themes.mdx
Closes #3277
Fixes a minor typo in the theme register docs.
=> Theme register doc fix

.changeset/every-moles-help.md, packages/skeleton/src/utilities/form-groups.css
Closes #3282
Change justify-contents to justify-content in input group classes
=> Change justify-contents to justify-content in input group classes

sites/next.skeleton.dev/src/content/docs/design/typography.mdx, sites/next.skeleton.dev/src/examples/design/typography/Semantic.svelte
Closes #3273
Reimplements semantic typography styles following the latest Skeleton Preset and Tailwind v4 standards.
=> Implement Semantic Typography styles for Tailwind v4

packages/skeleton-react/CHANGELOG.md, packages/skeleton-svelte/CHANGELOG.md, packages/skeleton/CHANGELOG.md, sites/next.skeleton.dev/src/components/homepage/HomeCompGrid.svelte, sites/next.skeleton.dev/src/components/homepage/HomeDesignSystem.svelte, sites/next.skeleton.dev/src/components/homepage/HomeEvenMore.astro
Just updating examples and fixing some typos
=> Fix typo and remove switch binds

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/docs_issue.yml, .github/ISSUE_TEMPLATE/feature_request.yml, sites/skeleton.dev/src/routes/(inner)/docs/get-started/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte
Merge or v2 release - March 3, 2025
=> Merge or v2 release - March 3, 2025

sites/next.skeleton.dev/src/components/homepage/HomePlayground.astro
Closes #3096
Homepage frameworks updated
=> Homepage frameworks updated

.changeset/spicy-crabs-decide.md, packages/skeleton-react/src/components/TagsInput/TagsInput.tsx, packages/skeleton-react/src/components/TagsInput/types.ts, packages/skeleton-svelte/src/components/TagsInput/TagsInput.svelte, packages/skeleton-svelte/src/components/TagsInput/types.ts
Fixes the input tags chip edit not being styled and overflowing on smaller screens
=> bugfix: tags input edit regression

sites/next.skeleton.dev/src/content/docs/resources/contribute/documentation.mdx
=> Add generic code slot example

.changeset/eleven-bees-try.md, packages/skeleton-svelte/src/components/Combobox/Combobox.svelte
=> bugfix: prevent internal overwrite of `onInputValueChange` in `ComboBox`

sites/next.skeleton.dev/src/content/docs/get-started/core-api.mdx
Fixing [this](https://github.com/skeletonlabs/skeleton/issues/3300#issuecomment-2702911432)
=> Use JS escape string

sites/next.skeleton.dev/src/examples/components/progress/ExampleCustomAnimation.svelte, sites/next.skeleton.dev/src/examples/components/progress/ExampleCustomAnimation.tsx
Closes https://github.com/skeletonlabs/skeleton/issues/2827
Fixes the wacky progress animation that I originally implemented wrote. It should now look proper.
=> bugfix/docs: fix progress custom animation

sites/next.skeleton.dev/src/content/docs/integrations/popover/react.mdx, sites/next.skeleton.dev/src/content/docs/integrations/popover/svelte.mdx
Closes #3334 
Add cookbook link
=> Replace with cookbook link

.changeset/twelve-corners-grab.md, packages/skeleton-react/src/components/Avatar/Avatar.test.tsx, packages/skeleton-react/src/components/Avatar/Avatar.tsx, packages/skeleton-react/src/components/Avatar/types.ts, packages/skeleton-svelte/src/components/Avatar/Avatar.svelte, packages/skeleton-svelte/src/components/Avatar/Avatar.test.ts, packages/skeleton-svelte/src/components/Avatar/types.ts, sites/next.skeleton.dev/src/content/docs/components/avatar/react.mdx, sites/next.skeleton.dev/src/content/docs/components/avatar/svelte.mdx, sites/next.skeleton.dev/src/content/docs/guides/cookbook/svg-filters.mdx, sites/next.skeleton.dev/src/examples/components/avatars/ExampleFilter.svelte, sites/next.skeleton.dev/src/examples/components/avatars/ExampleFilter.tsx, sites/next.skeleton.dev/src/examples/components/avatars/ExampleStyle.svelte, sites/next.skeleton.dev/src/examples/components/avatars/ExampleStyle.tsx
Closes #3337
- Moves the position of the Avatar `style` attribute to the parent `<figure>` tag
- Removes the redundant `filter` prop
- Updates the docs to showcase SVG Filter usage
- Updates the docs to showcase `style` attribute usage
=> Avatar improvements

sites/next.skeleton.dev/src/components/docs/HeaderSponsors.tsx, sites/next.skeleton.dev/src/components/docs/Navigation.astro, sites/next.skeleton.dev/src/components/homepage/HomeDesignSystem.svelte, sites/next.skeleton.dev/src/components/homepage/HomeEvenMore.astro, sites/next.skeleton.dev/src/components/homepage/HomeFrameworkComps.svelte, sites/next.skeleton.dev/src/components/homepage/HomeHero.astro, sites/next.skeleton.dev/src/components/homepage/HomePlayground.astro
Closes #3346
Improves a number of small doc issues, mostly focusing on text and UI on the hompepage.
=> Homepage style and text fixes

.changeset/poor-dolls-arrive.md, packages/skeleton-svelte/src/components/Combobox/Combobox.svelte, packages/skeleton-svelte/src/components/Combobox/types.ts, sites/next.skeleton.dev/src/examples/components/popover/ExampleCombobox.svelte
Closes #3341 
Enable user to have custom template for combobox options
=> Combobox option template

.gitignore, packages/plugin/src/styles/components/forms.css, sites/skeleton.dev/src/app.html, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/steppers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/+page.svelte, sites/skeleton.dev/src/routes/+page.svelte
Closes #3353
Implements the last few changes to the v2 documentation before we archive the v2.0 branch.
> [!WARNING]  
> Make sure these changes are merged all the way down to `master` before the branch changes begin and v2 is archived!
=> v2 Docs - Prep for Archive

.gitignore, sites/skeleton.dev/src/app.html, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/steppers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/+page.svelte, sites/skeleton.dev/src/routes/+page.svelte
Merge for release March 11, 2025
=> Merge for release March 11, 2025

sites/skeleton.dev/src/components/docs/HeaderSponsors.tsx, sites/skeleton.dev/src/components/homepage/HomeCompGrid.svelte, sites/skeleton.dev/src/content/docs/get-started/installation/astro.mdx, sites/skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/skeleton.dev/src/content/docs/get-started/installation/other.mdx, sites/skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx, sites/skeleton.dev/src/content/docs/get-started/installation/vite-react.mdx, sites/skeleton.dev/src/content/docs/get-started/installation/vite-svelte.mdx, sites/skeleton.dev/src/content/docs/resources/contribute/get-started.mdx
Closes #3370
Resolves a small handful of issues with the launch version of the docs.
=> Post launch doc fixes

sites/skeleton.dev/src/components/homepage/HomeCompGrid.svelte
There were periods after some headers
{description}
=> docs/Update HomeCompGrid.svelte - Fixed typos

.github/workflows/build-publish.yml, .github/workflows/code-quality.yml
experimenting with github stuff, ignore this
=> chore: add `main` to code quality to allow github to discover status checks

playgrounds/skeleton-svelte/src/routes/+layout.svelte
=> Update checked state for svelte playground mode switch

sites/skeleton.dev/src/examples/guides/cookbook/dialog/Example.astro
Closes #3380
Adds positioning classes to center the native dialog.
=> docs: fix cookbook native dialog not centering

sites/skeleton.dev/src/examples/design/typography/TypeScale.svelte
=> Fix input range reactivity

.changeset/tasty-ducks-kick.md, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/index.ts
Fixes an issue where the glob matcher wasn't working well.
=> fix: skeleton cli source file glob

.changeset/yellow-turkeys-divide.md, packages/skeleton/src/utilities/typography.css, playgrounds/skeleton-core/src/pages/design/typography.astro, sites/skeleton.dev/src/content/docs/design/typography.mdx, sites/skeleton.dev/src/examples/design/typography/Mark.astro
Closes https://github.com/skeletonlabs/skeleton/issues/3407
Add `mark` utility.
=> feat: `mark` utility

.changeset/hungry-yaks-knock.md, packages/skeleton/src/utilities/form-groups.css
Closes #3439
Adjust the input/select to better match their individual counterparts.
=> Resolve Input Group discrepencies

sites/skeleton.dev/src/pages/figma/index.astro
We got multiple times asked if there is a preview for the Figma Kit.
Add Figma UI Kit Preview
=> Add Figma UI Kit preview section

packages/necroparser/package.json, packages/skeleton-react/package.json, packages/skeleton-svelte/package.json, packages/skeleton/package.json, playgrounds/skeleton-svelte/package.json, pnpm-lock.yaml, sites/themes.skeleton.dev/package.json
=> update vite dep

sites/skeleton.dev/src/content/docs/components/toast/react.mdx, sites/skeleton.dev/src/content/docs/components/toast/svelte.mdx, sites/skeleton.dev/src/examples/components/toast/ExampleReuseLayout.svelte, sites/skeleton.dev/src/examples/components/toast/ExampleReuseLayout.tsx, sites/skeleton.dev/src/examples/components/toast/ExampleReusePage.svelte, sites/skeleton.dev/src/examples/components/toast/ExampleReusePage.tsx, sites/skeleton.dev/src/examples/components/toast/toaster-react.ts, sites/skeleton.dev/src/examples/components/toast/toaster-svelte.ts
Closes #3497
Provides more detailed information for setting up, configuring, and using the Toast component.
=> Update Toast component docs

sites/skeleton.dev/src/content/docs/guides/cookbook/light-switch.mdx, sites/skeleton.dev/src/content/docs/tailwind/dividers.mdx
=> Fix some typos in light-switch and dividers example

.changeset/calm-papayas-give.md, packages/skeleton-react/src/components/Pagination/Pagination.tsx, packages/skeleton-react/src/components/Segment/Segment.tsx, packages/skeleton-svelte/src/components/Pagination/Pagination.svelte, packages/skeleton-svelte/src/components/Segment/Segment.svelte
=> Segment/Pagination: move default border padding to padding prop

sites/skeleton.dev/src/content/docs/guides/cookbook/floating-ui-attachments.mdx, sites/skeleton.dev/src/content/docs/integrations/popover/svelte.mdx, sites/skeleton.dev/src/examples/guides/cookbook/floating-ui-attachments/ExampleAttachment.txt, sites/skeleton.dev/src/examples/guides/cookbook/floating-ui-attachments/ExamplePopover.txt, sites/skeleton.dev/src/examples/guides/cookbook/floating-ui-attachments/ExampleTooltip.txt
Closes #3598
Implements a baselines integration for Floating UI and the recently launched Svelte attachments feature.
=> Floating UI Svelte attachement cookbook guide

sites/skeleton.dev/src/styles/app.css
Fixes a regression from #3662 that forgot to switch the `@source`'s to `@import`.
=> docs: fix import paths

packages/skeleton-react/vite.config.ts, packages/skeleton-svelte/vite.config.ts
Fixes bug where tests were failing due to not being able to resolve the alias correctly.
=> chore: fix alias in tests

.changeset/violet-signs-dream.md, packages/skeleton-svelte/package.json
Closes #3739
Fix some inconsistencies
=> fix: package internals

packages/skeleton-react/src/components/accordion/modules/use-accordion.ts, packages/skeleton-react/src/components/avatar/modules/use-avatar.ts, packages/skeleton-react/src/components/progress-linear/modules/use-progress-linear.ts, packages/skeleton-react/src/components/rating-group/modules/use-rating-group.ts, packages/skeleton-react/src/components/switch/modules/use-switch.ts, packages/skeleton-react/src/components/tabs/modules/use-tabs.ts
=> chore: make props optional

packages/skeleton-common/src/classes/tabs.ts
improve tabs classes and remove redundant class
=> tabs: improve class orchistration

sites/skeleton.dev/src/layouts/LayoutDoc.astro
=> chore: fix branch config

sites/skeleton.dev/src/content/docs/guides/figma/chapter-1.mdx
Closes #3821 
Fixes the button to be inline by correctly using HTML in MDX
=> docs: fix figma button wrap

.github/instructions/monorepo.instructions.md, .github/instructions/packages/skeleton-common.instructions.md, .github/instructions/packages/skeleton-react.instructions.md, .github/instructions/packages/skeleton-svelte.instructions.md, .github/instructions/sites/skeleton-dev.instructions.md
Adds some LLM instructions in the .github folder for a faster development cycle for those who like to use LLM's.
=> chore: copilot instructions

packages/skeleton-common/src/classes/listbox.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> chore: bump

.changeset/odd-cooks-make.md, packages/skeleton-svelte/src/components/file-upload/index.ts
=> fix(file-upload): add missing export

.changeset/good-groups-look.md, packages/skeleton-react/src/components/listbox/anatomy/root.tsx, packages/skeleton-react/src/components/toast/anatomy/root.tsx, packages/skeleton-svelte/src/components/accordion/anatomy/root.svelte, packages/skeleton-svelte/src/components/avatar/anatomy/root.svelte, packages/skeleton-svelte/src/components/combobox/anatomy/root.svelte, packages/skeleton-svelte/src/components/date-picker/anatomy/root.svelte, packages/skeleton-svelte/src/components/dialog/anatomy/root.svelte, packages/skeleton-svelte/src/components/file-upload/anatomy/root.svelte, packages/skeleton-svelte/src/components/listbox/anatomy/root.svelte, packages/skeleton-svelte/src/components/pagination/anatomy/root.svelte, packages/skeleton-svelte/src/components/popover/anatomy/root.svelte, packages/skeleton-svelte/src/components/progress/anatomy/root.svelte, packages/skeleton-svelte/src/components/rating-group/anatomy/root.svelte, packages/skeleton-svelte/src/components/segmented-control/anatomy/root.svelte, packages/skeleton-svelte/src/components/slider/anatomy/root.svelte, packages/skeleton-svelte/src/components/switch/anatomy/root.svelte, packages/skeleton-svelte/src/components/tabs/anatomy/root.svelte, packages/skeleton-svelte/src/components/tags-input/anatomy/root.svelte, packages/skeleton-svelte/src/components/toast/anatomy/root.svelte, packages/skeleton-svelte/src/components/tooltip/anatomy/root.svelte, packages/skeleton-svelte/src/components/tree-view/anatomy/root.svelte, pnpm-lock.yaml, pnpm-workspace.yaml, sites/skeleton.dev/src/content/docs/design/presets.mdx
=> chore: update deps
