skeletonlabs/skeleton

src/routes/index.svelte
`npm init svelte@next my-app` has been changed to `npm create svelte@latest my-app`.
Reference: https://kit.svelte.dev/
=> docs: update create command

src/routes/components/drawers.svelte
I had an error in the previous docs.  This example is now fully copy pastable with a note about the breakpoint.  Also removed the Dividers component to shrink the code up a bit.
=> Pastable functional demo

src/lib/LightSwitch/LightSwitch.svelte, src/lib/Menu/Menu.svelte
I'm playing with Skeleton in a regular Svelte app and made these changes to get it to work for me, so I thought I might as well open a PR.
As suggested in #68, this replaces SvelteKit-specific options with regular lifecyle hooks. 
I've checked out the LightSwitch and Menu running the site locally from this branch, and they seem to work fine. However, I have almost zero experience with SvelteKit. I'm happy to put a bit more time into this, if you have any improvements or an easy way to test this properly, let me know! And if you want to just close it, that's fine too, of course.
=> Decouple Skeleton from SvelteKit

scripts/skel
More for contributors/testers - but makes it much simpler to setup a base Skeleton app for testing.
I know the end goal would be more along the lines of a plugin for svelte-add, but there is a lot of complexity involved in doing so as it uses a full on AST to properly insert it's changes rather than the naive string manipulation this script does.  But this definitely helps in the short term.
=> Shell script for quickly creating a Skeleton app

svelte.config.js
Looking at https://kit.svelte.dev/docs/configuration#package
Their docs are wrong - it needs to be nested under kit.package: and the '!**/build.*' exclude is nonsense as they never get sent to that function on either build or package.  Have changed this to a JS only implementation.
This closes #127
=> JS only version of test strip

svelte.config.js
Because @sveltejs/package is it's own package now, the config is not under the `kit` property anymore.  `pnpm i`, `pnpm package` and `pnpm test` all seem to work as before their change.  This fixes #156
=> Package config hoisted a level as it is it's own package now

package.json, src/lib/CodeBlock/CodeBlock.svelte, src/lib/CodeBlock/stores.ts, src/lib/Table/DataTable.svelte, src/lib/index.ts, src/routes/+layout.svelte, src/routes/utilities/codeblocks/+page.svelte
See the attached ticket for details. In short, this drops the Highlightjs dep from CodeBlock, reinstated CodeBlock, update docs. Highlight.js is now an optional progressive enchantment if you choose to add it.
=> Decoupled Highlight.js from CodeBlock component

src/lib/CodeBlock/CodeBlock.svelte
This PR is to address a bug that removes syntax highlighting when the content of a CodeBlock is altered, specifically in this case the Skeleton sites Theme Generator
This PR also corrects an issue with HTML when highlight.js is not installed, the HTML needs to be passed directly as text instead of HTML in the component
=> Code block syntaxhighlight bug

src/lib/Menu/Menu.svelte
See attached ticket for details. Provides a race condition when origin:auto is used but the element binding is not yet ready.
=> Menu setOrigin now occurs onMount

src/lib/GradientHeading/GradientHeading.svelte
As per https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-level the proper level will be inferred from the `tag` being h1-6 or explicitly defined by the end dev.  Just added an ignore for the warning so as to not be a false positive.
This fixes #183
=> Removed a11y warning on Gradient Header

src/lib/components/Radio/RadioItem.svelte
Please review the location of the attribute as I can see arguments for being on both the enclosing div as well as the input itself (it's on the container dev currently)
=> Added data-testid for radio item

src/routes/(inner)/components/listboxes/+page.svelte
Just fixed a few typos.
And normalized the use of text `Listbox` to `ListBox` in docs to avoid any confusion.
=> ListBox was Listbox at few places

src/routes/(inner)/components/app-shell/+page.svelte
Fixed a small issue in the AppShell documentation with unnecessary mentions of header
=> Removed unnecessary 'header' from AppShell Property descriptions

src/routes/(inner)/guides/frameworks/vite/+page.svelte
=> Changed App.html to index.html

src/docs/DocsAppBar/DocsAppBar.svelte
Was pointing to App Shell, now points to Accordion.
=> Update link to accordion as first component

src/routes/(inner)/components/file-buttons/+page.svelte
quick fix to make var name consistent across drop zone and button
=> make consistent with dropzone

src/routes/(inner)/components/accordions/+page.svelte
Just added an extra example to show no collapsing based on question in #support from Geoff.
=> Added extra example for Accordion

src/routes/(inner)/docs/contributions/documentation/+page.svelte
Mostly typo/grammar fixes and moved the intellisense sentence up to the top as it felt oddly out of place and context previously.
=> Documentation Guide updates

.gitignore
The leading slashes made it only work at the root level, rather than flow down into multiple projects
=> gitignore fixes for monorepo

.github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md
This should fix the problem with the `feature request` label not being automatically added to new issues when creating from the template.
=> chore: fix broken feature request label

src/routes/(inner)/utilities/modals/+page.svelte
stripped extraneous feature portion of url's
=> bug: Fix github links on Modal doc page

src/lib/components/SvgIcon/SvgIcon.svelte
For whenever we get this exported from the library proper, it'll have correct values for the docs
=> Changed default value to be h-5

tsconfig.json
As per https://kit.svelte.dev/docs/configuration#alias the alias setting in svelte config.kit.alias now sets things up in both Vite and Typescript for us.
=> Removed ts path config

src/lib/utilities/Toast/Toast.svelte, src/lib/utilities/Toast/stores.ts, src/lib/utilities/Toast/types.ts
- Adds types for the `toastStore`
- Fixes a bug with Toast actions
- Removed a lost `console.log` in the store as well
**Toast actions bug:** if you navigate [here](https://www.skeleton.dev/utilities/toasts) and press on the following buttons in this order, `Paragraph` then `Action`, you will notice that if you try to press the `Greeting` action, the alert won't fire. 
Additionally, if you close all the toasts and press `Action`, then `Paragraph`, followed by pressing the `Greeting` action, you'll see that the alert fires this time. But! When the alert closes, the `Paragraph` toasts closes instead of the `Action` toast!
- Link to an issue using the verbiage [Fixes #XX](https://docs.github.com/en/issues/tracking-your-work-with-i …
=> Fix: Added better types for Toast and fixed issue with actions

src/routes/(inner)/elements/tables/+page.svelte, src/routes/(inner)/guides/frameworks/sveltekit/+page.svelte, src/routes/(inner)/guides/frameworks/vite/+page.svelte, src/routes/(inner)/template/+page.svelte
Fixes to make svelte-check happy again.
Escaped <script> tag again
Fixed up complaints about @ts-exepect-error in commented out sections of the templates
NOTE: this increases our lint error count
=> Escapes back in. Fixed ts-expect in comments

src/routes/(inner)/utilities/menus/+page.svelte
A test unrelated to a change I made is currently failing. Specifically related to the Drawer utility.
Fixes: #648 
Update documentation for *Menus* to include an example of how to mirror styles of `<a>` tags within a menu to a `<button>`.
=> Docs: Add `option` class to Menus docs #648

src/routes/(inner)/components/app-rail/+page.svelte
- [ X ] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/skeletonlabs/skeleton/discussions) before submission.
- [ X ] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [ X] Did you update documentation related to your new feature or changes?
Solves #658 
[Fixes #658](https://github.com/skeletonlabs/skeleton/issues/658)
- …
=> #658 AppRail anchor link option is undocumented

src/docs/DocsAppBar/DocsAppBar.svelte
…Default is only applied when command keys are also pressed at the same time
This issue was mentioned in Discord. When opening the search bar, it wasn't possible to type "k" into the search field since the keydown function was preventing defaults of it.
I updated the keydown function to use `&&` instead of `||` and also changed `e.code === 'KeyK` to `e.key === 'k'`, since <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>k</kbd> is a shortcut in Firefox to open the web console, but this was prevented here. On the SvelteKit site <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>k</kbd> also doesn't open the search field: https://kit.svelte.dev/, so perhaps they are doing it this way as well?
I don't have Mac so I can't check if these changes also work on there, so I'll create it as a draft PR for now.
- …
=> Update keydown function that opens the search field

src/lib/utilities/Menu/menu.ts
…ad and remove node click event listener so that window click event listener takes care of click events
This would Close #685, where the menu wouldn't open on the first click after a page reload.
The problem was because `onToggleClick` was checking if the `elemMenu.style.display === 'none'` but this only gets set when the menu is closed, so when a click is made anywhere on the page but the menu button. I changed the if statement to fix this.
I also made another update and removed the node click event listener, since we already have a window click event listener, and having both of them was a bit confusing.
- Link to an issue using the verbiage [Fixes …
=> Fix bug where menu wouldn't open on the first click after a page reload

src/lib/utilities/DataTable/DataTable.ts
The `DataTable` sorting is broken when the data contains `BigInt` values. This is because `Array.sort` doesn't support returning `BigInt`'s, and errors with:
> Cannot convert a BigInt value to a number
A simple fix for this is to return -1, 0, or 1 from the sort function, which is what this PR implements.
<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#comparisons>
Note I didn't run any tests for this and simply made the change in Github.
=> Fix `DataTable` sorting with BigInts

src/lib/components/FileButton/FileButton.svelte
Fixes #700 
Changed type on the button element from FileButton to "button" to stop the default submit behaviour that would result in premature form submission.
=> bugfix - Changed type on the button element

src/lib/components/ProgressBar/ProgressBar.svelte, src/lib/components/ProgressBar/ProgressBar.test.ts
The ProgressBar can now have a minimum and maximum value - not necessarily starting at 0. The value can be set to a value between the minimum and maximum value. The progress bar will then be filled up to the percentage of the value between the minimum and maximum value.
- [ X] Did you update and run tests before submission using `npm run test`?
- [ X ] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [ X ] Did you update documentation related to your new feature or changes? <<< Happened automatically 🤯
This extends the progress bar with a new property `min` so that it does not have to start at 0 necessarily.
=> feat: Extends the ProgressBar to potentially be also used as a meter.

src/lib/components/Accordion/AccordionItem.svelte
- this is necessary to be able to react on the accordion toggling event
Discussion on [Discord](https://discord.com/channels/1003691521280856084/1054106126993604658) 
The change allows to react upon an AccordionItem / detail toggling.
=> Adds the on:toggle Event handler on AccordionItem

src/routes/(inner)/components/avatars/+page.svelte
On the Avatar documentation page (https://www.skeleton.dev/components/avatars), the rounded sizes were in this order: full, xl, 3xl, none. I found this counterintuitive, as it would make more sense to place them in descending order as follows: full, 3xl, xl, none. That is essentially all this pull request addresses.
=> Logistical Fix in Avatars

src/lib/utilities/Modal/Modal.svelte, src/routes/(inner)/utilities/modals/+page.svelte
Fixes #734. 
Added `overflow-auto` to the modal to make it scrollable.
=> Add overflow-auto to modals to make them scrollable

src/routes/(inner)/components/gradient-headings/+page.svelte
as described in
https://tailwindcss.com/docs/background-clip#cropping-to-text
N.A.
Just a small fix for Tailwind bg-clip-text directive - ran into this small issue where bg-clip doesn't exist and needs to be bg-clip-text. It's just a documentation change, so I didn't run npm run test.
=> changed bg-clip to bg-clip-text

src/docs/DocsAppBar/DocsAppBar.svelte
Added utility classes to make the Theme menu, that is accessible from the navbar theme button, responsive on mobile devices
Fixes #792
=> Fixed unresponsive Theme menu

scripts/generate-jss.js, src/lib/tailwind/intellisense.cjs, src/lib/tailwind/skeleton.cjs, src/routes/(inner)/guides/tailwind/+page.svelte
Decouples the intellisense plugin from the base skeleton plugin. Users will now have to import the intellisense by adding `require('@skeletonlabs/skeleton/tailwind/intellisense.cjs')` to the plugin array in `tailwind.config.cjs`.
Additionally, we've renamed the generated CSS-in-JS file to `intellisense-classes.cjs` to fix the annoying committing issue.
=> Feat: Separate intellisense into it's own plugin

src/docs/DocsShell/types.ts, src/routes/(inner)/components/accordions/+page.svelte, src/routes/(inner)/components/app-bar/+page.svelte, src/routes/(inner)/components/app-rail/+page.svelte, src/routes/(inner)/components/app-shell/+page.svelte, src/routes/(inner)/components/avatars/+page.svelte, src/routes/(inner)/components/conic-gradients/+page.svelte, src/routes/(inner)/components/file-buttons/+page.svelte, src/routes/(inner)/components/file-dropzone/+page.svelte, src/routes/(inner)/components/input-chips/+page.svelte, src/routes/(inner)/components/listboxes/+page.svelte, src/routes/(inner)/components/paginators/+page.svelte, src/routes/(inner)/components/progress-bars/+page.svelte, src/routes/(inner)/components/progress-radials/+page.svelte, src/routes/(inner)/components/radio-groups/+page.svelte, src/routes/(inner)/components/range-sliders/+page.svelte, src/routes/(inner)/components/slide-toggles/+page.svelte, src/routes/(inner)/components/steppers/+page.svelte, src/routes/(inner)/components/svg-icons/+page.svelte, src/routes/(inner)/components/table-of-contents/+page.svelte, src/routes/(inner)/components/tables/+page.svelte, src/routes/(inner)/components/tabs/+page.svelte
As part of the sync'ing of tsconfig.json with the latest SK lib project template - it introduced a warning on the //@ts-ignore's on the Sveld import lines, this turned out to be also hiding a type mismatch error on SveldObj - this fixes up both and still retains the new settings of tsconfig.json.
=> Removed TS-ignores and fixed SveldJson type

scripts/compile-css-to-js.cjs, src/lib/tailwind/core.cjs, src/lib/tailwind/skeleton.cjs, src/routes/(inner)/guides/tailwind/+page.svelte, tailwind.config.cjs
This is a rework on how we export our plugin. We'll now export a function that returns an array of plugins. The function will accept an optional config that will allow users to opt out of certain plugins. Users will not be able to opt out of the `core` plugin.
By default (when no config is passed), both the `core` and `intellisense` plugins will be returned. 
Users will be able to import the config as follows:
```ts
// tailwind.config.cjs
// ... other TW options
plugins: [
// other existing plugins above...
...require('@skeletonlabs/skeleton/tailwind/skeleton.cjs')(),
]
```
If users want to opt out of having intellisense, it will be done as such:
```ts
// tailwind.config.cjs
// ... other TW options
plugins: [
// other existing plugins above... …
```
=> Feat: Modular Tailwind plugin

package.json, scripts/post-build.js
There is also a shuffle of svelte into Deps from devDeps as svelte-package was continuously nagging me.
This should be working for all props and events that have /** @event */ JSDoc tags in the JSDoc block.  There is some potential to pretty up the Intellisense formatting of the events, but want to discuss first as it will affect docsite as well.
=> Props and Events descriptions for intellisense

scripts/generate-jss.js
Fixes #888
Type selectors were being removed from the generated CSS-in-JS, but their dark variants were not. This fixes that.
=> Fix: Remove dark variants from type selectors in Intellisense

src/lib/utilities/Toast/Toast.svelte, src/lib/utilities/Toast/Toats.test.ts
The Toast component renders max + 1 toasts, which contradicts the description of the max property.
Added test and fixed implementation.
=> fix max toasts.

src/routes/(inner)/elements/logo-clouds/+page.svelte
Small type fix in logo-clouds doc.
There's an extra </span> in the code sample causing a syntax error.
=> fix typo in logo-cloud example doc

src/lib/components/FileButton/FileButton.svelte
If you bind a variable to a FileButton component's `files` property, it won't actually update when a file is selected. This PR removes the explicit property from the file input and just passes `files` to the input like any other property through the `prunedRestProps`.
=> fix: FileButton `files` property binding

src/routes/+layout.svelte
We need to lazy load the analytics to prevent the errors we've seen in dev due to ad blockers:
```
GET http://localhost:5173/node_modules/.vite/deps/@vercel_analytics.js?v=73c2f3ed net::ERR_BLOCKED_BY_CLIENT
manifest.js:145 TypeError: Failed to fetch dynamically imported module: http://localhost:5173/.svelte-kit/generated/client/nodes/0.js
handleError @ manifest.js:145
handle_error @ client.js?v=73c2f3ed:1812
_hydrate @ client.js?v=73c2f3ed:1749
await in _hydrate (async)
start @ start.js:33
(anonymous) @ (index):7441
localhost/:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:5173/.svelte-kit/generated/client/nodes/0.js
start.js:39 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: …
```
=> Fix: Lazy load vercel analytics

src/docs/layouts/DocsThemer/DocsThemer.svelte, src/lib/utilities/Popup/popup.ts, src/lib/utilities/Popup/types.ts, src/routes/(inner)/utilities/popups/+page.svelte
=> Improve popup behavior

src/routes/(inner)/docs/styling/+page.svelte
Arbitrary was spelling incorrectly on the `docs/styling` page referencing Tailwind arbitrary variants.
=> Fixed spelling of Arbitrary

src/docs/layouts/DocsShell/partials/PanelProps.svelte, src/lib/components/Accordion/Accordion.svelte, src/lib/components/AppBar/AppBar.svelte, src/lib/components/AppRail/AppRailTile.svelte, src/lib/components/AppShell/AppShell.svelte, src/lib/components/FileDropzone/FileDropzone.svelte, src/lib/styles/tailwind.css, src/routes/(inner)/actions/clipboard/+page.svelte, src/routes/(inner)/actions/filters/+page.svelte, src/routes/(inner)/actions/focus-trap/+page.svelte, src/routes/(inner)/components/accordions/+page.svelte, src/routes/(inner)/components/app-bar/+page.svelte, src/routes/(inner)/components/app-rail/+page.svelte, src/routes/(inner)/components/app-shell/+page.svelte, src/routes/(inner)/components/avatars/+page.svelte, src/routes/(inner)/components/conic-gradients/+page.svelte, src/routes/(inner)/components/file-dropzone/+page.svelte
Contributing to:
- https://github.com/skeletonlabs/skeleton/issues/1049
Checklist
=> Svelte group 1 docs review

src/lib/components/AppShell/AppShell.svelte, src/routes/(inner)/redirect/[destination]/+page.ts
Workaround for hyphenated links in JSDocs
=> Feat/redirector for jsdoc links to hyphenated url's

src/routes/(inner)/components/app-rail/+page.svelte
=> Fix App Rail code example

src/routes/(inner)/docs/colors/+page.svelte, src/routes/(inner)/docs/generator/+page.svelte, src/routes/(inner)/docs/get-started/SectionInstall.svelte, src/routes/(inner)/docs/get-started/SectionStylesheets.svelte, src/routes/(inner)/docs/get-started/SectionThemes.svelte, src/routes/(inner)/docs/introduction/+page.svelte, src/routes/(inner)/docs/tokens/+page.svelte
Resolves part of https://github.com/skeletonlabs/skeleton/issues/1049
Docs Sections - Group 1
=> Docs Update: Docs Section 1

src/routes/(inner)/components/radio-groups/+page.svelte
Example of vertical layout of RadioGroup
An example of vertical orientation for RadioGroup
Used flex-col to flow vertically and a for each of a time period variable to populate it.
I assume I don't want to link and auto close?
=> docs/components/radio-groups/ vertical example #1089

src/docs/layouts/DocsThemer/DocsThemer.svelte, src/docs/layouts/DocsThemer/Swatch.svelte, src/docs/layouts/DocsThemer/colors.ts, src/docs/layouts/DocsThemer/types.ts, src/lib/types/tailwind.ts
Changes made:
- added a validity checker for hex values
- added a contrastReports list variable that calls the `getPassReport` function only when hex value is valid
- html now gets generated with this new list instead of using `{@const contrastReport = ...}` calculation
- added some types
- updated an import in `Swatch.svelte` which was pointing at the wrong type
- added missing `semanticNames` (`'error'` and `'surface'`) to the `tailwind.ts` file
This would Close #1111 
- Linked issues …
=> Update theme generator so no error occurs while typing in hex colors 

src/routes/home-partials/HomeSponsors.svelte
The size of images for sponsors were causing a "jerk" effect when trying to smooth scroll on the home page. Those images have been shrunken from 136kB -> 40kB (Brain & Bones) and 654kB -> 30kB (Luke).
=> Fix: Optimized sponsor images

src/lib/utilities/Popup/popup.ts, src/lib/utilities/Popup/types.ts, src/routes/(inner)/utilities/popups/+page.svelte
Adds a `focus` event to the options passed to `use:popup`. This allows us to trigger the menu when an element is either clicked or tabbed to, and close it when focus moves outside the menu.
In `focus-click`, we do the same, but add a listener to the `click` event on the trigger node, so when the node already has focus, it can still be toggled by clicking the button.
It might be worth adding a notice at the top of the page that this might not work unless you enable the "Press tab to highlight each option on a webpage" toggle in Safari.
=> Add `focus` event to `popup`

src/routes/(inner)/components/autocomplete/+page.svelte
Added the Keywords & metadata used in the example to the shown example documentation to explain why neapolitan comes up for vanilla.
=> Added the Keywords & metadata used in the example to the shown example documentation to explain why neapolitan comes up for vanilla.

src/lib/utilities/Toast/stores.ts, src/lib/utilities/Toast/types.ts
- Fixes #1197 
- Adds `timeoutId` to the `Toast` type
- Clears timeout for closed Toasts
- Adds conditional check before removing toasts from the `tStore`
I welcome any and all feedback! Just let me know if you noticed anything that seem "off". As well I attempted to add a test for this change, but was running into some issues with the Vitest mocked timers. If anyone has some experience with those I'd love to get some tests to double check this fix! Also I noticed the test file is misspelled (`Toats.test.ts`), but decided to keep this MR focused on fixing the base issue. I'd gladly open another PR to fix that if it's a concern.
=> Fix Dismissed Toast Timeouts Closing Other Toast

src/lib/components/Autocomplete/Autocomplete.test.ts
- [ x ] Did you update and run tests before submission using `npm run test`?
- [ x ] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributing)? If not, please amend the branch name using `branch -m new-branch-name`
Adds unit tests for `Autocomplete.svelte`, as discussed on [Discord](https://discord.com/channels/1003691521280856084/1003699523522142399/1088929365221457930).
There are tests for filtering with and without a blacklist or whitelist, ensuring the 'No Results Found.' message displays when no options match the search term.
I've also written a test to ensure that the `on:selection` event is triggered.
I've written the data as an array of `as const` with a `satisfied AutocompleteOption[]` at the end. This lets us have autocompletion and type safety, …
=> Add tests for `Autocomplete.svelte`

src/lib/utilities/Modal/Modal.svelte
Fixes #1240 
Before, the `backdrop` event was dispatched whenever an element inside the modal component was clicked.
Now, it only dispatches the event when the backdrop is clicked
=> bugfix: only dispatch `backdrop` event if backdrop clicked

src/lib/utilities/Popup/popup.ts
Fixes #1229
Adds an `onPopupClick` handler to close when an element which matches `closeQuery` or is a descendant of an element that matches `closeQuery`, as in `onWindowClick`.
I've moved the logic for closing based on `closeQuery` to its own function, `closeOnQueryClick` since the code is reused by both `onWindowClick` and `onPopupClick`.
=> bugfix: add `onPopupClick` listener to close when closeQuery matches

src/routes/(inner)/components/autocomplete/+page.svelte
Updated autocomplete documentation to include recommendations on how to style and display the component. Updated all the examples as well to match.
Adds information for styling the component.
1. Passing `class` attribute directly to the prop.
2. Wrapping the component in a `div` and applying the `class` the `div`.
3. Updated all examples to use the method of wrapping the component in a `div` with the `class` applied
=> Docs - Provide documentation on component styling.

src/lib/components/Avatar/Avatar.svelte
- Ran test but there was un-related error: `src/lib/components/RangeSlider/RangeSlider.test.ts > RangeSlider.svelte > Ticks enabled
AssertionError: expected null to be truthy`
Fix the SVG off-center text rendering for the Avatar component. Fixed by changing `dominant-baseline` HTML value to "central"
=> Fix off-center text rendering for avatar

src/lib/components/RangeSlider/RangeSlider.svelte, src/lib/components/SlideToggle/SlideToggle.svelte
This pull request addresses the issue that the `SlideToggle` and `RangeSlider` components' `name` props refer to `file input`, although neither of them has anything to do with files.
Fixes #1269
=> Update `name` descriptions

src/lib/components/ListBox/ListBoxItem.svelte, src/lib/components/Radio/RadioItem.svelte, src/lib/components/Tab/Tab.svelte
This gets rid of the SK warnings and seems to make sense in that the role and tab index were on the label as well as the actual active input.
=> Delete role + tabindex from non-interactive labels

src/lib/utilities/Popup/popup.ts
Fixes #1305
Fixes #1306 
`elemPopup.style.display` was being set to `hidden` instead of `none`
This causes an issue when using the autocomplete with popup, because its list items are buttons, and when it wasn't actually being set to `display:none` properly it was causing focus to be given to the button even though the popup wasn't visible to the users.
Updated `elemPopup.style.display` to `none` as `hidden` is a tailwind class name for `display:none`. 
Also updated so that `Tab` and `Escape` close the popup. To match the default functionality for tabbing in an input. 
@endigo9740 ~~If you think its better, I can resubmit this PR with tab only closing the popup is `node` is an instance of `HTMLInputElement` instead?~~ 
Actually after thinking …
=> Popups display not being correctly set on Close()

src/routes/(inner)/components/app-shell/+page.svelte
Adjusted the primary labels in the interactive examples to better represent the svelte fragments Added a section depicting the slot usage to make it more clear how to pass through page data
=> Adjusted AppShell example

src/docs/modals/examples/ModalExampleImage.svelte
Remove duplicate class `btn-icon` in `ModalExampleImage.svelte`.
=> Remove duplicate class in modal example.

src/lib/components/Tab/TabGroup.svelte
The PR fixes a wrong class name for hiding scrollbar in TabGroup component.
=> Fixed hide scrollbar in TabGroup

src/lib/styles/core.css
Before change
After change
Note: I've overwritten the behavior of CodeBlock to showcase the before and after - by default there is no overflow on the CodeBlock.
=> Apply same height to scrollbars as width

src/docs/layouts/DocsShell/DocsShell.svelte, src/docs/layouts/DocsShell/defaults.ts
To have more clarity `docSellDefaults` was renamed to `docShellDefaults`. The placement swap of the imports is due to import sorting. Can be reverted if not wanted.
I do prefer automatic import sorting on projects with multiple contributors to have consistent import orders.
=> rename docSell to docShell

package.json
Fixes #1359
Removed the top level `svelte` field from package.json
=> Removed svelte field from package.json

package-lock.json, package.json, src/lib/utilities/Drawer/Drawer.svelte, src/lib/utilities/LocalStorageStore/LocalStorageStore.ts
Fixes #1352
To determine the current runtime environment, I added [`esm-env`](https://github.com/benmccann/esm-env) based on the recommendation from SvelteKit's package documentation under ["Best Practices"](https://kit.svelte.dev/docs/packaging#best-practices).
=> Fixes `window undefined` during SSR

src/lib/actions/Filters/filter.test.ts
- TS2769: No overload matches this call
```
No overload matches this call.
Overload 1 of 2, '(component: Constructor<NoirLight__SvelteComponent_>, componentOptions?: SvelteComponentOptions<NoirLight__SvelteComponent_> | undefined, renderOptions?: Omit<...> | undefined): RenderResult<...>', gave the following error.
Argument of type 'typeof Noir__SvelteComponent_' is not assignable to parameter of type 'SvelteComponentOptions<NoirLight__SvelteComponent_> | undefined'.
Type 'typeof Noir__SvelteComponent_' is not assignable to type 'Record<string, never>'.
Index signature for type 'string' is missing in type 'typeof Noir__SvelteComponent_'.
Overload 2 of 2, '(component: Constructor<NoirLight__SvelteComponent_>, componentOptions?: SvelteComponentOptions<NoirLight__SvelteComponent_> | …
```
=> Fixes TS-Error on filters.test.ts

src/lib/utilities/Toast/Toast.svelte
Fixes #1403. The type of ``position`` in the ``Toast.svelte`` component was only defined through a JSDoc comment leading to TypeScript inferring the type as ``string``. Moved this to a TypeScript type instead, so that the type is now inferred correctly leading to intellisense/autocomplete working. See issue for more details.
=> Fix: Toast position incorrect type

src/docs/components/DocsAppBar/DocsAppBar.svelte, src/lib/styles/elements/lists.css, src/lib/styles/elements/popups.css, src/lib/utilities/Popup/popup.ts, src/lib/utilities/Popup/types.ts, src/routes/(inner)/components/autocomplete/+page.svelte, src/routes/(inner)/utilities/popups/+page.svelte, src/routes/+layout.svelte
Closes #1350
As well as:
Fixes #1338
Fixes #1336
Fixes #1345 
Fixes #1282
Fixes #1337
Fixes #1379
=> Popup refactor

src/lib/components/Tab/Tab.svelte, src/lib/components/Tab/TabGroup.svelte
This PR adds keyboard navigation to the TabGroup and Tab components, following the patterns described in [WAI-ARIA](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/).
Summarizing:
- Pressing the `left` and `right` arrow keys when the selected tab is focused will focus the tab sibilings
- Pressing `tab` when a tab is focused will focus the tab panel instead of another tab
- Pressing `shift+tab` from the tab panel will focus the selected tab
=> feat: add kbd navigation to tabs

src/lib/utilities/LightSwitch/LightSwitch.svelte
Fixes #1341
Lightswitch Initial State is always dark because when `modeCurrent` is not set in the local storage it will be treated as false and therefore dark.
I have updated the lightswitch to check `onMount` if the `modeCurrent` is **not** set in the local storage, then It will be set to the `modeOsPrefers` causing it to sync with the theme.
=> Fixed Lightswitch initial state always dark (#1341)

src/lib/utilities/Popup/popup.ts
When no element matches the query selector for either the arrow or the `[data-popup]` element, a new HTMLElement is created currently with `new HTMLElement()`. This doesn't work, because HTMLElement is meant to be an interface that element implement. Instead, we can use `document.createElement('div')` to create a new HTMLDivElement
=> fix illegal constructor bug for popup

src/lib/actions/Filters/filter.test.ts, src/lib/actions/Filters/filter.ts, src/lib/actions/Filters/svg-filters/Apollo.svelte, src/lib/actions/Filters/svg-filters/BlueNight.svelte, src/lib/actions/Filters/svg-filters/Emerald.svelte, src/lib/actions/Filters/svg-filters/GreenFall.svelte, src/lib/actions/Filters/svg-filters/Noir.svelte, src/lib/actions/Filters/svg-filters/NoirLight.svelte, src/lib/actions/Filters/svg-filters/Rustic.svelte, src/lib/actions/Filters/svg-filters/Summer84.svelte, src/lib/actions/Filters/svg-filters/XPro.svelte, src/routes/(inner)/actions/filters/+page.svelte
When a DOM element is marked as `hidden` Firefox will ignore it more
readily than other browsers, which lead to our filters not working in
Firefox. By removing the `hidden` class we are able to render filters in
Firefox.
Since the class was added to avoid rendering the DOM element, they now
create white space that we have to remove via utility classes.
The noir filter used a diffuse lighting effect that did not provide any
visual difference except visual glitches in both Firefox and Chrome. I
simply removed the effect. The filter looks indistinguishable.
This PR ensures that filters work as expected in Firefox as discussed here: https://github.com/skeletonlabs/skeleton/discussions/1426
=> Support filters in Firefox

src/lib/components/Tab/Tab.svelte
issue: #1446 
Fractional width was not applied because the `classesBase` was located on the child `div` instead of the parent `label` in Tab.
so I moved it and tested fractional width on tabs, which is working now.
=> Moved classesBase from tab to parent label

src/lib/actions/FocusTrap/focusTrap.ts
Fixes #1444
Fixes #1423 
I have also tested the focusTrap manually with the following components:
1. DocsSearch
2. Modal
3. Accordion
4. Drawer
5. Drawer with Accordions with anchor links
As described here: https://github.com/skeletonlabs/skeleton/issues/1444#issuecomment-1541461421 and following the second solution, I implemented a MutationObserver to monitor the children of the node and execute the `onScanElements` function.
1. Changed function names: (`onInit` -> `onScanElements`, `onDestroy` -> `onCleanUp`) because these functions are also used outside the lifecycle logic and I thought these names describe them better. (I would happily change them back if necessary)
2. The `onScanElements` function now receives a boolean indicating if the call was executed by the observer or at …
=> added mutationObserver to focusTrap

src/lib/actions/Clipboard/additional-svelte-typings.d.ts, src/lib/actions/Clipboard/clipboard.ts
Also: an event is fired when copying is ready.
- When copying a html node, mime-type is set to text/html
- An event is fired when copy is done so you can e.g., easily show a toast as feedback to the user.
=> #1453 Clipboard now uses text/html when copying a node.

sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte
Added an explanation for how to preload fonts to potentially avoid flicker on load.
https://discord.com/channels/1003691521280856084/1109062538517286923
ezpz on Discord noted that it fixes the flicker and it seems like a good place to add the tip to preload the font.
=> Added an explanation for how to preload fonts to potentially avoid flicker on load.

package.json
Added option for creating a svelte-kit library type in packages that adds things like svelte-package and publint as well as defaulting to playwright and vitest being true due to the higher likelihood of testing requirements
=> Added csl for creating a Svelte-kit library project in packages

packages/skeleton/package.json
This script is the reason why we would see the npm error about publishing duplicate packages. When executing, this would run `npm publish` twice.
=> fix: remove the publish script from `packages/skeleton/package.json`

packages/skeleton/package.json, packages/skeleton/src/lib/components/Table/Table.svelte, packages/skeleton/src/lib/utilities/CodeBlock/CodeBlock.svelte, packages/skeleton/src/lib/utilities/Drawer/Drawer.svelte, packages/skeleton/src/lib/utilities/Modal/Modal.svelte
Modal store was being imported from our `index.ts` rather than directly from where it's declared. This was causing runtime type errors as a result.
=> fix: modal store needs to be imported directly

sites/skeleton.dev/src/routes/(inner)/components/app-rail/+page.svelte
use the new `AppRailAnchor`
As I posted on Discord, the page state example for `AppRail` should use the new `AppRailAnchor` instead of `AppRailTile`.
=> docs(AppRail): fix page state example

.changeset/config.json
Small config change for changesets. `baseBranch` is used by changesets to determine what packages have been recently changed. This should've been pointing to `dev`.
=> chore: `baseBranch` for changesets should point to `dev` instead

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/docs_issue.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md
Close #1569
This PR updates the PR and Issue templates for GitHub.
If you modify files in `/package/skeleton`, run `pnpm changeset`, follow the prompts, then commit the markdown file. This automates our changelog.
=> Revised GitHub templates

sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte
Added instructions for changeset.
=> docs: added Changeset docs

.changeset/rotten-apes-own.md, cspell.json, sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionTailwind.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/lightswitches/+page.svelte
Updated a broken link, popups ordering in links.ts, removing add-svelte from CLI instructions (they remain in manual), making a note about .dark being inserted into app.html by CLI
=> Doc updates resulting from monorepo migration

.changeset/wild-tools-ring.md, sites/skeleton.dev/src/routes/(inner)/components/avatars/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/file-buttons/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/file-dropzone/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/progress-radials/+page.svelte
Closes #1571 
removed shorthand prop definitions.
docs: removed shorthand prop definitions.
=> Docs: remove shorthand props

.changeset/big-paws-melt.md, packages/skeleton/src/lib/utilities/Popup/popup.ts
Closes #1586 
The popup focusable elements were not updated when the input changed in Autocomplete causing the index to be stuck in the input if the list changed and the first element is not existing anymore.
updated the `focusablePopupElements` in `onWindowKeyDown`.
bugfix: updated focusablePopupElements onWindowKeyDown in popup to allow tabbing into changed lists in Autocomplete
=> update focusable elements onWindowKeyDown

.changeset/smooth-rockets-know.md, packages/skeleton/package.json
Closes #1581 
Replaces `index` for `index.d.ts` from `typesVersions` map in `package.json`. Even though SvelteKit's [packaging docs](https://kit.svelte.dev/docs/packaging#typescript) states:
> Note that if you opt into typesVersions you have to declare all type imports through it, including the root import (which is defined as `"index": [..]`). 
I think this may actually be a typo in the SvelteKit docs.
Fortunately, this change won't negatively effect any users that may already be importing their components with the `@skeletonlabs/skeleton/index` path since it was never a valid import path in the first place. If they imported anything from this path, the app would just error.
I also added the type declaration path for our plugin as well since that was missing.
Changesets automate our …
=> bugfix: changed `typesVersions` map to point to `index.d.ts`

packages/skeleton/src/lib/components/AppRail/AppRail.svelte, packages/skeleton/src/lib/components/AppRail/AppRailAnchor.svelte, packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte, packages/skeleton/src/lib/components/AppRail/AppRailTile.test.ts, sites/skeleton.dev/src/routes/(inner)/components/app-rail/+page.svelte
Closes #1549
- added slot lead to the docs example
- centered the icon content of AppRailAnchor.
- added title to AppRail and AppRailTile (this could required changeset but I will wait for you to decide)
- updated docs to use the title also in AppRailTile
- deleted an outdated test that was covering `Overrides tag when href is passed` which is now replaced by AppRailAnchor.
=> added anchor lead slot, added tile title

.changeset/nasty-deers-draw.md, packages/skeleton/src/lib/utilities/Modal/Modal.svelte
Closes #1544 
Closes #1539 
- Instead of closing modal `on:mouseDown`, we do the following:
1. register mouseDown if it was on the backdrop
2. close modal if the the mouseDown was already registered and the mouseUp was fired on the backdrop.
- using `preventDefault` to prevent double firing the events.
- forwarding touchstart and touchend events instead of handling them.
feat: modal backdrop interaction - register interaction on mousedown and close modal on mouseup
=> Feat: modal backdrop interaction

.changeset/itchy-mice-judge.md, packages/skeleton/src/lib/components/Stepper/Step.svelte, sites/skeleton.dev/src/routes/(inner)/components/steppers/+page.svelte
Closes #1476
Adds support for a `navigation` slot, which replaces the disabled Back button in the first step only.
=> Add nav slot to Step component

sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
Add a warning to the AppShell component page to explain that scrolling isn't globally scoped and that the users will need to first focus the content regions before scrolling.
Documentation to address issue #1408 
=> chore: AppShell documentation warning that scrolling is not window scoped

.changeset/empty-students-mix.md, packages/skeleton/src/lib/utilities/Drawer/Drawer.svelte
Closes #1610
Changes:
1. `backdrop` event only fires on backdrop interaction (not on drawer interaction).
2. implemented `drawer` event that fires on drawer interaction.
3. changed handle functions param type from `any` to the appropriate event type.
4. forwarded `touchstart` and `touchend`. (backward compatibility).
bugfix: drawer - fire backdrop event only on backdrop interaction, implemented drawer event on drawer interaction
=> bugfix: fire backdrop event only on backdrop interaction

sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte
Closes #1620
Fixed a minor typo on the themes page related to font family overrides.
=> Fixed typo on the themes page

.github/pull_request_template.md
Closes #1622
Various improvements to THIS PR message template.
=> Updated GitHub PR template

.changeset/slimy-knives-tie.md, packages/skeleton/src/lib/components/ListBox/ListBoxItem.svelte
Closes #1485 
Checking the value of listBoxItem deeply will also work if the value is received from another source (different object reference).
I made sure this works with primitive types and with multiple options.
bugfix: checking listBoxItem value equality deeply instead of by reference.
=> bugfix: checking listBoxItem value equality deeply instead of by reference

.changeset/swift-parrots-help.md, packages/skeleton/.eslintrc.cjs, packages/skeleton/package.json, packages/skeleton/pnpm-lock.yaml, packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte, packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte, packages/skeleton/src/lib/components/TableOfContents/TableOfContents.svelte, packages/skeleton/src/lib/utilities/Drawer/Drawer.test.ts, packages/skeleton/src/lib/utilities/LightSwitch/LightSwitch.svelte, sites/skeleton.dev/.eslintrc.cjs, sites/skeleton.dev/package.json, sites/skeleton.dev/pnpm-lock.yaml, sites/skeleton.dev/src/routes/(inner)/components/radio-groups/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/buttons/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/chat/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/lists/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/data-tables/+page.svelte
[`eslint-plugin-svelte3`](https://github.com/sveltejs/eslint-plugin-svelte3) has been deprecated and replaced by [`eslint-plugin-svelte`](https://github.com/sveltejs/eslint-plugin-svelte). This PR aims to replace and configure the new plugin.
=> chore: swap the now deprecated `eslint-plugin-svelte3` for `eslint-plugin-svelte`

.changeset/big-maps-smell.md, .changeset/big-paws-melt.md, .changeset/empty-apricots-judge.md, .changeset/empty-students-mix.md, .changeset/famous-pears-jam.md, .changeset/few-flowers-train.md, .changeset/fluffy-gorillas-sneeze.md, .changeset/funny-plants-burn.md, .changeset/hip-dancers-march.md, .changeset/itchy-mice-judge.md, .changeset/nasty-deers-draw.md, .changeset/nervous-cheetahs-smile.md, .changeset/ninety-eagles-yawn.md, .changeset/odd-countries-admire.md, .changeset/pink-vans-rule.md, .changeset/purple-mice-fly.md, .changeset/slimy-knives-tie.md, .changeset/smooth-rockets-know.md, .changeset/swift-parrots-help.md
Cleaned up the changeset messages.
Instructions: Changesets automate our changelog. If you modify files in `/package/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.
=> chore: cleanup changesets

.changeset/thick-cougars-notice.md, packages/skeleton/src/lib/styles/partials/typography-prose.css
Closes #1646
fixed Typography-Prose headers typo
bugfix: fixed Typography-Prose headers typo.
=> bugfix: fixed Typography-Prose headers typo

.changeset/strange-falcons-provide.md, packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte
Closes #none
Removed duplicated word "content" in the description of Accordion Items.
Instructions: Changesets automate our changelog. If you modify files in `/package/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.
1 test skipped. Lightswitch test.
=> docs/accordion Remove duplicate word exposed in accordion doc

sites/skeleton.dev/src/routes/(inner)/components/app-rail/+page.svelte
An import of used component was missing in the documentation, added it
=> docs: Add missing import `AppRailAnchor`

.github/pull_request_template.md
Path `/package/skeleton` is invalid, replaced `package` with the correct directory `/packages`
=> docs: Typo in PR template

.changeset/lazy-pants-yawn.md, cspell.json, packages/skeleton/src/lib/utilities/Toast/Toast.svelte, packages/skeleton/src/lib/utilities/Toast/stores.ts, packages/skeleton/src/lib/utilities/Toast/types.ts, sites/skeleton.dev/src/routes/(inner)/utilities/toasts/+page.svelte
Closes #1311
1. ability to hide the x button using the prop `hideDismiss`.
2. ability to remain visible if hovering using the prop `hoverVisible`.
3. ability to close toast programmatically using the toastId.
1. I was worried that the user could activate `hideDismiss` and the toast will stay on screen infinitely. so I have set autohide to true automatically when `hideDismiss` is set and wrote a note in the docs about it.
2. Should I add some hover effect when `hoverVisible` is set so the user knows that hovering the toast will keep it open?
3. remaining visible when hovering is simpler when we just delete the timeout and recreate it after, but the time spent on the toast is not calculated, so should I track the time and kind of continue it after `mouseLeave` or is it ok to just reset the …
=> Feat: toast enhancement

sites/skeleton.dev/src/routes/(inner)/utilities/drawers/+page.svelte
Seems a typo caused by copy-paste, replaced `Modal` with `Drawer`.
=> docs: typo in Drawer docs

.changeset/fast-apricots-sing.md, packages/skeleton/src/lib/utilities/Drawer/Drawer.svelte
Closes #1671
so by setting the transition like this:
```ts
transition:fly|local={{ x: anim.x, y: anim.y, duration }}
```
apparently svelte will save the params values and use them for `out` transition, so updating these values won't update the transition.
to solve this, I replaced the transition with in/out, so Svelte would check the value of the params before going out. which solves the problem.
Note: this is just my understanding of the issue, I didn't find any official docs that tackle this problem or indicate how Svelte handles the transitions internally, so my interpretation could be awfully wrong 😄.
bugfix: Fixed double drawers unexpected closing direction.
=> Bugfix: double drawer unexpected closing direction

sites/skeleton.dev/src/routes/(inner)/components/ratings/+page.svelte
~~Closes #...~~
In the Rating component demos, "icon" is misspelled as "con". This fixes this.
I'm not sure if I correctly understood this, ngl. Given I only changed the docs, do I have to do anything?
```
echo "Error: no test specified" && exit 1
``` huh?
=> bugfix:fixed spelling mistake @ ratings: con => icon

.changeset/young-cameras-sparkle.md, packages/skeleton/src/lib/components/Ratings/Ratings.svelte, sites/skeleton.dev/src/routes/(inner)/components/ratings/+page.svelte
Closes #1685
Added iconType property to make the icons interactive on demand.
bugfix: `Ratings` icons are only interactive when `iconType` is set to `button`.
=> bugfix: interactive ratings icons on demand

.changeset/two-donuts-remember.md, packages/skeleton/.eslintrc.cjs, packages/skeleton/src/lib/actions/Filters/filter.test.ts, packages/skeleton/src/lib/actions/Filters/filter.ts, packages/skeleton/src/lib/components/Avatar/Avatar.test.ts, packages/skeleton/src/lib/components/Stepper/Step.test.ts
Filter names are now typesafe.
Note the following type:
```ts 
type FilterName = `#${Filters[number]}` | (string & {});
``` 
This allows users to get the autocomplete option for our filter presets while also permitting them into adding their own filter if they created one.
I also fixed the types for 2 tests, just to finally get rid of their warnings too.
Please read and apply all [contribution …
=> bugfix: Enhanced types for the filter action

.changeset/breezy-kings-type.md, packages/skeleton/src/lib/actions/Clipboard/additional-svelte-typings.d.ts, packages/skeleton/src/lib/actions/Clipboard/clipboard.ts
Made the clipboard action just a little more typesafe.
=> bugfix: Enhanced types for the clipboard action

.changeset/clean-carrots-nail.md, packages/skeleton/src/lib/components/Radio/RadioGroup.svelte
Closes #1672
display space-x only on row flex as it is not needed on column flex
bugfix: removed horizontal space on vertical radio group.
=> RadioGroup vertical spacing fix

.changeset/tiny-camels-try.md, packages/skeleton/src/lib/components/AppShell/AppShell.svelte, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
Closes #1670
Applied changes suggested by @AdrianGonz97 in https://github.com/skeletonlabs/skeleton/issues/1670#issuecomment-1615209699
bugfix: fixed `scroll` event type in `AppShell`
=> bugfix: appshell-scroll-handler

packages/skeleton/postcss.config.cjs, packages/skeleton/svelte.config.js, sites/skeleton.dev/postcss.config.cjs, sites/skeleton.dev/svelte.config.js
This fixes the _terribly annoying_ postcss parsing error that mainly occurs when you're working directly with the whole monorepo in your editor:
To reproduce, open the project in vscode from the **root of the monorepo** and checkout the `dev` branch. 
Open the `sites/skeleton.dev/src/routes/+page.svelte` file and you should see the error shown above.
No changeset needed
=> chore: fixes the `Semicolon or block is expected` postcss parsing error

.changeset/big-ligers-rest.md, packages/skeleton/src/lib/components/Ratings/Ratings.svelte
Before this fix, the following warning occurred:
A11y: <svelte:element> with click handler must have an ARIA role
This was an issue because the `on:click` binding was always applied, even when the element would be not interactive (a `span`).
=> bugfix: fix a11y warning in Ratings component

packages/skeleton/src/lib/utilities/Modal/Modal.svelte
Closes #1755
This error is showing when using [Modals](https://www.skeleton.dev/utilities/modals) :
`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`
=> Add passive event listener Modal

.changeset/witty-pigs-wave.md, packages/skeleton/src/lib/utilities/Modal/Modal.svelte
Closes #1683
Fixed the bug using the code [suggestion](https://github.com/skeletonlabs/skeleton/issues/1683#issuecomment-1599617938)
bugfix: fixed Scroll to the top of the modal, when the modal is bigger than the view.
=> bugfix: scroll to top of modal, when modal is bigger than view

sites/skeleton.dev/src/lib/layouts/DocsThemer/DocsThemer.svelte, sites/skeleton.dev/src/routes/(inner)/docs/generator/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionInstall.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionTailwind.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionThemes.svelte, sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte
=> V2 Theme generator and doc updates

packages/plugin/src/styles/components/buttons.css, sites/skeleton.dev/src/routes/(inner)/elements/buttons/+page.svelte
Closes #1724
Reinstate the `.btn-base` style, including the alias `.btn-md` to fix issues with responsive styling.
=> v2: Chore/reinstate btn-base

.changeset/kind-sheep-look.md, packages/skeleton/src/lib/index.ts, packages/skeleton/src/lib/utilities/Drawer/Drawer.svelte, packages/skeleton/src/lib/utilities/Drawer/stores.ts, packages/skeleton/src/lib/utilities/Modal/Modal.svelte, packages/skeleton/src/lib/utilities/Modal/Modal.test.ts, packages/skeleton/src/lib/utilities/Modal/stores.ts, packages/skeleton/src/lib/utilities/Toast/Toast.svelte, packages/skeleton/src/lib/utilities/Toast/Toats.test.ts, packages/skeleton/src/lib/utilities/Toast/stores.ts, packages/skeleton/src/lib/utilities/index.ts, sites/skeleton.dev/src/lib/components/DocsAppBar/DocsAppBar.svelte, sites/skeleton.dev/src/lib/components/DocsDrawer/DocsDrawer.svelte, sites/skeleton.dev/src/lib/components/DocsSidebar/DocsSidebar.svelte, sites/skeleton.dev/src/lib/modals/DocsSearch/DocsSearch.svelte, sites/skeleton.dev/src/lib/modals/examples/ModalExampleEmbed.svelte, sites/skeleton.dev/src/lib/modals/examples/ModalExampleForm.svelte, sites/skeleton.dev/src/lib/modals/examples/ModalExampleImage.svelte, sites/skeleton.dev/src/lib/modals/examples/ModalExampleList.svelte, sites/skeleton.dev/src/routes/(inner)/components/input-chips/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/chips/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/drawers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/toasts/+page.svelte, sites/skeleton.dev/src/routes/+layout.svelte, sites/skeleton.dev/src/routes/blog/+page.svelte, sites/skeleton.dev/src/routes/home-partials/HomeSvelteKit.svelte
Closes #522 
This PR aims to fix the SSR related issues that comes with stores that are defined in the global scope. To fix this, we'll be using Svelte's context API as a means of attaching these stores to the component tree for safe keeping.
The first change is how these utility stores are initialized. As we are using contexts now, we need to initialize and set the contexts for these stores in the root layout file. 
We provide a utility function, `initializeStores()`, that will handle the initialization for the users:
```svelte
<script lang="ts">
import { Toast, Modal, Drawer, initializeStores } from "@skeletonlabs/skeleton";
initializeStores();
</script>
<Toast />
<Modal />
<Drawer />
```
Stores for `Modal`, `Toast`, and `Drawer` are now accessed through a function that will retrieve …
=> breaking: Refactor global stores for `Modal`, `Toast`, and `Drawer`

.changeset/flat-insects-film.md, packages/plugin/scripts/compile-css-to-js.ts, packages/plugin/scripts/generate-jss.ts, packages/plugin/src/index.ts, packages/plugin/src/styles/base/core.css, packages/plugin/src/styles/base/elements.css, packages/plugin/src/styles/base/forms.css, packages/plugin/src/styles/tailwind.css
Simplifies the CSS in JS generation and removes the need to strip out base TW styles
=> (v2) Fixed plugin's base styles being wrongfully removed

.changeset/spicy-horses-wonder.md, packages/skeleton/src/lib/components/Paginator/Paginator.svelte
Fixed an issue where the paginator page would be set to -1 if the size was 0
=> bugfix: Paginator page set to -1 when empty

.changeset/five-deers-listen.md, packages/create-skeleton-app/.prettierignore, packages/plugin/src/index.ts, packages/plugin/src/tailwind/themes/crimson.ts, packages/plugin/src/tailwind/themes/gold-nouveau.ts, packages/plugin/src/tailwind/themes/hamlindigo.ts, packages/plugin/src/tailwind/themes/index.ts, packages/plugin/src/tailwind/themes/modern.ts, packages/plugin/src/tailwind/themes/rocket.ts, packages/plugin/src/tailwind/themes/sahara.ts, packages/plugin/src/tailwind/themes/seafoam.ts, packages/plugin/src/tailwind/themes/skeleton.ts, packages/plugin/src/tailwind/themes/vintage.ts, packages/plugin/src/types.ts
Closes #1893
Added optional dark mode specific properties for themes.
These properties can be added via the optional `properties_dark` prop for custom themes.
Ex:
```ts
import type { CustomThemeConfig } from '@skeletonlabs/tw-plugin';
export const customTheme = {
name: "my-custom-theme",
// base
properties: {
'--color-primary-50': '219 245 236',
'--color-primary-100': '207 241 230',
'--color-primary-200': '195 238 224',
// ...
},
// applies on dark theme only (optional)
properties_dark: {
'--color-primary-50': '219 245 236',
'--color-primary-100': '207 241 230',
'--color-primary-200': '195 238 224',
}
} satisfies CustomThemeConfig;
```
Instructions: Changesets automate our changelog. If you modify files in `/packages/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the …
=> feat: Added optional dark mode theme properties

sites/skeleton.dev/src/lib/components/DocsAppBar/DocsAppBar.svelte
Closes #1895
Update the doc site app bar to include a Versions drop down. This includes links to prior version, which include only v1 at this point.
=> v2: version picker for doc site App Bar

.changeset/fluffy-garlics-carry.md, packages/plugin/src/types.ts
Fixed the type for `CustomThemeConfig`. The intersection for `BaseTheme` was causing the custom config to require `properties_dark` to be defined.
=> fix: `CustomThemeConfig` shouldn't require `properties_dark` to be defined

.changeset/metal-dots-melt.md, packages/plugin/src/styles/base/core.css
Closes #1797
Makes scrollbar corner background transparent using the `::-webkit-scrollbar-corner` pseudo-element.
=> Bugfix: make scrollbar corner background transparent

.changeset/soft-tables-wave.md, packages/skeleton/src/lib/components/FileButton/FileButton.svelte, sites/skeleton.dev/src/routes/(inner)/components/file-buttons/+page.svelte
Closes #1876 
- Moved `.btn` class to `button` prop so it can be customised to render a buton without hardcoded styles.
=> bugfix: allow unstyled file buttons

.changeset/large-donuts-brake.md, sites/skeleton.dev/src/lib/layouts/DocsThemer/DocsThemer.svelte, sites/skeleton.dev/src/lib/layouts/DocsThemer/types.ts
Closes #1888 (issue was already closed but not implemented)
This pull request introduces a new feature that allows users to lock colors from randomization in the theme generator. The purpose of this pull request is to enhance the theme generation process by giving users more control over specific colors.
=> feat: ability to lock colors in theme generator

packages/skeleton/src/lib/index.ts, packages/skeleton/src/lib/utilities/Drawer/stores.ts, packages/skeleton/src/lib/utilities/Drawer/types.ts, packages/skeleton/src/lib/utilities/Modal/stores.ts, packages/skeleton/src/lib/utilities/Modal/types.ts, packages/skeleton/src/lib/utilities/Toast/stores.ts, packages/skeleton/src/lib/utilities/Toast/types.ts, sites/skeleton.dev/src/routes/(inner)/utilities/drawers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/toasts/+page.svelte
This PR simply adds a note to each of the stores stating that their respective store getter functions must be invoked at the top level of a component. 
I also noticed that we weren't exposing the type for each of the stores, so I went ahead and added that with this PR.
- Exposed the following type: `ToastStore`, `DrawerStore`, and `ModalStore`
- Added those newly exposed type to their respective pages in the docs
- Improved the JSDoc comment for each getter function, such that it specifies that the function _must_ be invoked from the top level of a component:
- Added this note for each store:
---
Copying over the original message from Discord here too:
I think this is another topic worth bringing up. Looking into this, the introduction of using contexts to store our `toastStore`, …
=> docs: Adds a note for each store that uses context

.changeset/tall-jobs-wait.md, packages/skeleton/src/lib/utilities/TableOfContents/crawler.ts, sites/skeleton.dev/src/routes/(inner)/elements/chat/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/table-of-contents/+page.svelte
Closes #1915
Instead of hardcoding a `toc-` prefix to all Table of Content hash links, we now recommend supplying a custom heading ID when a conflict arises. However, I've also implement a means to manually set your own prefix/suffix in case this is required.
=> ToC optional prefix/suffice params added

packages/skeleton/src/lib/utilities/Modal/Modal.test.ts, packages/skeleton/src/lib/utilities/Modal/ModalTest.svelte, packages/skeleton/src/lib/utilities/Toast/Toast.test.ts, packages/skeleton/src/lib/utilities/Toast/ToastTest.svelte
No issue, just DominikG asking about our failing Tests
Added a TestComponent wrapping the Modal/Toast and their stores and refactored the tests to utilize them.
=> Added TestComponents for Modal & Toast to correctly initialize their Stores

sites/skeleton.dev/src/lib/layouts/DocsThemer/settings.ts
Quick fix for quotation marks in the theme generator for the CSS-in-JS format.
=> fix(DocsThemer): fix quote problem with serif/mono fonts

sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
Closes #1936
Updates the App Shell docs to explain how to auto-scroll the page region to the top on navigation.
=> Updated AppShell docs for auto-scroll top on navigate

sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte
Closes #2008
Resolved a number of theme doc issue in regards to the v2 `:root [data-theme='skeleton'] {}` selector structure.
=> Updated theme docs to new root data-theme structure

.changeset/beige-poets-lie.md, packages/plugin/src/styles/components/forms.css
Closes #1838
Added additional selectors for disabled input styling to include inputs nested inside input groups.
=> Added input group disabled selectors + changesets

.changeset/tall-mice-exercise.md, sites/skeleton.dev/src/routes/(inner)/elements/forms/+page.svelte
None
One of the forms' examples was missing the some stub code. I added that by copying it straight from the page source code.
---
"skeleton.dev": major
---
bugfix: added missing source code to tailwind forms example
=> bugfix: added missing source code in input group examples

sites/skeleton.dev/src/lib/layouts/DocsThemer/DocsThemer.svelte, sites/skeleton.dev/src/lib/layouts/DocsThemer/settings.ts
`Courier New` was using a double quote instead of a single, so that's been changed.
I also made the output string for fonts use template literals instead of either a single or double quotes so that we can avoid the above issue entirely.
=> docs: Fixed theme generator's `mono` font

.changeset/modern-chairs-buy.md, packages/skeleton/src/lib/components/AppShell/AppShell.svelte, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
- docs for scrollbar-gutter in AppShell didn't match the property name
- syntax to apply style seems wrong
=> fix: scrollbar-gutter code and docs

.vscode/settings.json, packages/skeleton/.changeset/gold-jars-pretend.md, packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte, packages/skeleton/src/lib/components/Autocomplete/types.ts, sites/skeleton.dev/src/routes/(inner)/components/autocomplete/+page.svelte
Closes #1188 
Fixes generics on values and other props in Autocomplete component
feat: autocomplete generics
=> feat/Autocomplete Generics

.changeset/fast-pugs-tan.md, packages/skeleton/src/lib/components/Stepper/Step.svelte
Closes #1975 
Adds `fill-current` to the lock svg icon so styling from the surrounding item is applied and more visible.
=> bugfix: add styling to the lock icon of the stepper component

packages/skeleton/src/lib/utilities/CodeBlock/CodeBlock.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionInstall.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionSkeleton.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionTailwind.svelte, sites/skeleton.dev/src/routes/(inner)/docs/purgecss/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/quickstart/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/forms/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/codeblocks/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte, sites/skeleton.dev/src/routes/+layout.svelte, sites/skeleton.dev/src/routes/blog/[slug]/+page.svelte
Closes #2024 and #1381 
Improves the Code Blocks documentation by adding an example of configuring PurgeCss and a note on reducing bundle size. 
=> Improve code blocks docs

.changeset/cuddly-zebras-eat.md, packages/plugin/src/styles/components/buttons.css
Closes #2058 
added disabled styling for the btn-icon class
=> bugfix: added a disabled style for the btn-icon class

packages/skeleton/scripts/post-build.js
Closes #2049 
There were a number of issues here:
- When extracting the jsdocs, some of the newer components had multiple script blocks that the script hadn't accounted for, so it wasn't getting all of the jsdocs available.
- `svelte-package` emits .d.ts files in different ways depending on what the component does internally, sometimes we want to insert into `props() : {`, `props: {` or `declare const __propDef: {`. We are now aiming for the `[x: string]: any;` string as it seems to be universally available as the first line after the aforementioned strings.
There is so far only one case where this is not true - packages/skeleton/src/lib/components/TreeView/TreeViewDataDrivenItem.svelte and I can't see what is special about this one - nor can I see why this one (and it seems to be the …
=> Multi script block handling for jsdocs

sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
Closes #2040
Added import statement like suggested by @maehr 
=> added missing import statement in appshell docs

.changeset/modern-bags-join.md, packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte
Using `text-start` instead of `text-left`
=> Supporting RTL layout in Accordion component

sites/skeleton.dev/package.json, sites/skeleton.dev/pnpm-lock.yaml, sites/skeleton.dev/vite.config.ts
```
assets/0.3cb19104.css                                           236.36 kB │ gzip:  32.18 kB
```
```
assets/0.3cb19104.css                                           197.45 kB │ gzip:  27.86 kB
```
---
The reduction is even more dramatic if we also purge the icon related stylesheets as part of #2114:
```
assets/0.99bb4257.css                                           329.71 kB │ gzip:  54.57 kB
```
```
assets/0.99bb4257.css                                           202.99 kB │ gzip:  29.57 kB
```
Instructions: Changesets automate our changelog. If you modify files in `/packages/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please …
=> docs: Added `vite-plugin-tailwind-purgecss` to the docs site

sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte
Closes #2117
Popup docs updated to include an example using an `#each` block to iterate popups.
=> Add popup loop example

sites/skeleton.dev/vite.config.ts
Closes #2156
PurgeCSS config updated to allow Carbon ads
=> PurgeCSS config updated to allow Carbon ads

sites/skeleton.dev/src/routes/(inner)/elements/chips/+page.svelte
[Discord thread](https://discord.com/channels/1003691521280856084/1164155860096917585)
Clarified toggleFilter function in Chips Element Documentation
=> Clarified toggleFilter function in Chips Element Documentation

packages/skeleton/src/lib/components/Table/Table.svelte
Closes #2147
The integer 0 should not be replaced with '-'. in Table cells This PR aims to fix that. 
=> chore: added logic to enable 0 in table cells

sites/skeleton.dev/src/routes/(inner)/utilities/popups/+page.svelte
Closes #2148
I was stuck for a while on this and finally realized that it was just the display override because of using flex on the `[data-popup]` div.
=> add popup warning

sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte
This PR removes an explicit `any` type from the AppShell scroll to top docs, and substitutes the proper type from sveltekit. 
Also use optional chaining to simplify the checks for `isNewPage`
No changeset added since this is a docs only change.
=> docs: strong types for `AppShell` scroll-to-top

sites/skeleton.dev/src/lib/components/DocsSidebar/DocsSidebar.svelte, sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/docs/tauri/+page.svelte
Added new integrations section and a guide to integrate Skeleton with Tauri.
This is mostly done, but I still want to add a template for people to use so it's not ready to merge. As it's not complete, changeset hasn't been added yet.
=> docs/Add new Integrations section + Tauri guide

sites/skeleton.dev/src/lib/modals/DocsSearch/DocsSearch.svelte
Closes #2182
Bugfix for doc search input focus style
=> Bugfix for doc search input focus style

sites/skeleton.dev/src/routes/(inner)/elements/lists/+page.svelte
I struggled a bit understanding the Skeleton.dev > Explore > Tailwind > Lists > Nav List for highlighting. As a newbie I was unfamiliar with the shorthand format it was written in, and after searching Discord for that the `{href}` was shorthand for how it would be written inside a loop. This makes sense, but was a bit unclear as someone newer.
So I suggest changing the highlighting example to match the main Nav List example just above the highlighting example. 
Dominik and Niktek helped with some pointers in the Discord channel, as well as suggesting changing the icons.
{description}
Instructions: Changesets automate our changelog. If you modify files in `/packages/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that …
=> Docs/ Nav List example for highlighting to match main Nav List example

.changeset/warm-mirrors-kneel.md, packages/skeleton/src/lib/components/ProgressBar/ProgressBar.svelte, packages/skeleton/src/lib/components/ProgressRadial/ProgressRadial.svelte
Closes #2195
Progress Bar and Radial transition prop added
=> Progress Bar and Radial transition prop added

.github/pull_request_template.md
=> PR Template Updates

.changeset/cool-phones-fold.md, .changeset/seven-rockets-add.md, packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte
Closes #2163
I am unsure if these comments relate to the issue so i kept this as a draft for the moment. 
I chose role of button as researching how similar functionality was handled, such as:
https://www.perkins.org/
And this article:
https://betterprogramming.pub/how-to-turn-a-div-into-an-accessible-button-in-react-fbf236283d6d
=> A11y improvements for AppRailTile

.changeset/gold-ads-flash.md, .changeset/ninety-dingos-search.md, .changeset/plenty-drinks-tan.md, .changeset/rich-squids-decide.md, .changeset/seven-rockets-add.md, .changeset/sharp-suns-wash.md, .changeset/tender-jobs-allow.md, .changeset/warm-mirrors-kneel.md, .github/pull_request_template.md, packages/plugin/src/styles/components/chips.css, packages/plugin/src/styles/components/lists.css, packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte, packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte, packages/skeleton/src/lib/components/ProgressBar/ProgressBar.svelte, packages/skeleton/src/lib/components/ProgressRadial/ProgressRadial.svelte, packages/skeleton/src/lib/components/Table/Table.svelte, packages/skeleton/src/lib/components/TreeView/RecursiveTreeViewItem.svelte, packages/skeleton/src/lib/components/TreeView/TreeViewItem.svelte, packages/skeleton/src/lib/utilities/Drawer/Drawer.svelte, packages/skeleton/src/lib/utilities/Modal/stores.ts, sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/components/autocomplete/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/tree-views/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/chips/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/lists/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte, sites/skeleton.dev/src/routes/+page.ts, sites/skeleton.dev/src/routes/home-partials/HomeContributors.svelte
=> Merge for release 11/7/2023

sites/skeleton.dev/src/routes/(inner)/components/tables/+page.svelte
Closes #2234
Table example output was created dynamically while the code example was static. Both are now dynamics and will display data that faker generated
=> Made table source example dynamic

sites/skeleton.dev/src/routes/(inner)/components/paginators/+page.svelte
Closes #2211
Documentation on updating pagination size accordingly to the dynamic data source
=> docs update on pagination  with dynamic size

sites/skeleton.dev/package.json, sites/skeleton.dev/pnpm-lock.yaml
Bumps `vite-plugin-tailwind-purgecss` to the latest version. I just pushed an update that decreased the plugin's processing time by 80%. This should reduce our build times by a considerable amount. 
Related PR: https://github.com/AdrianGonz97/vite-plugin-tailwind-purgecss/pull/19
=> chore: Bump `vite-plugin-tailwind-purgecss` version

sites/skeleton.dev/src/routes/(inner)/docs/get-started/SectionThemes.svelte
Fixes a small typo in the SectionThemes portion of the getting started section.
=> fix typo in SectionThemes component

.changeset/smart-ligers-rest.md, packages/skeleton/src/lib/components/Avatar/Avatar.svelte, packages/skeleton/src/lib/components/Avatar/Avatar.test.ts
Closes #2321
Added a ``fontSize`` prop that targets the font size for the initials, this allows for more fine grained control over the initials when having bigger or smaller avatars
=> Feat: Avatar fontSize prop

.changeset/thick-trains-chew.md, packages/skeleton/src/lib/components/Radio/RadioGroup.svelte, packages/skeleton/src/lib/components/Radio/RadioGroup.test.ts, sites/skeleton.dev/src/routes/(inner)/components/radio-groups/+page.svelte
Closes #2295
Made spacing props to adopt value passed in and set *space-x-1* as default value for it
=> Fix RadioGroup spacing

sites/skeleton.dev/src/routes/(inner)/utilities/table-of-contents/+page.svelte
Closes #2294
Added a bit more descriptive information on which typical case would be useful for keyed update, made changes to code block.
Couldn't find a better way to animate this and give a better example. Do feedback if you have better ideas in mind.
=> Modified keyed update on ToC docs

sites/skeleton.dev/src/routes/(inner)/utilities/modals/+page.svelte
Closes #2127
Add built-in response section to docs
=> Update modal docs: add built-in response section

.changeset/modern-ways-greet.md, packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte, sites/skeleton.dev/src/routes/(inner)/components/accordions/+page.svelte
N/A - Discussed in Discord [#contributors](https://discord.com/channels/1003691521280856084/1003699523522142399/1181305822261825586) channel.
Adds two optional slots for customizing the `AccordionItem` icon when open or closed.
- `iconClosed` - What to display when the given `AccordionItem` is closed.
- `iconOpen` - What to display when the given `AccordionItem` is open.
Updated the component documentation page with a showcase + code example.
[Preview Link](https://skeleton-docs-77t1teymf-skeleton-labs.vercel.app/components/accordions#open--close-icons)
Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while …
=> feat: Add slots to allow customizing AccordionItem open/close icons

sites/skeleton.dev/vite.config.ts
Closes #2268
Resolve an issue that allows PurgeCSS to remove required blog styles.
=> Blog style PurgeCSS fix

.changeset/gentle-melons-decide.md, packages/skeleton/src/lib/utilities/Modal/Modal.svelte
Closes #2335
Removed manual subscription in favor of svelte's auto subscription syntax ($), this removes the need to manually unsubscribe (which wasn't done in the first place).
=> Bugfix; Removed manual subscription in Modal component causing memory leak

package.json, sites/skeleton.dev/vite-plugin-skeleton-plugin-watcher/index.ts
This PR addresses an issue where our watcher plugin that rebuilds the TW plugin previously didn't work for contributors that were using Windows.
=> chore: Fix watcher plugin for Windows users

.changeset/eight-bugs-report.md, packages/skeleton/src/lib/components/Stepper/Step.svelte, packages/skeleton/src/lib/components/Stepper/Stepper.svelte
Closes #2323
Rather than pass the event dispatcher down through the context API, we now instead pass the individual event handler functions. This ensures the events trigger in the parent, which means the documentation matches implementation.
=> Step events now occur in parent Stepper

.changeset/spotty-ads-care.md, packages/plugin/src/styles/components/tables.css, sites/skeleton.dev/src/routes/(inner)/components/tables/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/tables/+page.svelte
Closes #2302
Closes #2318
> NOTE: I grouped these since they are both related to tables
1. Element: Adjusts the whitespace breakpoint from `lg` -> `md`
2. Component: Adds a reactive table data example to the docs
=> Updated table style and add reactive data example

sites/skeleton.dev/src/routes/(inner)/elements/forms/+page.svelte
Closes #2230
Updated the input-group docs to showcase the examples in a vertical column rather than a 2x2 grid.
=> Update input group doc layout

.changeset/nervous-roses-arrive.md, packages/skeleton/src/lib/actions/Clipboard/additional-svelte-typings.d.ts, packages/skeleton/src/lib/actions/Clipboard/clipboard.ts
Noticed that we were using an `additional-svelte-typings.d.ts` type declaration file to type the `copyComplete` event for the clipboard action. This PR replaces that with the more idiomatic approach of using the `ActionReturn` type instead.
=> chore: Use the `ActionReturn` type for the `clipboard` action

sites/skeleton.dev/src/routes/(inner)/elements/chat/+page.svelte
Closes #2410
switched listbox navigation to buttons in chat UI as suggested in the ticket.
=> switched navigation listbox to buttons

.changeset/famous-pots-trade.md, packages/skeleton/src/lib/components/TreeView/RecursiveTreeView.svelte
Closes #2426
Deleted unused props ` disabled`  and ` open` from the recursive-tree-view
=> bugfix: deleted unused props

.changeset/nasty-terms-allow.md, packages/skeleton/src/lib/utilities/CodeBlock/CodeBlock.svelte
Closes #2416
changed the type to ` button` so the copy button doesn't submit forms.
=> bugfix: codeblock copy btn type

sites/skeleton.dev/src/routes/(inner)/components/progress-radials/+page.svelte
None. 
The Progress Radials component documentation contains an error in the styling code example, specifically the strokeLinecap should be set to a string 'butt' not a variable called butt. 
Current:
```svelte
<ProgressRadial ... stroke={100} meter="stroke-primary-500" track="stroke-primary-500/30" strokeLinecap={butt} />
```
Corrected:
```svelte
<ProgressRadial ... stroke={100} meter="stroke-primary-500" track="stroke-primary-500/30" strokeLinecap="butt" />
```
chore: Fixed missing quote strings around "butt" in the Progress Radial documentation.
- Failing on unmodified file:
```bash
│ Error: Module '"$env/static/private"' has no exported member 'VERCEL_ENV'. 
│ import type { …
```
=> Fix faulty example progress radial documentation

.changeset/real-cougars-invent.md, packages/skeleton/src/lib/components/InputChip/InputChip.svelte
Closes #2440
added `labelSelect` to provide aria-label on input-chip select
=> bugfix: input chip select aria

packages/plugin/src/styles/components/modals.css
Closes #2436 
bugfix: removed outline style from input in modal
=> added input-group input  exception

sites/skeleton.dev/src/routes/(inner)/docs/colors/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/ssd/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/chat/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/lightswitches/+page.svelte
Closes #2472
Fixing a few low hanging linting issues
=> Linting pass

sites/skeleton.dev/src/routes/(inner)/docs/ssd/ClientSSD.svelte, sites/skeleton.dev/src/routes/(inner)/docs/ssd/ServerSSD.svelte
Closes https://github.com/skeletonlabs/skeleton/issues/2513
This PR fixes a small typo in the documentation or Svelte Simple Datatables. Currently, in step 2 of [Creating the Components](https://www.skeleton.dev/docs/ssd#creating-the-components), both the Client-Based and Server-Based instructions misspell the path to the Datatable.svelte file. 
Before the fix, the path is `/src/lib/comonents/Datatable.svelte`.
After the fix, the path is `/src/lib/components/Datatable.svelte`
link to documentation: https://www.skeleton.dev/docs/ssd
Note: this is my first contribution to any open source project :0  small change but exciting! 
Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit …
=> docs/fix typo in file path for Datatable.svelte within SSD docs

sites/next.skeleton.dev/src/components/docs/ChipsBar.astro
fixes docs links that ends with a slash by deleting the slash.
=> delete Docs link trailing slash if included

packages/skeleton/scripts/convert-theme.ts, packages/skeleton/src/plugin/themes/catppuccin.ts, packages/skeleton/src/plugin/themes/cerberus.ts, packages/skeleton/src/plugin/themes/index.ts, packages/skeleton/src/plugin/themes/legacy/crimson.ts, packages/skeleton/src/plugin/themes/legacy/gold-nouveau.ts, packages/skeleton/src/plugin/themes/legacy/hamlindigo.ts, packages/skeleton/src/plugin/themes/legacy/modern.ts, packages/skeleton/src/plugin/themes/legacy/rocket.ts, packages/skeleton/src/plugin/themes/legacy/sahara.ts, packages/skeleton/src/plugin/themes/legacy/seafoam.ts, packages/skeleton/src/plugin/themes/legacy/skeleton.ts, packages/skeleton/src/plugin/themes/legacy/vintage.ts, packages/skeleton/src/plugin/themes/legacy/wintry.ts, packages/skeleton/src/plugin/themes/pine.ts, packages/skeleton/src/plugin/themes/rose.ts
#2360
Consolidates the preset and custom theme types into a single `Theme` type. Removes `properties_dark` and `enhancements` from the type. Updates the `properties` to match the current v3 structure.
=> NEXT theme type improvements

sites/next.skeleton.dev/src/content/components/common/accordions.mdx, sites/next.skeleton.dev/src/content/components/common/app-bars.mdx, sites/next.skeleton.dev/src/content/components/common/avatars.mdx, sites/next.skeleton.dev/src/content/components/react/accordions.mdx, sites/next.skeleton.dev/src/content/components/react/app-bars.mdx, sites/next.skeleton.dev/src/content/components/react/avatars.mdx, sites/next.skeleton.dev/src/content/components/svelte/accordions.mdx, sites/next.skeleton.dev/src/content/components/svelte/app-bars.mdx, sites/next.skeleton.dev/src/content/components/svelte/avatars.mdx, sites/next.skeleton.dev/src/content/resources/contribute/documentation.mdx
#2353
Remove docs common mdx body content, redistribute to each framework-specific mdx page.
=> NEXT - remove docs common mdx body content

sites/skeleton.dev/src/routes/(inner)/docs/tokens/+page.svelte
Closes #2412
Remove the Design Tokens > Divider documentation which incorrectly lists support for color pairings. These are not supported in Skeleton v2, but WILL be supported in v3!
=> Remove Divide docs

.changeset/thirty-cows-laugh.md, packages/plugin/src/styles/base/core.css
Closes #2538
Migrates the Skeleton plugin base styles from the -webkit- vendor prefix to the new modern standards described here:
- https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
- https://developer.chrome.com/docs/css-ui/scrollbar-styling
This matches the exact implementation in Skeleton v3, which better prepares for the transition going forward.
Please read and apply all [contribution …
=> Update to modern standard for scrollbar styles

sites/skeleton.dev/src/lib/links.ts, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/steppers/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/tables/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/dark-mode/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/tables/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/local-storage-stores/+page.svelte
Closes #2607
Notable changes:
- I've moved `Utilities > Lightswitch` to `Docs > Essentials > Dark Mode` to better align with the v3 approach
- Depreciated components: App Shell, Tables, Steppers
- Depreciated utilities: Persisted Store (aka localstorage stores)
=> Documentation v2 deprecations

.changeset/forty-trains-type.md, packages/skeleton/src/lib/utilities/Toast/Toast.svelte, packages/skeleton/src/lib/utilities/Toast/Toast.test.ts, packages/skeleton/src/lib/utilities/Toast/ToastTest.svelte
Closes #2407
Whenever transitions are enabled and a second toast is triggered immediately after the first one is closed, the toast wrapper is removed from the DOM and the second toast is not displayed.
This happens because the wrapper depends on a IF block thats only true when theres a toast on the queue, but when a first toast `A` is removed and a second one `B` is immediately added it seems the update of the removal of the toast wrapper, scheduled by the removal of `A` is executed after `A` outro animation ends, in this case `B` will be shown for a mere moment and then the wrapper is removed, but it should be visible since `B` is on the queue.  
Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow …
=> Bugfix/toast transition error when triggered/closing at the same tick

.changeset/four-cherries-arrive.md, packages/skeleton/src/lib/components/Avatar/Avatar.svelte, packages/skeleton/src/lib/components/Avatar/Avatar.test.ts, sites/skeleton.dev/src/routes/(inner)/components/avatars/+page.svelte
Closes #2625
This implements the following changes:
1. Moved `$$restProps` up to the parent `<figure>` element to ensure it's usable in all variations. This also enables support for hex value background colors to be provided via `<Avatar style="background-color: #bada55">`
2. Keeps the `fallback` prop to maintain backwards compatibility, while introducing a default slot to provide any user-supplied content, be that an image, text, or an icon.
3. Updated the documentation page to showcase the new slot usage.
Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please …
=> v2 Avatars - restProps and fallback slot support

package.json, packages/skeleton-react/package.json, pnpm-lock.yaml, sites/next.skeleton.dev/package.json
pnpm offers a feature that allows [scripts to run simultaneously](https://pnpm.io/cli/run#running-multiple-scripts), removing the need for us to use the `concurrently` package. Just one less dependency to worry about.
=> chore: Replace `concurrently` with a native pnpm feature

sites/skeleton.dev/src/routes/(inner)/docs/contributing/requirements/+page.svelte
Removed duplicate word "core" in the following sentence in the "Dependencies" section in the contribution requirement docs: "Please sync with a core core maintainer if this is required."
=> chore: remove duplicate word

packages/skeleton-react/src/lib/components/Tabs/Tabs.tsx, packages/skeleton-svelte/src/lib/components/Tab/Tabs.svelte, packages/skeleton-svelte/src/lib/components/Tab/TabsControl.svelte, sites/next.skeleton.dev/src/components/docs/Preview.tsx
Closes #2591
- Update docs tabs to match the the Skeleton design aesthetic.
- Minor cosmetic change to the Svelte and React table component (adheres to theme border width)
=> NEXT: doc tabs redesigned to match Skeleton

pnpm-lock.yaml, sites/next.skeleton.dev/package.json
Plugin had a bug causing errors, this has been resolved in 0.2.7. This PR simply bumps the dep
=> Bugfix: Bump `vite-plugin-pagefind`

sites/next.skeleton.dev/src/components/docs/Search.svelte
Fixed a small oversight with the search feature for the doc site.
For example when I was on `/docs/components/accordion/svelte` and I opened to search modal to go to: `/docs/components/accordion/svelte#api` the modal would stay open. To fix this I added a `onclick` to all `a` tags in the search modal that close the modal upon clicking any result.
=> Added onclose handlers for dialog

.changeset/mean-schools-double.md, packages/skeleton/src/plugin/components/forms.css
Closes #2665 
The default transition duration was 100ms, making it too fast to see properly. See the issue for before and after videos
=> Increase default transition duration to 300ms to avoid a white flash

sites/next.skeleton.dev/src/content/docs/design/themes.mdx, sites/themes.skeleton.dev/src/lib/components/previews/CodeGen.svelte, sites/themes.skeleton.dev/src/lib/state.svelte.ts
Closes #2699
- Custom themes are now generated with the proper structure
- Custom theme names have basic validation `[A-Za-z0-9_]`
- Minor fixes to the v3 doc > themes information
=> NEXT: Resolve custom theme and doc errors

.changeset/unlucky-keys-brake.md, packages/skeleton/src/lib/components/AppRail/AppRailAnchor.svelte
Closes #2662
Removes the extra role and forward events from the `<AppRailAnchor>` component. Svelte was throwing a11y errors for these because they are invalid on an anchor element.
=> Resolve A11y errors for AppRailAnchor

.changeset/chatty-ties-sell.md, packages/skeleton/src/lib/components/InputChip/InputChip.svelte
Closes #2737
I added the same code FileDropzone uses to add restProps
=> fix: add restProps to InputChip

.changeset/stale-poets-sell.md, .vscode/extensions.json, .vscode/settings.json, packages/skeleton-react/src/lib/components/Accordion/Accordion.tsx, packages/skeleton-react/src/lib/components/AppBar/AppBar.tsx, packages/skeleton-react/src/lib/components/Navigation/Navigation.tsx, packages/skeleton-react/src/lib/components/Tabs/Tabs.tsx, packages/skeleton-react/src/lib/utils/react-compose.ts, packages/skeleton-react/src/routes/components/accordions.tsx, packages/skeleton-react/src/routes/components/app-bars.tsx, packages/skeleton-react/src/routes/components/avatars.tsx, packages/skeleton-react/src/routes/components/navigation.tsx, packages/skeleton-react/src/routes/components/progress-rings.tsx, packages/skeleton-react/src/routes/components/progress.tsx, packages/skeleton-react/src/routes/components/ratings.tsx, packages/skeleton-react/src/routes/components/switch.tsx, packages/skeleton-react/src/routes/components/tabs.tsx, packages/skeleton-react/src/routes/components/test.tsx, packages/skeleton-react/tsconfig.json, packages/skeleton-react/tsconfig.package.json, packages/skeleton-react/vite.config.ts, sites/next.skeleton.dev/src/content/docs/resources/contribute/components.mdx
Addresses one issue raised in #2733  (side note: I will from now on open smaller issues, this was just an easy target)
This PR makes 2 notable changes. 
1. Adds a path alias to `vite.config.ts`, `tsconfig.json`, and `tsconfig.package.json` to redirect the standard alias `@` to `__dirname/src`.
2. All components that rely on composition and previously used the `reactCompose` function, now instead implement `Object.assign` directly.
It's nice to make a small, easy change this time.
Changesets have been added. I'll just need to push one more commit to update my message (my mistake, I forgot to follow conventional commit standards).
=> Remove `reactCompose` utility

.prettierignore, sites/next.skeleton.dev/src/content/docs/design/presets.mdx
Added `.mdx` files to `.prettierignore` by adding it to the root.
As @endigo9740 attempted before, nested `.prettierignore` files don't work with prettier as per: https://github.com/prettier/prettier/issues/4081.
The CI passing in this PR should prove that it works as expected since the codeblocks are working and prettier is passing, which wasn't the case before.
=> fix: prettier mdx

packages/skeleton-react/src/lib/components/Switch/Switch.tsx, packages/skeleton-svelte/src/lib/components/Switch/Switch.svelte
Svelte used `inline`, React used `flex`, removing both has the same result.
=> feat: remove/sync base classes switch

sites/skeleton.dev/src/lib/modals/examples/ModalExampleForm.svelte
not relevant
example modal with custom component from docs had a missing prop.
bugfix: in modal component example; added dynamic buttonTextSubmit param from parent
- [nc ] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [nc ] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [nc ] Ensure Prettier linting is current - run `pnpm format`
- [nc ] All test cases are passing - run `pnpm test`
- [nc ] Includes a changeset (if relevant; see above)
nc = non compat with github quick pr feature
=> patch: buttonTextSubmit param not working in modal component example

sites/next.skeleton.dev/src/content/docs/tailwind/forms.mdx
Followup of https://github.com/skeletonlabs/skeleton/discussions/2765
Adds instructions on how to install the Tailwind Forms plugin as it is required for Skeleton's styles to work correctly.
I mostly copied the v2 docs, with some minor changes.
*new v3 docs vs v2*
The "contributing" page is awesome, never seen such a well-written guide!
In case I should change anything about this PR, please let me know. Edits by maintainers are enabled too.
=> tailwind/forms: Install Tailwind Plugin instructions

sites/skeleton.dev/src/lib/components/DocsFooter/DocsFooter.svelte, sites/skeleton.dev/src/routes/home-partials/HomeHeroComponents.svelte
#2788
Drops Twitter, adds Bluesky social links in it's place for the v2 doc site.
=> v2 Docs - Replace Twitter with Bluesky social link

sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx
Closes #2798 
The @svelte-add/tailwindcss package is deprecated and recommends using `svelte-add tailwindcss`: https://github.com/svelte-add/tailwindcss
=> use current svelte-add syntax to install tailwind

sites/next.skeleton.dev/src/content/docs/resources/cookbook/image-layouts.mdx, sites/next.skeleton.dev/src/examples/resources/cookbook/image-layouts/ExampleFeatured.astro, sites/next.skeleton.dev/src/examples/resources/cookbook/image-layouts/ExampleGrid.astro, sites/next.skeleton.dev/src/examples/resources/cookbook/image-layouts/ExampleMasonry.astro, sites/next.skeleton.dev/src/examples/resources/cookbook/image-layouts/ExampleQuad.astro
Adds image layouts from v2 Blocks to v3 Cookbook. Includes two new layouts,
- Quad
- Featured
The page seems laggy on my local dev, it might be all the image URLs loading at full size. I can implement some image optimization features from Astro, but was trying to minimize any maintainable image assets in the codebase for now. It would also complicate the interaction between example components and raw code if we are maintaining a different component for the docs than what the example raw code is showing.
=> NEXT: Cookbook Image Layouts

.changeset/pre.json, .changeset/strong-tables-whisper.md, packages/skeleton-react/src/lib/components/ProgressRing/ProgressRing.test.tsx, packages/skeleton-react/src/lib/components/Rating/Rating.test.tsx, packages/skeleton-react/src/lib/components/Rating/Rating.tsx, packages/skeleton-react/src/lib/components/Segment/Segment.test.tsx, packages/skeleton-react/src/lib/components/Switch/Switch.test.tsx, packages/skeleton-react/src/lib/components/Tabs/Tabs.test.tsx, packages/skeleton-react/src/routes/components/ratings.tsx
#2805 
Updates and add tests after the recent Zag integration in #2778. See also:
- https://github.com/skeletonlabs/skeleton/pull/2813
=> NEXT: Resolve Unit Tests - Part 2

sites/next.skeleton.dev/src/content/docs/components/navigation/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/navigation/react.mdx, sites/next.skeleton.dev/src/content/docs/components/navigation/svelte.mdx
Closes #2820
Hotfix: Restore v3 Navigation Docs that was accidentally removed during the Zag updates.
=> NEXT: hotfix to restore v3 navigation docs

.changeset/stale-taxis-kneel.md, packages/skeleton-react/package.json, pnpm-lock.yaml
Closes #2829 
Moves react deps to peerDeps.
=> Move `react` and `react-dom` to `peerDependencies`

.changeset/wicked-seahorses-itch.md, packages/skeleton-react/src/lib/components/Segment/Segment.tsx, packages/skeleton-react/src/lib/components/Segment/types.ts, packages/skeleton-react/src/lib/components/Switch/Switch.tsx, packages/skeleton-react/src/lib/components/Switch/types.ts, packages/skeleton-svelte/src/lib/components/Segment/SegmentItem.svelte, packages/skeleton-svelte/src/lib/components/Segment/types.ts, packages/skeleton-svelte/src/lib/components/Switch/Switch.svelte, packages/skeleton-svelte/src/lib/components/Switch/types.ts, packages/skeleton/src/plugin/base/core.css
Closes #2806
~~Resolve global focus states for native elements and Zag-based components.~~
Implements a common global `.focused` class that can be used to visualize focus state within Zag-base components.
=> NEXT: Improved focus states

.changeset/stupid-lizards-happen.md, sites/skeleton.dev/src/routes/(inner)/docs/themes/+page.svelte
- use css property `font-face: swap` instead of preloading the font to not block rendering
Closes #2835
Following the previously recommended guide to Preload fonts makes the font loading event block the rendering of the website and heavily affect LCP. Removing it and using the CSS property `font-face` to handle events on font loading leads to no flickering, and doesn't affect LCP.
Please read and apply all [contribution …
=> docs(themes): update `Preloading Fonts` section

.changeset/swift-kings-float.md, packages/skeleton-svelte/src/lib/components/Segment/Segment.svelte
Closes #2857
Removing the `$effect` and resolving the issue linked above.
=> next: remove excessive logs in the segment component

sites/next.skeleton.dev/src/examples/design/typography/ListOrdered.astro
Not applicable 
Fix the typography docs in `next`. The list ordered was not displaying as an ordered list.
Before:
After:
Not applicable as it lives within the sites directory.
=> FIX: Typography list ordered example list-disc to list-decimal.

sites/themes.skeleton.dev/src/lib/utils/importer/import-file.ts
Closes #2914
Resolves two issues for theme files generated using the generator itself:
1. Trims whitespace
2. Accounts for double quotes (not just single-quotes) for key/values
=> NEXT Theme Generator double quote import fix

sites/next.skeleton.dev/src/layouts/LayoutRoot.astro, sites/themes.skeleton.dev/src/app.html
#2907
Implements analytics tracking code to the following sites:
- v3 doc site (Astro)
- v3 theme generator (SvelteKit)
=> Analytics tag added to v3 docs and theme genererator

sites/skeleton.dev/src/routes/(inner)/docs/dark-mode/+page.svelte
Closes #2917
Easy enough to spot. Fix typo **Initilize** -> **Initialize**
=> Fix typo Initilize -> Initialize

sites/next.skeleton.dev/src/content/docs/get-started/fundamentals.mdx
No issue created as very minor thing.
Fixes "implementing" being there twice in the fundamentals section of the docs
=> Fix typo in docs (fundamentals page)

.changeset/little-glasses-drive.md, packages/skeleton/package.json, packages/skeleton/tsup.config.ts
Unifies build output by outputting both cjs and esm as tailwind now supports both too.
Also points to correct declaration file in `package.json`.
=> Fixed conflicting build artifacts

.changeset/shaggy-pants-repair.md, sites/skeleton.dev/src/routes/(inner)/components/conic-gradients/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/contributing/style-guide/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/get-started/+page.svelte
Closes #2935 
Updates the invalid svelte.dev links in the documentation
Chore: Updates invalid links in v2 documentations.
=> Chore: Updates invalid links in v2 documentations.

sites/next.skeleton.dev/tailwind.config.js
Closes #2945 
Adjusts glob matcher to only grab content from `dist`.
=> Fix tailwind config content path to only include `dist`.

.changeset/fluffy-rockets-call.md, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte
Closes #2944
Adds an `if` statement around the button to only render it if the snippet is actually passed, this was previously posing an a11y hazard.
=> Only render `<button>` when trigger is present

.changeset/heavy-bugs-obey.md, packages/skeleton/src/plugin/index.ts, sites/next.skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx, sites/next.skeleton.dev/tailwind.config.js, sites/themes.skeleton.dev/tailwind.config.js
Adds a utility function for assembling content globs for skeleton component packages.
=> feat: `contentPath` utility for tailwind's `content` globs

.github/workflows/release-next.yaml, package.json
Re-implements a missing `ci:` command for triggering Changesets for the release process.
=> chore: add publish script

.changeset/swift-students-confess.md, packages/skeleton/src/plugin/index.ts, sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx
Includes two changes:
1. Addresses the type issue with `contentPath` > `fileURL`
2. Updates the Svelte onboarding docs to remove the node types requirement
=> fix: adjust arg type for `contentPath`

packages/skeleton-react/src/lib/components/Navigation/Navigation.tsx, packages/skeleton-react/src/lib/components/Navigation/types.ts, packages/skeleton-svelte/src/lib/components/Navigation/NavTile.svelte, packages/skeleton-svelte/src/lib/components/Navigation/types.ts
Closes #2934 
Make type attribute a props of NavTile component
=> Type as props for Nav Tile component

sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx
None
npm install is not more needed as part of the newest `npx sv` - it's executed automatically as part of npx sv :)
=> Remove npm install as part of sveltekit installation guide

sites/next.skeleton.dev/src/content/docs/resources/cookbook/dialog.mdx, sites/next.skeleton.dev/src/content/docs/resources/cookbook/stepper.mdx, sites/next.skeleton.dev/src/examples/tailwind/forms/ExampleSpecial.astro
Fixed links & typo
Closes #3015 
Closes #3016 
Closes #3018 
- Removed  `http://localhost:4321` so that the redirects are correct in dialog.mdx
- Fixed small typo `presetnation` in the tags of stepper.mdx
- Fixed small mislabeling of `Date Picker` input as `File Input`
=> Small fixed for next docs #3015 & #3016

.changeset/weak-items-destroy.md, packages/skeleton-react/src/lib/components/Switch/Switch.tsx, packages/skeleton-svelte/src/lib/components/Switch/Switch.svelte
Fixes #3010 
Fixes the Switch component having some extra padding to the right when there is no child (they're shown as a label)
**before**
**after**
=> NEXT fix empty switch padding (fixes #3010)

.changeset/blue-moles-swim.md, packages/skeleton-react/src/lib/components/Pagination/Pagination.tsx, packages/skeleton-react/src/lib/components/Pagination/types.ts, packages/skeleton-svelte/src/lib/components/Pagination/Pagination.svelte, packages/skeleton-svelte/src/lib/components/Pagination/types.ts, packages/skeleton-svelte/tailwind.config.js, pnpm-lock.yaml, sites/next.skeleton.dev/src/content/docs/components/pagination/react.mdx, sites/next.skeleton.dev/src/content/docs/components/pagination/svelte.mdx
Closes #2986
Reinstate Pagination count property
=> Bugfix: reinstate Pagination count property

.changeset/silent-rings-whisper.md, packages/skeleton-svelte/src/lib/components/Combobox/Combobox.svelte, packages/skeleton-svelte/src/lib/components/Combobox/types.ts, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte, packages/skeleton-svelte/src/lib/components/Modal/types.ts, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Popover/types.ts, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/types.ts
Closes #3009
Implements consistent Positioner and Z-Index classes to the following Svelte components:
- Popvers
- Tooltips
- Comboboxes
- Modals
=> NEXT Popver - Consistent Positioner and Z-Index Classes

.changeset/hip-poems-perform.md, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte, packages/skeleton-svelte/src/lib/components/Modal/types.ts, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Popover/types.ts, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/types.ts
Closes #2988
Added `base` and `classes` style props to the root element in the following Svelte Popover components:
- Popover
- Tooltip
- Modal
> NOTE: Combobox already had these in place.
=> NEXT Popovers - added base classes to Svelte Popover components

.changeset/slimy-keys-bathe.md, packages/skeleton-svelte/src/lib/components/Combobox/types.ts
Closes #2963
Disables the Zag-based `multiple` prop for the Svelte Combobox, as this is an unsupported feature.
=> NEXT disable combobox multiple prop

sites/next.skeleton.dev/src/content/docs/get-started/fundamentals.mdx
Closes #3041
Update fundamentals doc to reference our use of Lucide for iconography
=> Add Lucide iconography callout to Fundamentals page

.changeset/wild-wolves-wink.md, packages/skeleton-react/src/lib/components/Rating/Rating.tsx
Closes #3037 
The original issue seem to be caused because the span element containing the `key` property wasn't the outmost element, as it was wrapped by an empty element. After removing the empty wrapper element, seems like the warning went away from the console.
=> Set unique key on outmost element for Rating

.changeset/six-cooks-whisper.md, packages/skeleton-svelte/src/lib/components/Modal/types.ts, packages/skeleton-svelte/src/lib/components/Popover/types.ts, packages/skeleton-svelte/src/lib/components/Tooltip/types.ts
Closes #3044
Change the `trigger` prop description for Popover, Modal and Tooltip
=> Change description for triggers

.changeset/healthy-onions-hide.md, packages/skeleton-react/src/lib/internal/nodes.tsx, packages/skeleton-svelte/src/lib/internal/snippets.ts
Closes #2808
Improves the Ratings component half star SVG for React and Svelte.
=> Chore/improve ratings half star SVG

.changeset/lovely-walls-push.md, packages/skeleton/src/plugin/components/buttons.css
Closes #2938
Improve button hover state brightness. I'll note this is a subtle change, but likely we can do with the potentially infinite combination of colors and luminosity. If this continues to be an issue, the next step might be to remove the built-in hover state and leave this up to end users. That way they can tailor it to their individual theme requirements.
3. Commit and push the …
=> NEXT Improve button hover state brightness

sites/next.skeleton.dev/src/examples/components/pagination/Example.svelte, sites/next.skeleton.dev/src/examples/components/pagination/Example.tsx
N/A
The Skeleton Next's docs pagination examples had their column names in the wrong order so the values did not match up. Before and after:
=> NEXT Fix column names in pagination examples

.changeset/tiny-mugs-know.md, packages/skeleton-svelte/src/lib/components/Combobox/Combobox.svelte, packages/skeleton-svelte/src/lib/components/Combobox/types.ts, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte, packages/skeleton-svelte/src/lib/components/Modal/types.ts, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Popover/types.ts, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/types.ts
Closes #2961 
Implement *onclick* for Popover, Modal and Combobox and *onmouseover* for Tooltip. Svelte only.
=> Implement trigger event props

.changeset/sweet-apes-fix.md, packages/necroparser/__mocks__/fs.cjs, packages/necroparser/package.json, packages/necroparser/src/index.ts, packages/necroparser/test/options.test.ts, pnpm-lock.yaml, sites/next.skeleton.dev/scripts/generate-schemas.ts
Continuation of #3068 
Adds `transformProperty` callback to alter the output, we use this for `Snippet` so that they are treated as primitives instead of functions.
=> Feat: Necroparser, resolve `Snippet` to `primitive` typeKind instead of `function`

.changeset/sweet-pens-compare.md, packages/skeleton-react/src/lib/components/Navigation/Navigation.tsx, packages/skeleton-svelte/src/lib/components/Navigation/NavBar.svelte, sites/next.skeleton.dev/src/content/docs/components/navigation/meta.mdx
None
The NavBar currently has both `h-full` & `h-20` applied by default. This means that its height is determined by which class ends up earlier in the CSS. Seems like this was probably an oversight to have both?
=> Remove extra height class from NavBar

.changeset/slow-dancers-stare.md, packages/skeleton/src/lib/utilities/Popup/popup.ts
Closes #3075
Fixed an oversight.
=> Bugfix: CloseQuery has no efffect/Popup close on click

sites/next.skeleton.dev/src/examples/tailwind/forms/Example.astro, sites/next.skeleton.dev/src/examples/tailwind/forms/ExampleGroups.astro, sites/next.skeleton.dev/src/examples/tailwind/forms/ExampleSelection.astro, sites/next.skeleton.dev/src/examples/tailwind/forms/ExampleSpecial.astro
Closes #3087
Astro apparently does complain about an invalid attribute (`className`) being put onto HTML elements so it might just be beneficial to stick to Svelte syntax since it aligns more closely to bare HTML code. Replaced JSX comments with HTML comments and fix an import from `lucide-react` to `lucide-svelte`.
=> Input group example code changes

pnpm-lock.yaml, sites/next.skeleton.dev/astro.config.js, sites/next.skeleton.dev/package.json, sites/next.skeleton.dev/src/layouts/LayoutRoot.astro
Closes #3114
Makes two changes:
1. Updates the Svelte 5 dependency per #3112
2. Implements [Partytown](https://docs.astro.build/en/guides/integrations-guide/partytown/) to move the Analytics script off the main thread.
=> Implements Partytown for Analytic script

.changeset/tender-bees-allow.md, packages/skeleton-cli/README.md, packages/skeleton-cli/src/index.ts, packages/skeleton-cli/src/utility/get-our-package-json.ts
This PR implements that the name, description and version are pulled from the package.json so we only need to define it once.
This removes the need to maintain these in 2 places, since the code/CLI pulls it from the package.json.
```js
const pkg = await getOurPackageJson();
const cli = new Command()
.name(pkg.name)
.description(pkg.description)
.version(pkg.version)
```
=> Feature: Name, description and version are now pulled from the `package.json`.

.changeset/unlucky-poems-rest.md, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-module.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-svelte.ts, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-tailwind-config.ts, packages/skeleton-cli/test/migrate/skeleton-3/fixtures/tailwind-config/no-themes, packages/skeleton-cli/test/migrate/skeleton-3/fixtures/tailwind-config/perserve-config, packages/skeleton-cli/test/migrate/skeleton-3/results/tailwind-config/content-path, packages/skeleton-cli/test/migrate/skeleton-3/results/tailwind-config/content-path-different-index, packages/skeleton-cli/test/migrate/skeleton-3/results/tailwind-config/custom-theme, packages/skeleton-cli/test/migrate/skeleton-3/results/tailwind-config/preset-theme-object-notation
Removes `fixUnusedIdentifiers` calls to lessen the migration noise and edit non skeleton parts of your app.
=> Bugfix (migrate/skeleton-3): Remove `fixUnusedIdentifiers`

.changeset/polite-lions-camp.md, packages/plugin/src/styles/components/forms.css
Fixes wrong displayed checkbox inside input-group.
Bugfix: Exclude checkbox and radio from input-group styles
=> Bugfix: Exclude checkbox and radio from input-group styles

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
n/a
Some minor changes in issue and PR templates
=> Update issue and PR templates

.changeset/twelve-pets-hide.md, packages/skeleton-react/src/lib/components/Accordion/types.ts, packages/skeleton-react/src/lib/components/Avatar/Avatar.test.tsx, packages/skeleton-react/src/lib/components/Avatar/Avatar.tsx, packages/skeleton-react/src/lib/components/Avatar/types.ts, packages/skeleton-svelte/src/lib/components/Avatar/Avatar.svelte, packages/skeleton-svelte/src/lib/components/Avatar/Avatar.test.ts, packages/skeleton-svelte/src/lib/components/Avatar/types.ts
Closes #3100 
Added `style` prop for Avatar
Bumped Svelte up to **5.18.0** in order to make tests work.
=> Style prop for Avatar

sites/skeleton.dev/src/routes/(inner)/actions/filters/+page.svelte, sites/skeleton.dev/src/routes/(inner)/components/app-shell/+page.svelte, sites/skeleton.dev/src/routes/(inner)/docs/transitions/+page.svelte, sites/skeleton.dev/src/routes/(inner)/elements/alerts/+page.svelte, sites/skeleton.dev/src/routes/(inner)/utilities/table-of-contents/+page.svelte
Fix invalided link
This updates the link from https://next.skeleton.dev/docs/get-started/layouts to https://next.skeleton.dev/docs/guides/layouts
=> docs: fixes invalid links

.changeset/dirty-fans-tap.md, .changeset/twenty-planes-argue.md, packages/skeleton-svelte/src/lib/components/Accordion/Accordion.svelte, packages/skeleton-svelte/src/lib/components/Combobox/Combobox.svelte, packages/skeleton-svelte/src/lib/components/Pagination/Pagination.svelte, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Rating/Rating.svelte, packages/skeleton-svelte/src/lib/components/Rating/types.ts, packages/skeleton-svelte/src/lib/components/Segment/Segment.svelte, packages/skeleton-svelte/src/lib/components/Segment/types.ts, packages/skeleton-svelte/src/lib/components/Slider/Slider.svelte, packages/skeleton-svelte/src/lib/components/Tabs/Tabs.svelte, packages/skeleton-svelte/src/lib/components/Tabs/types.ts, packages/skeleton-svelte/src/lib/components/TagsInput/TagsInput.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte, packages/skeleton-svelte/src/routes/components/pagination/+page.svelte
Closes: #3064
Continuation of: #3073
Both @phamduylong and me came to the same conclusion that and `$effect` is likely needed to sync our internal state and the binding aswell as updating the zagjs API, this is mainly caused by the fact we support `bind:` aswell as `on<Event>`.
=> Bugfix: Event handlers and bindings.

.changeset/tall-pigs-perform.md, packages/skeleton-react/src/lib/components/Navigation/Navigation.tsx, packages/skeleton-svelte/src/lib/components/Navigation/NavTile.svelte, packages/skeleton-svelte/src/lib/components/Toast/types.ts
Closes #3085 
Make `id` mandatory on Nav.Tile instances
=> Make Nav.Tile id mandatory and update examples

sites/next.skeleton.dev/scripts/generate-schemas.ts
Closes #3165
The original regex matches the first `skeleton-*`, which can lead to incorrect matches (e.g., "next" instead of "svelte" in `/home/louis/skeleton-next/.../skeleton-svelte/...`). This update ensures it targets the correct package name (e.g., "svelte") by anchoring the match to `/src/lib/components`.
=> Bugfix: schema script directory

pnpm-lock.yaml, sites/next.skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx
Closes #3179
Updates SvelteKit and Next.js onboarding to use pinned version that will avoid Tailwind v4 for now.
=> v3 onboading pinned versions

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/docs_issue.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Closes nothing...Chris reported this in Discord
Use the new GitHub feature
=> Update issue template to set type automatically

.changeset/hip-bikes-doubt.md, packages/skeleton-svelte/src/lib/components/Combobox/Combobox.svelte, packages/skeleton-svelte/src/lib/components/Combobox/types.ts, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte, packages/skeleton-svelte/src/lib/components/Modal/types.ts, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Popover/types.ts, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/types.ts
Closes #3120 
Implemented `disabled` prop for:
- Combobox
- Modal
- Popover
- Tooltip
=> Disabled prop implementation

sites/next.skeleton.dev/src/content/docs/get-started/purgecss.mdx, sites/next.skeleton.dev/src/content/docs/guides/purgecss.mdx
Closes #2881
Ported documentation from [v2 docs](https://www.skeleton.dev/docs/purgecss) with updated changes such as Vite 6 config format.
=> Docs: ported purgecss from v2

.changeset/angry-hats-hear.md, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte
Closes #3204
Set trigger button type to `button` for **Tooltip**, **Popover** and **Modal**
=> Set trigger button type to `button` for Tooltip, Popover and Modal

sites/skeleton.dev/src/routes/(inner)/docs/get-started/+page.svelte
Fixes the typo "Taiwlind" on [Get Started](https://www.skeleton.dev/docs/get-started).
n/a
=> Docs: fix typo on Get Started page

.changeset/stale-coats-build.md, packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte, packages/skeleton-svelte/src/lib/components/Popover/Popover.svelte, packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte
Closes #3206 
Only render button wrapping around `trigger` if the snippet was provided
=> Conditional rendering for trigger button

.changeset/config.json, package.json, pnpm-lock.yaml
See: https://github.com/changesets/changesets/issues/1434#issuecomment-2670928266
Changesets runs the default prettier format *after* bumping versions, we don't want this because we have our own formatter so this would previously cause conflicts, now we won't have formatting issues after releasing.
=> Disable changeset post format step causing formatting issues

.changeset/curly-jobs-sort.md, .changeset/khaki-shoes-type.md, packages/skeleton-react/CHANGELOG.md, packages/skeleton-svelte/CHANGELOG.md, packages/skeleton-svelte/src/lib/components/Avatar/Avatar.svelte
Closes #2408
This PR fixes the bug of avatar component with initials only that causes content to load in the center of screen, when used in AppBar. In fact ive just removed unecessary h-full class in fallbackrender
OBS: I didnt manage to replicate the bug, cause i dont have Safari. (I tried BrowserStack but coudnt reproduce as well). @nullpointerexceptionkek tried too and didn't succeed. Since is a trivial fix, i will submit the PR anyway. Tell if we need some other test.
=> fix(avatar): remove unecessary h-full class in Avatar fallbackBase

package.json
Remove `create-skeleton-app` from the `dev` scripts, we don't want to scaffold apps during development 😄
=> remove create-skeleton-app from dev script

sites/next.skeleton.dev/src/content/docs/components/tabs/meta.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/astro.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/vite-react.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/vite-svelte.mdx, sites/next.skeleton.dev/src/content/docs/get-started/migrate-from-v2.mdx, sites/themes.skeleton.dev/vite.config.ts
- Add `/dist` to `@source` until https://github.com/tailwindlabs/tailwindcss/issues/16038 is fixed.
- Remove unneeded step from v2 -> v3 migration guide.
- Updated `tailwind` to `tailwindcss` default Vite plugin imports.
- Closes #3272
=> Docs: Post RC 2 cleanup

.github/workflows/release-next.yaml
Removed a basically duplicate build step in our CI pipeline that also builds playgrounds and other unneccesary packages.
=> Remove redundant build step, we're already building postinstall

packages/skeleton-react/CHANGELOG.md, packages/skeleton-svelte/CHANGELOG.md, packages/skeleton/CHANGELOG.md, sites/next.skeleton.dev/src/content/docs/components/accordion/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/app-bar/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/avatar/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/file-upload/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/navigation/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/pagination/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/progress-ring/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/progress/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/rating/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/segment/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/slider/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/switch/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/tabs/meta.mdx, sites/next.skeleton.dev/src/content/docs/components/tags-input/meta.mdx
After #3257 got merged the `src/lib` structure was reduced to `src`, the doc links however weren't updated (my bad). This PR fixes that.
=> docs: fix broken component links

.prettierignore
Remove CHANGELOG and lockfiles to prettier ignore, unneccesary formatting. As pointed out by @endigo9740 in #3292.
=> Add files to prettierignore

sites/next.skeleton.dev/src/content/docs/design/themes.mdx, sites/next.skeleton.dev/src/content/docs/resources/contribute/documentation.mdx
Closes #3300
Double hyphens are being rendered into en dash
Need to fix [this](https://github.com/skeletonlabs/skeleton/issues/3300#issuecomment-2702911432)
=> Fix double hyphens

.changeset/calm-adults-lay.md, packages/skeleton/src/utilities/buttons.css, packages/skeleton/src/utilities/chips.css
#3316
Restores and ensure matching styles for default `.btn` and `.chip` hover states.
=> Restore button hover states

.changeset/grumpy-nights-design.md, packages/skeleton/src/utilities/form-groups.css
Closes #3280
Closes #3294
Resolves a number of small style issues with `input-group` elements.
=> Input-Group style fixes

sites/next.skeleton.dev/src/content/docs/components/navigation/react.mdx, sites/next.skeleton.dev/src/content/docs/components/navigation/svelte.mdx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleBarRouting.svelte, sites/next.skeleton.dev/src/examples/components/navigation/ExampleBarRouting.tsx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleRail.svelte, sites/next.skeleton.dev/src/examples/components/navigation/ExampleRail.tsx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleRailExpanded.svelte, sites/next.skeleton.dev/src/examples/components/navigation/ExampleRailExpanded.tsx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleRailRouting.svelte, sites/next.skeleton.dev/src/examples/components/navigation/ExampleRailRouting.tsx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleTiles.svelte, sites/next.skeleton.dev/src/examples/components/navigation/ExampleTiles.tsx, sites/next.skeleton.dev/src/examples/components/navigation/ExampleTilesSelectionReact.txt, sites/next.skeleton.dev/src/examples/components/navigation/ExampleTilesSelectionSvelte.txt
Closes #3198
Updates both the React and Svelte documentation examples for the navigation component to better showcase usage examples. This includes the following:
- Navigation Rail - splits examples between Selection and Routing use cases
- Navigation Rail expanded example now animates between state changes
- Navigation Bar - splits examples between Selection and Routing use cases
- Navigation Tile now covers `href` selection state using URL paths and `selected` prop
1. Navigate to the root of …
=> Navigation Component Examples Reworked

sites/next.skeleton.dev/src/styles/app.css
Works around [#safari](https://github.com/skeletonlabs/skeleton/issues/3279)
Disables the `bg-noise` for now.
=> bugfix: disable bg-noise for now

.changeset/young-moles-sip.md, packages/skeleton-react/package.json, packages/skeleton-svelte/package.json, pnpm-lock.yaml
In preparation for v3 release.
- added `@skeletonlabs/skeleton` as a peer-dependency to `skeleton-react` and `skeleton-svelte`
- removed some minor unnecessary and redundant bits
=> chore: audit `package.json`s

.changeset/metal-ravens-tell.md, packages/skeleton-react/src/components/ProgressRing/ProgressRing.tsx, packages/skeleton-svelte/src/components/ProgressRing/ProgressRing.svelte
Closes #3222
Partially improves #2991
Fixes the progress by adding @nullpointerexceptionkek's suggestion of applying the `viewBox` prop.
=> fix(progress-ring): Fix progress ring being 100% on Safari

sites/next.skeleton.dev/src/content/docs/get-started/core-api.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/astro.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/nextjs.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/other.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/sveltekit.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/vite-react.mdx, sites/next.skeleton.dev/src/content/docs/get-started/installation/vite-svelte.mdx, sites/next.skeleton.dev/src/content/docs/get-started/migrate-from-v2.mdx, sites/next.skeleton.dev/src/layouts/LayoutDoc.astro, sites/next.skeleton.dev/src/layouts/LayoutRoot.astro
Closes #3355
Implements the final v3 doc changes to prepare for launch.
=> v3 Docs - Prepare for Launch

.changeset/config.json, .changeset/pre.json, .github/workflows/release.yaml
- replaces the `next` release workflow for our a `main` one to publish `@latest`
- exits prerelease mode
=> chore: update CI for release

.changeset/vast-icons-thank.md, packages/skeleton/src/utilities/form-selects.css
Closes #3400 
I don't see why should the style rules deleted in this PR should exist.
(Edit from Hugo, this is the difference on windows, for reference for @endigo9740):
Before (dark):
After (dark):
Before (light):
After (light):
=> Remove selected options custom styles

.github/pull_request_template.md
I don't think this applies anymore
- **this v**
- **this ^**
=> chore: replace v3 next branch mention

.changeset/cool-beers-call.md, sites/skeleton.dev/src/components/docs/TableOfContents.astro, sites/skeleton.dev/src/examples/guides/cookbook/table-of-contents/Example.astro
Closes #3431
Adds back missing spacing in table of contents components (both on site and cookbook) as it was removed by a Tailwind v4 breaking change (see issue).
If the title should keep being a `<span>`, then `space-y` should be removed and `mt-2` added to the content instead.
=> fix: add missing spacing in table of contents

.changeset/pink-teeth-throw.md, packages/skeleton/src/utilities/form-selects.css
Closes #3395
Removes `padding-inline` - which was unintentionally affecting the native arrow and allowing it to overlap text.
=> Bugfix for Select arrow and padding

.changeset/few-vans-doubt.md, packages/skeleton/src/utilities/cards.css
Closes #3448 
Make the hover style apply correctly (to the card, not any links that may be in it).
=> fix: apply card hover style correctly

.changeset/slick-waves-throw.md, packages/skeleton-cli/src/commands/migrate/migrations/skeleton-3/transformers/transform-svelte.ts
This thread on our Discrd: https://discord.com/channels/1003691521280856084/1352848490656432188 shows our migration CLI choking on `script` tag stuff which was manually parsed. Turns out Svelte provides these anyways, so we swap out our manually (janky) way of parsing it.
=> bugfix: simplify script parsing.

playgrounds/skeleton-core/src/pages/design/colors.astro
Closes #3447 
fixes the color pairings section in the `skeleton-core` playground:
fixed:
=> fix missing color pairings

.changeset/plain-jobs-think.md, packages/skeleton-svelte/src/components/FileUpload/FileUpload.svelte
Uses the `file` object instead of `file.name` to prevent the component crashing when passing in duplicate file name's.
Using the object works because every object created is a unique referenced "thing" in memory and thus preventing conflicts to ever happen, even if all the properties have the same value.
See: https://discord.com/channels/1003691521280856084/1356229397929267362
=> fix(FileUpload): conflicting each key

sites/skeleton.dev/src/content/docs/design/themes.mdx
Closes #3464 
Just updates docs to use 'body' in selector to demonstrate themeing in CSS examples.
See screencapture below:
=> Append body selector to CSS example for theme docs - see: Theme background examples should target `<body>` #3464

sites/skeleton.dev/src/content.config.ts, sites/skeleton.dev/src/content/docs/components/toast/meta.mdx
Partially closes #3469
We should actually add the tags to the sidebar once #3479 is merged.
Adds `stability` prop to `content.config` and patches toast title to include `(beta)`
=> docs: mark toast as beta

.changeset/lovely-carrots-enjoy.md, packages/skeleton-react/src/components/TagsInput/TagsInput.test.tsx, packages/skeleton-react/src/components/TagsInput/TagsInput.tsx, packages/skeleton-svelte/src/components/TagsInput/TagsInput.svelte, packages/skeleton-svelte/src/components/TagsInput/TagsInput.test.ts
Closes #3460 
Add hidden input to `TagsInput` component, allowing the value to be submitted in a form.
=> feat: add hidden input for TagsInput

.changeset/cruel-months-tap.md, packages/skeleton-cli/package.json
Adds `skeleton` to our bin path so you can do `npx skeleton` instead of `npx @skeletonlabs/skeleton-cli`.
=> feat: skeleton bin path

packages/cli/CHANGELOG.md, packages/cli/package.json, sites/skeleton.dev/src/content/docs/resources/contribute/get-started.mdx
Just removes some old references to the old CLI name.
=> chore: cleanup skeleton-cli rename junk

sites/skeleton.dev/src/components/docs/Navigation.astro
Closes #3528
Aims to restore the missing Headless Components navigation section. This was lost during a recent refactor.
=> Restore Headless Components section

.changeset/light-moles-sip.md, packages/skeleton/src/utilities/form-inputs.css
Closes #3520
Remove Color input border in Firefox
=> Remove Color input border in Firefox

sites/skeleton.dev/src/content/docs/components/toast/meta.mdx, sites/skeleton.dev/src/content/docs/components/toast/react.mdx, sites/skeleton.dev/src/content/docs/components/toast/svelte.mdx
Closes #3525
Fixed an issue where the Toast docs refer to a `message` key in place o `title`. And move the feature from `beta` status to stable.
=> Fix Toast typo, move to stable

sites/skeleton.dev/src/components/docs/FigmaBuyNow.astro
The checkout modal was not opening on the first click, and the dark theme was not successfully detected.
=> fix: update theme detection and opening modal on first load

sites/skeleton.dev/src/examples/tailwind/forms/ExampleSelection.astro
Closes #3534
Update docs to no longer recommend `<select>` element variants like `size` or `multiple`. Note the styles for these will remain in place, nothing is being removed in v3.0. But in Skeleton v4.0 we may properly remove support for these. As such recommendations have been added for moving to a custom component. Additionally, Zag.js has recently introduce a beta Listbox component. We will aim to adopt this asap.
2. Run `pnpm …
=> Remove support for Select element variants

packages/skeleton-svelte/src/components/Modal/types.ts, packages/skeleton-svelte/src/components/Popover/types.ts, packages/skeleton-svelte/src/components/Tooltip/types.ts
eg.
```
<Popover
onclick={(e: MouseEvent) => {
// typescript is complaining here 
// do something with event
e.stopImmediatePropagation();
}}
>
```
Improve typing for onclick function, so that the event can be accessed without ts errors.
=> Add MouseEvent types for event handlers

.changeset/icy-insects-throw.md, packages/skeleton-svelte/src/components/Tooltip/Tooltip.svelte
None
This PR fixes an issue where the `zIndex` of a tooltip was not correctly applied when an arrow element was present. As a result zIndex was ignored on the tooltip with arrows.
Example code:
```svelte
<section class="border border-surface-200-800 space-y-4 p-20 flex justify-center items-center flex-col">
<span class="z-10 bg-surface-200">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</span>
<Tooltip
open={openState}
onOpenChange={(e) => (openState = e.open)}
positioning={{ placement: 'top' }}
openDelay={0}
triggerBase="btn preset-tonal"
contentBase="card preset-filled p-4"
zIndex="40"
arrow
>
{#snippet trigger()}Hover Me{/snippet}
{#snippet content()}This is a tooltip.{/snippet}
</Tooltip>
</section>
```
Previous behavior:
Behavior with patch:
Please read …
=> Fix: Tooltip z-index was not working with an arrow

sites/skeleton.dev/src/content/docs/get-started/introduction.mdx, sites/skeleton.dev/src/layouts/LayoutDoc.astro
Closes #3563 
- Fixed the extra bottom padding appearing appearing in end of all the pages of the docs
- Fixed the "Additional Benefits" Grid overlapping at smaller breakpoints
- grid is now as it is supposed to be
- No more extra bottom padding
=> Fixed Grid Overlapping and Extra Padding Issue

.changeset/rare-dodos-swim.md, packages/skeleton-svelte/src/components/Modal/types.ts, packages/skeleton-svelte/src/components/Popover/types.ts, packages/skeleton-svelte/src/components/Tooltip/types.ts, sites/skeleton.dev/scripts/generate-schemas.ts, sites/skeleton.dev/tsconfig.json, sites/themes.skeleton.dev/src/lib/components/generator/Controls/ControlsColors.svelte
Closes #3583
Resolves a number of small issues tripping up our CI checks:
4. Run `pnpm changeset` and follow the prompts
5. Commit and push the changeset before flagging your PR review for review.
=> Resolve small errors tripping up our CI process

sites/skeleton.dev/src/content/docs/get-started/migrate-from-v2.mdx
Closes #3573
Updates the v2 migration guide regarding the usage of `@apply`. This can sometimes trip up the Tailwind migration CLI, so these steps are recommended for most users.
=> Improve Migration steps for TW apply

playgrounds/skeleton-core/src/pages/components/buttons.astro, sites/skeleton.dev/src/components/docs/Drawer.astro, sites/skeleton.dev/src/components/docs/Footer.astro, sites/skeleton.dev/src/components/docs/Header.astro, sites/skeleton.dev/src/components/docs/Lightswitch.astro, sites/skeleton.dev/src/content/docs/headless/bits-ui.mdx, sites/skeleton.dev/src/examples/guides/cookbook/scroll-containers/ExampleCarousel.astro, sites/skeleton.dev/src/examples/guides/cookbook/scroll-containers/ExampleMultiColumn.astro, sites/skeleton.dev/src/examples/tailwind/buttons/Example.astro
Closes #3588 
Added title and aria-label fields to all btn-icon elements in documentation and static files.
- Add accessibility attributes to documentation examples and static files
- Update playgrounds/skeleton-core/src/pages/components/buttons.astro
- Update sites/skeleton.dev/src/components/docs/Header.astro
- Update sites/skeleton.dev/src/components/docs/Lightswitch.astro
- Update sites/skeleton.dev/src/components/docs/Drawer.astro
- Update sites/skeleton.dev/src/content/docs/headless/bits-ui.mdx
- Update sites/skeleton.dev/src/examples/guides/cookbook/scroll-containers/ExampleCarousel.astro
- Update sites/skeleton.dev/src/examples/guides/cookbook/scroll-containers/ExampleMultiColumn.astro
- Update sites/skeleton.dev/src/examples/tailwind/buttons/Example.astro
Also tracked component …
=> docs: add aria-label and title attributes to btn-icon elements

.changeset/witty-files-matter.md, packages/skeleton/src/base/globals.css, packages/skeleton/src/utilities/form-inputs.css, packages/skeleton/src/utilities/form-textareas.css
Closes #3605
Drop individual utility element placeholder styling for a singular global placeholder color value. This should actually prove easier for users to overwrite if they wish to customize this value on their own, while providing a blanket default for any and all input usage.
=> Bugfix for consistent input placeholder text color

sites/skeleton.dev/src/examples/components/navigation/ExampleTilesSelectionSvelte.txt
Each `link` is destructured into `label` and `href` so refer to `href` directly
=> docs: remove unreferenced `link`

sites/skeleton.dev/src/components/homepage/HomePlayground.astro
Closes #3519
Adds the functional Stackblitz REPL links for each framework on the doc homepage.
=> Add REPL links to documentation homepage

.changeset/ninety-trams-own.md, packages/skeleton/src/utilities/form-groups.css
Closes #3558
Automatically apply border-radii to the first and last child of the input group.
They were missing before and leaving a small visual gap when the input was focused
=> Input group border-radii for children

.changeset/cyan-brooms-run.md, .changeset/sharp-crabs-smash.md, packages/skeleton-svelte/src/components/Combobox/Combobox.svelte, packages/skeleton-svelte/src/components/Combobox/types.ts, sites/skeleton.dev/src/content/docs/integrations/popover/svelte.mdx
Closes #3600
Closes #3328
This PR addresses the issues reported in #3600, where the Combobox component experiences desynchronization between the provided data and the filtered options. The root cause is the internal "contains" filter logic, which always executes before any external handlers (e.g., onInputValueChange). This results in the data being one step behind, causing lag in scenarios involving dynamic filtering, such as minimum length checks or asynchronous API fetches.
To resolve this, I've introduced an optional boolean prop disableAutoFilter (default: false). When set to true, the internal filtering is skipped, allowing users full control over data updates via their own onInputValueChange handler. This ensures seamless handling of custom filtering logic without interference from …
=> feat: add disableAutoFilter prop to Combobox for custom filtering

sites/skeleton.dev/src/content/docs/components/rating-group/react.mdx, sites/skeleton.dev/src/content/docs/components/rating-group/svelte.mdx
Rating Group was missing API Reference, now added.
=> Docs: Add API Reference to Rating Group

sites/skeleton.dev/scripts/generate-type-documentation/framework.ts, sites/skeleton.dev/scripts/generate-type-documentation/index.ts, sites/skeleton.dev/scripts/generate-type-documentation/parser.ts, sites/skeleton.dev/src/components/docs/ApiTable.astro, sites/skeleton.dev/src/content.config.ts
Closes #3689
Pulls the class list to a code block above the props table. Filters the class attribute out of the props table.
=> API Ref Table Improvements

packages/skeleton/package.json, sites/skeleton.dev/src/app.css, sites/skeleton.dev/src/components/ui/header-themes.tsx, sites/skeleton.dev/src/components/ui/header-version.tsx, sites/skeleton.dev/src/components/ui/header.astro
QoL, makes more sense to do now that we have fixed versioning:
=> docs: display version in header
